/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationConversationsDtoChatMessageOutputDto } from './sDJCRMApplicationConversationsDtoChatMessageOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationConversationsDtoChatMessageOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationConversationsDtoChatMessageOutputDto[] | null;
  totalCount?: number;
}
