/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeAttributeOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeAttributeOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeAttributeOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeAttributeOutputDto[] | null;
  totalCount?: number;
}
