/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoAssetMoveAssetMoveOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetMoveAssetMoveOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationAssetManagementDtoAssetMoveAssetMoveOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationAssetManagementDtoAssetMoveAssetMoveOutputDto[] | null;
  totalCount?: number;
}
