/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContactContactUserContactUserOutputDto } from './sDJCRMApplicationContactContactUserContactUserOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationContactContactUserContactUserOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationContactContactUserContactUserOutputDto[] | null;
  totalCount?: number;
}
