/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLABookingDtoBookingOutputDto } from './sDJCRMApplicationLABookingDtoBookingOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationLABookingDtoBookingOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationLABookingDtoBookingOutputDto[] | null;
  totalCount?: number;
}
