/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationProjectDtoProjectOutputDto } from './sDJCRMApplicationProjectDtoProjectOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationProjectDtoProjectOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationProjectDtoProjectOutputDto[] | null;
  totalCount?: number;
}
