/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUnitDtoUnitResOutputDto } from './sDJCRMApplicationUnitDtoUnitResOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationUnitDtoUnitResOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationUnitDtoUnitResOutputDto[] | null;
  totalCount?: number;
}
