/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationLADtoLeaseAgreementOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationLADtoLeaseAgreementOutputDto[] | null;
  totalCount?: number;
}
