/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUnitHandoverDtoUnitHandoverOutputDto } from './sDJCRMApplicationUnitHandoverDtoUnitHandoverOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationUnitHandoverDtoUnitHandoverOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationUnitHandoverDtoUnitHandoverOutputDto[] | null;
  totalCount?: number;
}
