/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryTaskOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryTaskOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationInquiriesDtoInquiryTaskOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationInquiriesDtoInquiryTaskOutputDto[] | null;
  totalCount?: number;
}
