/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationSettingVATDtoSettingVATOutputDto } from './sDJCRMApplicationSettingVATDtoSettingVATOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationSettingVATDtoSettingVATOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationSettingVATDtoSettingVATOutputDto[] | null;
  totalCount?: number;
}
