/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationInquiriesDtoInquiryOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationInquiriesDtoInquiryOutputDto[] | null;
  totalCount?: number;
}
