/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationRemindersDtoReminderSettingOutputDto } from './sDJCRMApplicationRemindersDtoReminderSettingOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationRemindersDtoReminderSettingOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationRemindersDtoReminderSettingOutputDto[] | null;
  totalCount?: number;
}
