/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationRolesDtoRoleDto } from './sDJCRMApplicationRolesDtoRoleDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationRolesDtoRoleDto {
  /** @nullable */
  items?: SDJCRMApplicationRolesDtoRoleDto[] | null;
  totalCount?: number;
}
