/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementContactOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementContactOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationLADtoLeaseAgreementContactOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationLADtoLeaseAgreementContactOutputDto[] | null;
  totalCount?: number;
}
