/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface AbpAuthorizationUsersUserClaim {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  tenantId?: number | null;
  userId?: number;
  /**
     * @minLength 0
     * @maxLength 256
     * @nullable
     */
  claimType?: string | null;
  /** @nullable */
  claimValue?: string | null;
}
