/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationBudgetDtoBudgetOutputDto } from './sDJCRMApplicationBudgetDtoBudgetOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationBudgetDtoBudgetOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationBudgetDtoBudgetOutputDto[] | null;
  totalCount?: number;
}
