/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationWorkOrderWorkOrderDtoWorkOrderOutputDto } from './sDJCRMApplicationWorkOrderWorkOrderDtoWorkOrderOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationWorkOrderWorkOrderDtoWorkOrderOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationWorkOrderWorkOrderDtoWorkOrderOutputDto[] | null;
  totalCount?: number;
}
