/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto } from './sDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto[] | null;
  totalCount?: number;
}
