/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface AbpAuthorizationUsersUserLogin {
  id?: number;
  /** @nullable */
  tenantId?: number | null;
  userId?: number;
  /**
     * @minLength 0
     * @maxLength 128
     */
  loginProvider: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  providerKey: string;
}
