/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUserTenantDtoUserTenantOutputDto } from './sDJCRMApplicationUserTenantDtoUserTenantOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationUserTenantDtoUserTenantOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationUserTenantDtoUserTenantOutputDto[] | null;
  totalCount?: number;
}
