/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquirySiteVisitOutputDto } from './sDJCRMApplicationInquiriesDtoInquirySiteVisitOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationInquiriesDtoInquirySiteVisitOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationInquiriesDtoInquirySiteVisitOutputDto[] | null;
  totalCount?: number;
}
