/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryProposalOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryProposalOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationInquiriesDtoInquiryProposalOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationInquiriesDtoInquiryProposalOutputDto[] | null;
  totalCount?: number;
}
