/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface AbpAuthorizationUsersUserToken {
  id?: number;
  /** @nullable */
  tenantId?: number | null;
  userId?: number;
  /**
     * @minLength 0
     * @maxLength 128
     * @nullable
     */
  loginProvider?: string | null;
  /**
     * @minLength 0
     * @maxLength 128
     * @nullable
     */
  name?: string | null;
  /**
     * @minLength 0
     * @maxLength 512
     * @nullable
     */
  value?: string | null;
  /** @nullable */
  expireDate?: string | null;
}
