/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceOutputDto } from './sDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceOutputDto[] | null;
  totalCount?: number;
}
