/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationTemplateManagementDtoNotificationTemplateMapOutput } from './sDJCRMApplicationTemplateManagementDtoNotificationTemplateMapOutput';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationTemplateManagementDtoNotificationTemplateMapOutput {
  /** @nullable */
  items?: SDJCRMApplicationTemplateManagementDtoNotificationTemplateMapOutput[] | null;
  totalCount?: number;
}
