/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContractProviderContractDtoProviderContractOutputDto } from './sDJCRMApplicationContractProviderContractDtoProviderContractOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationContractProviderContractDtoProviderContractOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationContractProviderContractDtoProviderContractOutputDto[] | null;
  totalCount?: number;
}
