/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoAssetCategoryOrUnitOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetCategoryOrUnitOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationAssetManagementDtoAssetCategoryOrUnitOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationAssetManagementDtoAssetCategoryOrUnitOutputDto[] | null;
  totalCount?: number;
}
