/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersEmployeesDtoEmployeeOutputDto } from './sDJCRMApplicationUsersEmployeesDtoEmployeeOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationUsersEmployeesDtoEmployeeOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationUsersEmployeesDtoEmployeeOutputDto[] | null;
  totalCount?: number;
}
