/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationMultiTenancyDtoTenantDto } from './sDJCRMApplicationMultiTenancyDtoTenantDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationMultiTenancyDtoTenantDto {
  /** @nullable */
  items?: SDJCRMApplicationMultiTenancyDtoTenantDto[] | null;
  totalCount?: number;
}
