/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectManagementDtoDefectInfoOutputDto } from './sDJCRMApplicationDefectDefectManagementDtoDefectInfoOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationDefectDefectManagementDtoDefectInfoOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationDefectDefectManagementDtoDefectInfoOutputDto[] | null;
  totalCount?: number;
}
