/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContactDtoContactSimpleOutputDto } from './sDJCRMApplicationContactDtoContactSimpleOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationContactDtoContactSimpleOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationContactDtoContactSimpleOutputDto[] | null;
  totalCount?: number;
}
