/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryCallOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryCallOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationInquiriesDtoInquiryCallOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationInquiriesDtoInquiryCallOutputDto[] | null;
  totalCount?: number;
}
