/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContractContractDtoContractCategoryOutputDto } from './sDJCRMApplicationContractContractDtoContractCategoryOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationContractContractDtoContractCategoryOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationContractContractDtoContractCategoryOutputDto[] | null;
  totalCount?: number;
}
