/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationWorkOrderWOCategoryDtoWOOutputDto } from './sDJCRMApplicationWorkOrderWOCategoryDtoWOOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationWorkOrderWOCategoryDtoWOOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationWorkOrderWOCategoryDtoWOOutputDto[] | null;
  totalCount?: number;
}
