/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLocalizationDtoLanguageTextListDto } from './sDJCRMApplicationLocalizationDtoLanguageTextListDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationLocalizationDtoLanguageTextListDto {
  /** @nullable */
  items?: SDJCRMApplicationLocalizationDtoLanguageTextListDto[] | null;
  totalCount?: number;
}
