/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryMailOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryMailOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationInquiriesDtoInquiryMailOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationInquiriesDtoInquiryMailOutputDto[] | null;
  totalCount?: number;
}
