/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersCustomersDtoCustomerOutputDto } from './sDJCRMApplicationUsersCustomersDtoCustomerOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationUsersCustomersDtoCustomerOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationUsersCustomersDtoCustomerOutputDto[] | null;
  totalCount?: number;
}
