/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContactDtoContactOutputDto } from './sDJCRMApplicationContactDtoContactOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationContactDtoContactOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationContactDtoContactOutputDto[] | null;
  totalCount?: number;
}
