/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryActivityOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryActivityOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationInquiriesDtoInquiryActivityOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationInquiriesDtoInquiryActivityOutputDto[] | null;
  totalCount?: number;
}
