/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUnitDtoUnitStatusManagementUnitStatusManagementOutputDto } from './sDJCRMApplicationUnitDtoUnitStatusManagementUnitStatusManagementOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationUnitDtoUnitStatusManagementUnitStatusManagementOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationUnitDtoUnitStatusManagementUnitStatusManagementOutputDto[] | null;
  totalCount?: number;
}
