/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseDtoUserDto } from './sDJCRMApplicationUsersUserBaseDtoUserDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationUsersUserBaseDtoUserDto {
  /** @nullable */
  items?: SDJCRMApplicationUsersUserBaseDtoUserDto[] | null;
  totalCount?: number;
}
