/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryReservationOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryReservationOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationInquiriesDtoInquiryReservationOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationInquiriesDtoInquiryReservationOutputDto[] | null;
  totalCount?: number;
}
