/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoProjectUserOutputDto } from './sDJCRMApplicationInquiriesDtoProjectUserOutputDto';

export interface AbpApplicationServicesDtoPagedResultDtoSDJCRMApplicationInquiriesDtoProjectUserOutputDto {
  /** @nullable */
  items?: SDJCRMApplicationInquiriesDtoProjectUserOutputDto[] | null;
  totalCount?: number;
}
