/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface AbpConfigurationSetting {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  /** @nullable */
  tenantId?: number | null;
  /** @nullable */
  userId?: number | null;
  /**
     * @minLength 0
     * @maxLength 256
     */
  name: string;
  /** @nullable */
  value?: string | null;
}
