/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type AbpConfigurationSettingScopes = typeof AbpConfigurationSettingScopes[keyof typeof AbpConfigurationSettingScopes];


export const AbpConfigurationSettingScopes = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_4: 4,
  NUMBER_7: 7,
} as const;
