/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpNotificationsNotificationData } from './abpNotificationsNotificationData';
import type { AbpNotificationsNotificationSeverity } from './abpNotificationsNotificationSeverity';
import type { SystemType } from './systemType';

export interface AbpNotificationsTenantNotification {
  id?: string;
  /** @nullable */
  tenantId?: number | null;
  /** @nullable */
  notificationName?: string | null;
  data?: AbpNotificationsNotificationData;
  entityType?: SystemType;
  /** @nullable */
  entityTypeName?: string | null;
  entityId?: unknown | null;
  severity?: AbpNotificationsNotificationSeverity;
  creationTime?: string;
}
