/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type AbpNotificationsNotificationDataProperties = {[key: string]: unknown | null} | null;
