/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpNotificationsTenantNotification } from './abpNotificationsTenantNotification';
import type { AbpNotificationsUserNotificationState } from './abpNotificationsUserNotificationState';

export interface AbpNotificationsUserNotification {
  id?: string;
  /** @nullable */
  tenantId?: number | null;
  userId?: number;
  state?: AbpNotificationsUserNotificationState;
  notification?: AbpNotificationsTenantNotification;
  /** @nullable */
  targetNotifiers?: string | null;
  /** @nullable */
  readonly targetNotifiersList?: readonly string[] | null;
}
