/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type AbpNotificationsUserNotificationState = typeof AbpNotificationsUserNotificationState[keyof typeof AbpNotificationsUserNotificationState];


export const AbpNotificationsUserNotificationState = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
