/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpNotificationsNotificationDataProperties } from './abpNotificationsNotificationDataProperties';

export interface AbpNotificationsNotificationData {
  /** @nullable */
  readonly type?: string | null;
  /** @nullable */
  properties?: AbpNotificationsNotificationDataProperties;
}
