/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type AbpNotificationsNotificationSeverity = typeof AbpNotificationsNotificationSeverity[keyof typeof AbpNotificationsNotificationSeverity];


export const AbpNotificationsNotificationSeverity = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
