/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpOrganizationsOrganizationUnit as __AbpOrganizationsOrganizationUnit } from './abpOrganizationsOrganizationUnit';

export interface AbpOrganizationsOrganizationUnit {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  /** @nullable */
  tenantId?: number | null;
  parent?: __AbpOrganizationsOrganizationUnit;
  /** @nullable */
  parentId?: number | null;
  /**
     * @minLength 0
     * @maxLength 95
     */
  code: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  displayName: string;
  /** @nullable */
  children?: AbpOrganizationsOrganizationUnit[] | null;
}
