/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppCommentGetCommentByReferenceParams = {
moduleId?: number;
referenceId?: number;
Keyword?: string;
IsInvalid?: boolean;
IsActive?: boolean;
FromDate?: string;
ToDate?: string;
/**
 * @minimum 1
 * @maximum 1000
 */
PageSize: number;
/**
 * @minimum 1
 * @maximum 1000
 */
MaxResultCount?: number;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 0
 * @maximum 2147483647
 */
PageNumber: number;
};
