/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppPlanMaintenanceGetListPlanMaintenanceV2Params = {
Keyword?: string;
ProjectId?: number;
ZoneId?: number;
StatusId?: number;
Year?: number;
};
