/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType } from './sDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType';

export type GetApiExportExportAssetParams = {
TypeId?: SDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType;
ToWarrantDate?: string;
IsActive?: boolean;
ProjectIds?: number[];
UnitIds?: number[];
ZoneIds?: number[];
KeyWord?: string;
TypeLv1Id?: number;
TypeLv2Id?: number;
IsLiquidation?: boolean;
IsIncludeHistorical?: boolean;
IsCurrent?: boolean;
};
