/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppUnitHandoverGetAllParams = {
Keyword?: string;
IsActive?: boolean;
StatusIds?: number[];
ProjectIds?: number[];
UnitId?: number;
FromDate?: string;
ToDate?: string;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
