/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedEnumsLATypeEnum } from './sDJCRMCoreSharedEnumsLATypeEnum';

export type GetApiServicesAppStatisticAppServicesGetDashboardUnitOccDetailsParams = {
nameStore?: string;
fromDate?: string;
toDate?: string;
timeZone?: number;
statusIds?: string;
projectId?: number;
type?: number;
laType?: SDJCRMCoreSharedEnumsLATypeEnum;
};
