/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreInquiriesInquiryConstantsActivityType } from './sDJCRMCoreInquiriesInquiryConstantsActivityType';

export type GetApiServicesAppInquiryGetActivityParams = {
InquiryId?: number;
ContactId?: number;
UnitId?: number;
ActivityType?: SDJCRMCoreInquiriesInquiryConstantsActivityType;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
