/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedEnumsModule } from './sDJCRMCoreSharedEnumsModule';

export type GetApiServicesAppReminderGetReminderParams = {
module?: SDJCRMCoreSharedEnumsModule;
parentId?: number;
};
