/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiExportExportPlanMaintenanceParams = {
Keyword?: string;
ProjectIds?: number[];
StatusIds?: number[];
ZoneIds?: number[];
AssetIds?: number[];
ProviderId?: number;
FromActualStartDate?: string;
ToActualStartDate?: string;
FromCreatedDate?: string;
ToCreatedDate?: string;
};
