/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppInquiryGetListInquiryForLAParams = {
Id?: number;
Keyword?: string;
StatusId?: number;
StatusDetailId?: number;
ClientId?: number;
CompanyId?: number;
ContactId?: number;
TypeId?: number;
AskingRent?: number;
ActualSize?: number;
Size?: number;
FacingId?: number;
ProjectId?: number;
UnitId?: number;
UserIds?: number[];
UnitTypeIds?: number[];
FromDate?: string;
ToDate?: string;
UnitFacilityIds?: number[];
ViewIds?: number[];
UnderUserIds?: number[];
IsExcludeInquiryLA?: boolean;
IsActive?: boolean;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
