/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType } from './sDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType';

export type GetApiServicesAppAssetManagementGetAssetsParams = {
TypeId?: SDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType;
ProjectId?: number;
ZoneId?: number;
ProjectIds?: number[];
UnitIds?: number[];
ZoneIds?: number[];
ToWarrantDate?: string;
KeyWord?: string;
IsActive?: boolean;
TypeLv1Id?: number;
TypeLv2Id?: number;
IsLiquidation?: boolean;
IsMoved?: boolean;
IsIncludeHistorical?: boolean;
IsCurrent?: boolean;
AssetTypeAttributeIds?: number[];
IsAllowanced?: boolean;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
