/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppStatisticAppServicesGetReportBudgetParams = {
nameStore?: string;
fromDate?: string;
toDate?: string;
timeZone?: number;
type?: number;
year?: number;
months?: string;
};
