/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppLeaseAgreementGetLAAmountAfterDiscountParams = {
StartDate?: string;
EndDate?: string;
DiscountIncludeVatPerMonth?: number;
DiscountExcludeVatPerMonth?: number;
LAAmountDiscountIncludeVAT?: number;
LAAmountDiscountExcludeVat?: number;
};
