/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum } from './sDJCRMCoreSharedEnumsDefectConfigurationTypeEnum';

export type GetApiExportExportDefectParams = {
Keyword?: string;
ProjectIds?: number[];
ZoneIds?: number[];
UnitIds?: number[];
PicIds?: number[];
DefectCategoryId?: number;
DefectTypeId?: SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum;
PriorityId?: number;
StageId?: number;
StatusId?: number;
FromCreatedDate?: string;
ToCreatedDate?: string;
RepeatedSearch?: boolean;
IsDelayed?: boolean;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
