/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedEnumsLATypeEnum } from './sDJCRMCoreSharedEnumsLATypeEnum';

export type GetApiServicesAppStatisticAppServicesGetDashboardV1Params = {
nameStore?: string;
thisFromDate?: string;
thisToDate?: string;
lastFromDate?: string;
lastToDate?: string;
timeZone?: number;
statusIds?: string;
projectId?: number;
type?: SDJCRMCoreSharedEnumsLATypeEnum;
};
