/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppUserGetUsersParams = {
RoleId?: number;
TeamId?: number;
Keyword?: string;
IsActive?: boolean;
FromDate?: string;
ToDate?: string;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
