/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppUnitGetListUnitsByProjectParams = {
projectId?: number;
fromDate?: string;
toDate?: string;
unitStatusId?: number;
};
