/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppWorkOrderGetAllParams = {
Keyword?: string;
ProjectIds?: number[];
UnitIds?: number[];
CategoryIds?: number[];
StatusIds?: number[];
ZoneIds?: number[];
AssetTypeLv1Ids?: number[];
AssetTypeLv2Ids?: number[];
FromDate?: string;
ToDate?: string;
FromCompletedDate?: string;
ToCompletedDate?: string;
WarrantyDate?: string;
AssetId?: number;
ProviderId?: number;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
