/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppPlanMaintenanceGetPlanMaintenanceReportCostParams = {
Keyword?: string;
ProjectIds?: number[];
StatusIds?: number[];
ZoneIds?: number[];
AssetIds?: number[];
AssetId?: number;
ServiceProviderId?: number;
FromActualStartDate?: string;
ToActualStartDate?: string;
FromCreatedDate?: string;
ToCreatedDate?: string;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
