/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppContactGetListContactByLAParams = {
Id?: number;
RoleId?: number;
Keyword?: string;
IsActive?: boolean;
OrganizationUnitId?: number;
LevelId?: number;
CountryId?: number;
ProvinceId?: number;
DistrictId?: number;
NationalityId?: number;
FromDate?: string;
ToDate?: string;
CompanyId?: number;
UserIds?: number[];
TypeId?: number;
LeaseAgreementId?: number;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
