/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpNotificationsUserNotificationState } from './abpNotificationsUserNotificationState';
import type { SDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum } from './sDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum';

export type GetApiServicesAppNotificationGetUserNotificationsParams = {
Type?: SDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum;
State?: AbpNotificationsUserNotificationState;
StartDate?: string;
EndDate?: string;
/**
 * @minimum 1
 * @maximum 1000
 */
MaxResultCount?: number;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
};
