/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiExportExportWorkOrderParams = {
Keyword?: string;
ProjectIds?: number[];
UnitIds?: number[];
CategoryIds?: number[];
StatusIds?: number[];
ZoneIds?: number[];
AssetTypeLv1Ids?: number[];
AssetTypeLv2Ids?: number[];
FromDate?: string;
ToDate?: string;
WarrantyDate?: string;
AssetId?: number;
ProviderId?: number;
};
