/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppLanguageGetClientSourceLanguageTextsParams = {
/**
 * @maxLength 128
 */
SourceName: string;
/**
 * @minLength 0
 * @maxLength 128
 */
BaseLanguageName?: string;
/**
 * @minLength 2
 * @maxLength 128
 */
TargetLanguageName: string;
TargetValueFilter?: string;
};
