/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppUnitGetAllParams = {
InquiryId?: number;
Keyword?: string;
ProjectId?: number;
ProjectIds?: number[];
AssignProjectIds?: number[];
IsActive?: boolean;
UnitStatusId?: number;
UnitStatusIds?: number[];
ProvinceId?: number;
DistrictId?: number;
FacingId?: number;
UnitTypeId?: number;
FloorId?: number;
ProductTypeId?: number;
FromDate?: string;
ToDate?: string;
FromPrice?: number;
ToPrice?: number;
FromSize?: number;
ToSize?: number;
UnitTypeIds?: number[];
Ids?: number[];
FacingIds?: number[];
ViewIds?: number[];
FacilityIds?: number[];
ProductTypeIds?: number[];
Sorting?: string;
AlphabetSorting?: boolean;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
