/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppLeaseAgreementGetTerminationNoteParams = {
Id: number;
CreateTerminationDate: string;
TerminationDate: string;
TemplateId?: number;
RefundAmount?: number;
ForfeitAmount?: number;
OffsetAmount?: number;
TransferAmount?: number;
DepositTransNo?: string;
DepositTransSignDate?: string;
};
