/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiExportExportCompanyParams = {
RoleId?: number;
Keyword?: string;
IsActive?: boolean;
OrganizationUnitId?: number;
UserIds?: number[];
IndustryId?: number;
CountryId?: number;
ProvinceId?: number;
DistrictId?: number;
NationalityId?: number;
FromDate?: string;
ToDate?: string;
};
