/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppAuditLogGetAuditLogsParams = {
StartDate?: string;
EndDate?: string;
UserName?: string;
ServiceName?: string;
MethodName?: string;
BrowserInfo?: string;
HasException?: boolean;
MinExecutionDuration?: number;
MaxExecutionDuration?: number;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
