/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppLeaseAgreementGetAllParams = {
Keyword?: string;
IsActive?: boolean;
CompanyId?: number;
ContactId?: number;
ProjectId?: number;
UnitId?: number;
InquiryId?: number;
AdminId?: number;
DealerId?: number;
StatusId?: number;
StageId?: number;
ExpiredIn?: number;
LeaseAgreementAmendmentId?: number;
IsIncludeHistory?: boolean;
UnderUserIds?: number[];
FromDate?: string;
ToDate?: string;
IsShareCommission?: boolean;
Ids?: number[];
IsCurrent?: boolean;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
