/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpNotificationsUserNotificationState } from './abpNotificationsUserNotificationState';
import type { SDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum } from './sDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum';

export type GetApiServicesAppNotificationGetUserNotificationCountsParams = {
Type?: SDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum;
State?: AbpNotificationsUserNotificationState;
StartDate?: string;
EndDate?: string;
};
