/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type GetApiServicesAppInquiryReservationGetAllParams = {
InquiryId?: number;
UnitId?: number;
UnitIds?: number[];
StatusId?: number;
StatusIds?: number[];
UnitOrder?: boolean;
Keyword?: string;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
};
