/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type PostApiDocumentsUploadUnitsParams = {
UniqueId: string;
DocumentName?: string;
DocumentTypeId?: number;
UploadDate?: string;
};
