/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMWebCoreAuthenticationExternalAuthenticateResultModel {
  shouldResetPassword?: boolean;
  /** @nullable */
  passwordResetCode?: string | null;
  /** @nullable */
  returnUrl?: string | null;
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  encryptedAccessToken?: string | null;
  expireInSeconds?: number;
  userId?: number;
}
