/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLocalizationDtoApplicationLanguageListDto {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  /** @nullable */
  tenantId?: number | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  icon?: string | null;
  isDisabled?: boolean;
}
