/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationLADtoDepositLeaseAgreementDepositCollectOutputDto {
  id?: number;
  leaseAgreementId?: number;
  leaseAgreementDepositId?: number;
  /** @nullable */
  receiptNo?: string | null;
  /** @nullable */
  receiptDate?: string | null;
  /** @nullable */
  paymentDate?: string | null;
  /** @nullable */
  remark?: string | null;
  receiptAmount?: number;
  creatorUserId?: number;
  creationTime?: string;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  isActive?: boolean;
}
