/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContractContractDtoContractCategoryOutputDto as __SDJCRMApplicationContractContractDtoContractCategoryOutputDto } from './sDJCRMApplicationContractContractDtoContractCategoryOutputDto';
import type { SDJCRMApplicationContractContractDtoSimpleContractCategoryOutputDto } from './sDJCRMApplicationContractContractDtoSimpleContractCategoryOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationContractContractDtoContractCategoryOutputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  parentId?: number | null;
  parent?: __SDJCRMApplicationContractContractDtoContractCategoryOutputDto;
  /** @nullable */
  childs?: SDJCRMApplicationContractContractDtoSimpleContractCategoryOutputDto[] | null;
  isActive?: boolean;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
}
