/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeAttributeOutputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  isActive?: boolean;
  assetTypeLv1?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto;
  assetTypeLv2?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
}
