/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  surname?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  emailAddress?: string | null;
  /** @nullable */
  profilePictureId?: string | null;
  /** @nullable */
  groupId?: number | null;
}
