/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStartEndDateDto } from './sDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStartEndDateDto';
import type { SDJCRMApplicationPlanMaintenanceDtoPlanTaskInputDto } from './sDJCRMApplicationPlanMaintenanceDtoPlanTaskInputDto';

export interface SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceCreateInputDto {
  assetTypeLv1Id: number;
  /** @nullable */
  assetTypeLv2Id?: number | null;
  projectId: number;
  zoneId: number;
  /**
     * @minLength 0
     * @maxLength 500
     * @nullable
     */
  description?: string | null;
  picId: number;
  statusId: number;
  startDate: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  actualStartDate?: string | null;
  /** @nullable */
  actualEndDate?: string | null;
  repairingCost: number;
  /** @nullable */
  serviceProviderId?: number | null;
  /** @nullable */
  planTasks?: SDJCRMApplicationPlanMaintenanceDtoPlanTaskInputDto[] | null;
  /** @nullable */
  planStartEndDates?: SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStartEndDateDto[] | null;
  /** @nullable */
  assetIds?: number[] | null;
}
