/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto } from './sDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';

export interface SDJCRMApplicationDefectReportingsDtoDefectTypeReportDto {
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  /** @nullable */
  defectCategories?: SDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto[] | null;
  total?: number;
  amount?: number;
  percentage?: number;
  percentageAmount?: number;
}
