/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationMultiTenancyDtoCreateTenantDto {
  /**
     * @minLength 0
     * @maxLength 64
     * @pattern ^[a-zA-Z][a-zA-Z0-9_-]{1,}$
     */
  tenancyName: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  adminEmailAddress: string;
  /**
     * @minLength 0
     * @maxLength 1024
     * @nullable
     */
  connectionString?: string | null;
  isActive?: boolean;
}
