/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseInputDto } from './sDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseInputDto';
import type { SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionUserInputDto } from './sDJCRMApplicationLADtoCommissionLeaseAgreementCommissionUserInputDto';

export interface SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionMasterInputDto {
  id?: number;
  leaseAgreementId?: number;
  dealerCommissionAmount?: number;
  dealerPercent?: number;
  departmentCommissionAmount?: number;
  departmentPercent?: number;
  isManual?: boolean;
  /** @nullable */
  leaseAgreementCommissionPhase?: SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseInputDto[] | null;
  /** @nullable */
  leaseAgreementCommissionUser?: SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionUserInputDto[] | null;
}
