/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAreaCountry } from './sDJCRMCoreAreaCountry';
import type { SDJCRMCoreAreaDistrict } from './sDJCRMCoreAreaDistrict';

export interface SDJCRMCoreAreaProvince {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  provinceCode?: string | null;
  /** @nullable */
  provinceName?: string | null;
  countryId?: number;
  country?: SDJCRMCoreAreaCountry;
  /** @nullable */
  districts?: SDJCRMCoreAreaDistrict[] | null;
  isActive?: boolean;
}
