/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationUserTenantDtoUserTenantOutputDto {
  id?: number;
  /** @nullable */
  gender?: string | null;
  uniqueId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  passport?: string | null;
  /** @nullable */
  emailAddress?: string | null;
  isActive?: boolean;
  /** @nullable */
  nationalityId?: number | null;
  /** @nullable */
  nationalityName?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
}
