/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationContractContractDtoContractCategoryCreateInputDto {
  /** @nullable */
  name?: string | null;
  /**
     * @minLength 0
     * @maxLength 5000
     * @nullable
     */
  description?: string | null;
  /** @nullable */
  parentId?: number | null;
  isActive?: boolean;
}
