/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreLeaseAgreementsLeaseAgreementConstantFeeType } from './sDJCRMCoreLeaseAgreementsLeaseAgreementConstantFeeType';

export interface SDJCRMCoreSettingDtoFeeTypeOutputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  code?: string | null;
  typeId?: SDJCRMCoreLeaseAgreementsLeaseAgreementConstantFeeType;
  sortOrder?: number;
  isActive?: boolean;
}
