/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionUserOutputDto {
  id?: number;
  leaseAgreementId?: number;
  leaseAgreementCommissionMasterId?: number;
  userId?: number;
  user?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  commissionAmount?: number;
  percent?: number;
}
