/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositCollect } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositCollect';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDeposit {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement;
  /** @nullable */
  description?: string | null;
  vatPercent?: number;
  vatAmount?: number;
  depositAmount?: number;
  depositDate?: string;
  isActive?: boolean;
  /** @nullable */
  leaseAgreementDepositCollect?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositCollect[] | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
