/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationContactContactEmailContactEmailOutputDto {
  id?: number;
  contactId?: number;
  /** @nullable */
  contactName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  isPrimary?: boolean | null;
  /** @nullable */
  isOptedOut?: boolean | null;
  /** @nullable */
  isInvalid?: boolean | null;
  isActive?: boolean;
}
