/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreCompanyEntitiesCompany } from './sDJCRMCoreCompanyEntitiesCompany';
import type { SDJCRMCoreContactsEntitiesContact } from './sDJCRMCoreContactsEntitiesContact';
import type { SDJCRMCoreContactsEntitiesLevel } from './sDJCRMCoreContactsEntitiesLevel';

export interface SDJCRMCoreCompanyEntitiesCompanyContact {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  contactId?: number;
  contact?: SDJCRMCoreContactsEntitiesContact;
  companyId?: number;
  company?: SDJCRMCoreCompanyEntitiesCompany;
  /** @nullable */
  levelId?: number | null;
  level?: SDJCRMCoreContactsEntitiesLevel;
  /** @nullable */
  title?: string | null;
}
