/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationSessionsDtoApplicationInfoDtoFeatures } from './sDJCRMApplicationSessionsDtoApplicationInfoDtoFeatures';

export interface SDJCRMApplicationSessionsDtoApplicationInfoDto {
  /** @nullable */
  version?: string | null;
  releaseDate?: string;
  /** @nullable */
  features?: SDJCRMApplicationSessionsDtoApplicationInfoDtoFeatures;
}
