/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUserTenantDtoSimpleUserTenantOutputDto } from './sDJCRMApplicationUserTenantDtoSimpleUserTenantOutputDto';

export interface SDJCRMApplicationLADtoLeaseAgreementUserTenantOutputDto {
  id?: number;
  userTenantId?: number;
  leaseAgreementId?: number;
  userTenant?: SDJCRMApplicationUserTenantDtoSimpleUserTenantOutputDto;
  isActive?: boolean;
  isPrimary?: boolean;
}
