/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationNewsNewsCategoryOutputDto } from './sDJCRMApplicationNewsNewsCategoryOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';
import type { SDJCRMCoreSharedDocumentsDtoDocumentOutput } from './sDJCRMCoreSharedDocumentsDtoDocumentOutput';

export interface SDJCRMApplicationNewsNewsOutputDto {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  uniqueId?: string;
  subjectNameId?: string;
  contentNameId?: string;
  categoryId?: number;
  shortDescriptionNameId?: string;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  shortDescription?: string | null;
  startTime?: string;
  endTime?: string;
  sortOrder?: number;
  isActive?: boolean;
  isPublic?: boolean;
  category?: SDJCRMApplicationNewsNewsCategoryOutputDto;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  file?: SDJCRMCoreSharedDocumentsDtoDocumentOutput;
}
