/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationNewsNewsCategoryOutputDto {
  id?: number;
  nameId?: string;
  /** @nullable */
  name?: string | null;
  isActive?: boolean;
  sortOrder?: number;
}
