/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAreaCountry } from './sDJCRMCoreAreaCountry';
import type { SDJCRMCoreAreaDistrict } from './sDJCRMCoreAreaDistrict';
import type { SDJCRMCoreAreaProvince } from './sDJCRMCoreAreaProvince';
import type { SDJCRMCoreProjectsProject } from './sDJCRMCoreProjectsProject';

export interface SDJCRMCoreProjectsProjectAddress {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  projectId?: number;
  countryId?: number;
  country?: SDJCRMCoreAreaCountry;
  /** @nullable */
  provinceId?: number | null;
  province?: SDJCRMCoreAreaProvince;
  /** @nullable */
  districtId?: number | null;
  district?: SDJCRMCoreAreaDistrict;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  addressVi?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  project?: SDJCRMCoreProjectsProject;
}
