/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreCompanyEntitiesCompany } from './sDJCRMCoreCompanyEntitiesCompany';
import type { SDJCRMCoreCompanyEntitiesOtherCategory } from './sDJCRMCoreCompanyEntitiesOtherCategory';

export interface SDJCRMCoreCompanyEntitiesCompanyTypeMap {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  companyId?: number;
  company?: SDJCRMCoreCompanyEntitiesCompany;
  companyTypeId?: number;
  companyType?: SDJCRMCoreCompanyEntitiesOtherCategory;
  isActive?: boolean;
}
