/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpApplicationServicesDtoComboboxItemDto } from './abpApplicationServicesDtoComboboxItemDto';
import type { SDJCRMApplicationLocalizationDtoApplicationLanguageEditDto } from './sDJCRMApplicationLocalizationDtoApplicationLanguageEditDto';

export interface SDJCRMApplicationLocalizationDtoGetLanguageForEditOutput {
  language?: SDJCRMApplicationLocalizationDtoApplicationLanguageEditDto;
  /** @nullable */
  languageNames?: AbpApplicationServicesDtoComboboxItemDto[] | null;
  /** @nullable */
  flags?: AbpApplicationServicesDtoComboboxItemDto[] | null;
}
