/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationInquiriesDtoInquiryReservationUnitPriorityDto {
  unitId?: number;
  /** @nullable */
  unitName?: string | null;
  number?: number;
}
