/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCompanyCompanyAddressCompanyAddressInputDto } from './sDJCRMApplicationCompanyCompanyAddressCompanyAddressInputDto';
import type { SDJCRMApplicationCompanyCompanyPhoneCompanyPhoneInputDto } from './sDJCRMApplicationCompanyCompanyPhoneCompanyPhoneInputDto';

export interface SDJCRMApplicationCompanyDtoCompanyInputDto {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  legalName?: string | null;
  /** @nullable */
  legalNameVi?: string | null;
  /** @nullable */
  businessName?: string | null;
  /** @nullable */
  vatcode?: string | null;
  /** @nullable */
  industryId?: number | null;
  /** @nullable */
  industryLevel2Id?: number | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  keyClientManagement?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  nationalityId?: number | null;
  /** @nullable */
  bankNumber?: string | null;
  /** @nullable */
  bankAccountName?: string | null;
  /** @nullable */
  bankBranch?: string | null;
  /** @nullable */
  swiftCode?: string | null;
  /** @nullable */
  licenseNumber?: string | null;
  /** @nullable */
  licenseNumberVi?: string | null;
  /** @nullable */
  licenseIssued?: string | null;
  /** @nullable */
  licenseIssuedVi?: string | null;
  /** @nullable */
  licenseIssuedDate?: string | null;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  positionVi?: string | null;
  /** @nullable */
  certificate?: string | null;
  /** @nullable */
  certificateVi?: string | null;
  /** @nullable */
  representative?: string | null;
  /** @nullable */
  representativeVi?: string | null;
  /** @nullable */
  companyAddress?: SDJCRMApplicationCompanyCompanyAddressCompanyAddressInputDto[] | null;
  /** @nullable */
  companyPhone?: SDJCRMApplicationCompanyCompanyPhoneCompanyPhoneInputDto[] | null;
  /** @nullable */
  typeIds?: number[] | null;
  /** @nullable */
  organizationUnitIds?: number[] | null;
  /** @nullable */
  userIds?: number[] | null;
}
