/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementPaymentScheduleDetailsInputDto } from './sDJCRMApplicationLADtoLeaseAgreementPaymentScheduleDetailsInputDto';

export interface SDJCRMApplicationLADtoLeaseAgreementPaymentScheduleInputDto {
  id?: number;
  leaseAgreementId?: number;
  /** @nullable */
  name?: string | null;
  amount?: number;
  startDate?: string;
  endDate?: string;
  dueDate?: string;
  statusId?: number;
  isActive?: boolean;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  leaseAgreementPaymentScheduleDetails?: SDJCRMApplicationLADtoLeaseAgreementPaymentScheduleDetailsInputDto[] | null;
}
