/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSettingDtoFeeTypeOutputDto } from './sDJCRMCoreSettingDtoFeeTypeOutputDto';

export interface SDJCRMApplicationLADtoLeaseAgreementPaymentScheduleDetailsOutputDto {
  id?: number;
  leaseAgreementPaymentScheduleId?: number;
  amountIncludeVAT?: number;
  vatAmount?: number;
  feeTypeId?: number;
  feeType?: SDJCRMCoreSettingDtoFeeTypeOutputDto;
  amount?: number;
}
