/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationDefectReportingsDtoDefectReportByResponseTimeline {
  totalSatisfied1St?: number;
  totalOverdue1St?: number;
  totalSatisfied1StPercentage?: number;
  totalOverdue1StPercentage?: number;
  totalSatisfied2Nd?: number;
  totalOverdue2Nd?: number;
  totalSatisfied2NdPercentage?: number;
  totalOverdue2NdPercentage?: number;
  totalSatisfied3Rd?: number;
  totalOverdue3Rd?: number;
  totalSatisfied3RdPercentage?: number;
  totalOverdue3RdPercentage?: number;
  totalSatisfiedNormal?: number;
  totalOverdueNormal?: number;
  totalSatisfiedNormalPercentage?: number;
  totalOverdueNormalPercentage?: number;
  totalSatisfiedUrgent?: number;
  totalOverdueUrgent?: number;
  totalSatisfiedUrgentPercentage?: number;
  totalOverdueUrgentPercentage?: number;
}
