/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationRemindersDtoReminderSettingOutputDto {
  id?: number;
  moduleId?: number;
  reminder?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  otherNote?: string | null;
  isActive?: boolean;
}
