/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationDefectDefectManagementDtoWorkScheduleWorkDetailOutputDto {
  id?: number;
  /** @nullable */
  task?: string | null;
  startDate?: string;
  endDate?: string;
}
