/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto';
import type { SDJCRMApplicationUnitDtoSimpleUnitOutputDto } from './sDJCRMApplicationUnitDtoSimpleUnitOutputDto';
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationUnitDtoUnitStatusManagementUnitStatusManagementOutputDto {
  id?: number;
  unitId?: number;
  unit?: SDJCRMApplicationUnitDtoSimpleUnitOutputDto;
  /** @nullable */
  leaseAgreementId?: number | null;
  leaseAgreement?: SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto;
  statusId?: number;
  status?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  startDate?: string;
  endDate?: string;
  isActive?: boolean;
}
