/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectManagementDtoWorkScheduleWorkDetailOutputDto } from './sDJCRMApplicationDefectDefectManagementDtoWorkScheduleWorkDetailOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationDefectDefectManagementDtoWorkScheduleOutputDto {
  id?: number;
  defectId?: number;
  isCompleted?: boolean;
  /** @nullable */
  standardizedEndDate?: string | null;
  /** @nullable */
  actualSubmissionDate?: string | null;
  /** @nullable */
  estimateEndDate?: string | null;
  /** @nullable */
  plannedStartDate?: string | null;
  /** @nullable */
  plannedEndDate?: string | null;
  /** @nullable */
  actualStartDate?: string | null;
  /** @nullable */
  actualEndDate?: string | null;
  /** @nullable */
  description?: string | null;
  uniqueId?: string;
  isDelay?: boolean;
  /** @nullable */
  delayDays?: number | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  /** @nullable */
  workScheduleWorkDetails?: SDJCRMApplicationDefectDefectManagementDtoWorkScheduleWorkDetailOutputDto[] | null;
}
