/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationRemindersDtoReminderOutputDto {
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  reminderInMinute?: number | null;
  beforeDays?: number;
  /** @nullable */
  period?: number | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  users?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto[] | null;
  /** @nullable */
  emails?: string[] | null;
}
