/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationRemindersDtoReminderInputDto } from './sDJCRMApplicationRemindersDtoReminderInputDto';

export interface SDJCRMApplicationAssetManagementDtoAssetUpdateInputDto {
  id?: number;
  /**
     * @minLength 0
     * @maxLength 50
     * @nullable
     */
  laReferenceNumber?: string | null;
  /**
     * @minLength 0
     * @maxLength 255
     * @nullable
     */
  assetName?: string | null;
  /** @nullable */
  providerId?: number | null;
  assetTypeLv1Id?: number;
  assetTypeLv2Id?: number;
  /**
     * @minLength 0
     * @maxLength 50
     * @nullable
     */
  assetCode?: string | null;
  purchasedDate?: string;
  value?: number;
  warrantDate?: string;
  /** @nullable */
  model?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  liquidationDate?: string | null;
  reminder?: SDJCRMApplicationRemindersDtoReminderInputDto;
  /** @nullable */
  assetTypeAttributeIds?: number[] | null;
}
