/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryProposalProjectOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryProposalProjectOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryProposalUnitOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryProposalUnitOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto } from './sDJCRMApplicationInquiriesDtoInquirySimpleOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationInquiriesDtoInquiryProposalOutputDto {
  id?: number;
  uniqueId?: string;
  inquiryId?: number;
  /** @nullable */
  proposalType?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  proposalDate?: string | null;
  /** @nullable */
  description?: string | null;
  templateId?: number;
  /** @nullable */
  contentBefore?: string | null;
  /** @nullable */
  contentAfter?: string | null;
  linkView?: number;
  /** @nullable */
  proposalUnit?: SDJCRMApplicationInquiriesDtoInquiryProposalUnitOutputDto[] | null;
  /** @nullable */
  proposalProject?: SDJCRMApplicationInquiriesDtoInquiryProposalProjectOutputDto[] | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  inquiry?: SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto;
}
