/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreProjectsProjectTypeMap } from './sDJCRMCoreProjectsProjectTypeMap';

export interface SDJCRMCoreProjectsPropertyType {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  target?: string | null;
  isActive?: boolean;
  /** @nullable */
  projectTypeMap?: SDJCRMCoreProjectsProjectTypeMap[] | null;
}
