/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedEnumsSendEmailConfigurationModuleEnum } from './sDJCRMCoreSharedEnumsSendEmailConfigurationModuleEnum';

export interface SDJCRMApplicationDefectDefectConfigurationDtoDefectEmailModuleOutputDto {
  id?: number;
  module?: SDJCRMCoreSharedEnumsSendEmailConfigurationModuleEnum;
  /** @nullable */
  defectUsersEmails?: string[] | null;
}
