/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionPhase } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionPhase';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionUser } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionUser';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionMaster {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement;
  dealerCommissionAmount?: number;
  dealerPercent?: number;
  departmentCommissionAmount?: number;
  departmentPercent?: number;
  isManual?: boolean;
  /** @nullable */
  leaseAgreementCommissionPhase?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionPhase[] | null;
  /** @nullable */
  leaseAgreementCommissionUser?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionUser[] | null;
}
