/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto } from './sDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';

export interface SDJCRMApplicationDefectReportingsDtoDefectPriorityReportDto {
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  /** @nullable */
  defectPriorities?: SDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto[] | null;
  totalObserving?: number;
  total?: number;
  percentage?: number;
  totalDeductObserving?: number;
  percentageDeductObserving?: number;
}
