/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationFloorDtoFloorInputDto {
  /** @nullable */
  id?: number | null;
  projectId?: number;
  /** @nullable */
  floorName?: string | null;
  /** @nullable */
  size?: number | null;
  /** @nullable */
  order?: number | null;
}
