/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationSettingVATDtoSettingVATInputDto {
  id?: number;
  feeTypeId?: number;
  vat?: number;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
}
