/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto {
  id?: number;
  contactId?: number;
  /** @nullable */
  contactName?: string | null;
  statusId?: number;
  status?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  /** @nullable */
  referenceNumber?: string | null;
  /** @nullable */
  extensionDate?: string | null;
  /** @nullable */
  terminationDate?: string | null;
  commencementDate?: string;
  expiryDate?: string;
  /** @nullable */
  moveInDate?: string | null;
  /** @nullable */
  moveOutDate?: string | null;
}
