/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto } from './sDJCRMApplicationInquiriesDtoInquirySimpleOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquirySiteVisitUnitOutputDto } from './sDJCRMApplicationInquiriesDtoInquirySiteVisitUnitOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationInquiriesDtoInquirySiteVisitOutputDto {
  id?: number;
  inquiryId?: number;
  /** @nullable */
  siteVisitTime?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  siteVisitUnit?: SDJCRMApplicationInquiriesDtoInquirySiteVisitUnitOutputDto[] | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  inquiry?: SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto;
}
