/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationSessionsDtoApplicationInfoDto } from './sDJCRMApplicationSessionsDtoApplicationInfoDto';
import type { SDJCRMApplicationSessionsDtoRequestStatistic4PartnerDto } from './sDJCRMApplicationSessionsDtoRequestStatistic4PartnerDto';
import type { SDJCRMApplicationSessionsDtoTenantLoginInfoDto } from './sDJCRMApplicationSessionsDtoTenantLoginInfoDto';
import type { SDJCRMApplicationSessionsDtoUserLoginInfoDto } from './sDJCRMApplicationSessionsDtoUserLoginInfoDto';

export interface SDJCRMApplicationSessionsDtoGetCurrentLoginInformationsOutput {
  application?: SDJCRMApplicationSessionsDtoApplicationInfoDto;
  user?: SDJCRMApplicationSessionsDtoUserLoginInfoDto;
  requestPercent?: SDJCRMApplicationSessionsDtoRequestStatistic4PartnerDto;
  tenant?: SDJCRMApplicationSessionsDtoTenantLoginInfoDto;
}
