/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailInputDto {
  /** @nullable */
  id?: number | null;
  methodAndQuotationId: number;
  serviceProviderId: number;
  repairingCost: number;
  warrantyPeriodId: number;
  isSelected?: boolean;
}
