/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationPlanMaintenanceDtoAssetMonthOutputDto } from './sDJCRMApplicationPlanMaintenanceDtoAssetMonthOutputDto';
import type { SDJCRMApplicationZoneDtoZoneOutputDto } from './sDJCRMApplicationZoneDtoZoneOutputDto';

export interface SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceMonthOutputDto {
  zone?: SDJCRMApplicationZoneDtoZoneOutputDto;
  /** @nullable */
  assetMonth?: SDJCRMApplicationPlanMaintenanceDtoAssetMonthOutputDto[] | null;
}
