/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedEnumsModule } from './sDJCRMCoreSharedEnumsModule';

export interface SDJCRMApplicationRemindersDtoReminderInputDto {
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  reminderInMinute?: number | null;
  beforeDays?: number;
  /** @nullable */
  period?: number | null;
  /** @nullable */
  isActive?: boolean | null;
  moduleId?: SDJCRMCoreSharedEnumsModule;
  /** @nullable */
  userIds?: number[] | null;
  /** @nullable */
  emails?: string[] | null;
}
