/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationWorkOrderWOCategoryDtoWOUpdateDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  code?: string | null;
  isActive?: boolean;
}
