/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationInquiriesDtoInquiryServiceTypeOutputDto {
  id?: number;
  serviceTypeId?: number;
  serviceType?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  inquiryId?: number;
}
