/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedProjectsUnitsStatusConstants } from './sDJCRMCoreSharedProjectsUnitsStatusConstants';

export interface SDJCRMApplicationLADtoAmendmentStatusInputDto {
  id?: number;
  stageId?: number;
  statusId?: number;
  unitStatusId?: SDJCRMCoreSharedProjectsUnitsStatusConstants;
}
