/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementPaymentScheduleDetailsOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementPaymentScheduleDetailsOutputDto';
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationLADtoLeaseAgreementPaymentScheduleOutputDto {
  id?: number;
  leaseAgreementId?: number;
  /** @nullable */
  name?: string | null;
  amount?: number;
  startDate?: string;
  endDate?: string;
  dueDate?: string;
  statusId?: number;
  status?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
  /** @nullable */
  leaseAgreementPaymentScheduleDetails?: SDJCRMApplicationLADtoLeaseAgreementPaymentScheduleDetailsOutputDto[] | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
