/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationContractContractDtoSimpleContractCategoryOutputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  parentId?: number | null;
  isActive?: boolean;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
}
