/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto } from './sDJCRMApplicationInquiriesDtoInquirySimpleOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryTaskUserOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryTaskUserOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationInquiriesDtoInquiryTaskOutputDto {
  id?: number;
  /** @nullable */
  inquiryId?: number | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  dueDate?: string | null;
  /** @nullable */
  remindDate?: string | null;
  /** @nullable */
  description?: string | null;
  inquiryTaskStatusId?: number;
  inquiryTaskStatus?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  /** @nullable */
  inquiryTaskUser?: SDJCRMApplicationInquiriesDtoInquiryTaskUserOutputDto[] | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  inquiry?: SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto;
}
