/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationConfigurationDtoTenantUserManagementSettingsEditDto {
  allowSelfRegistration?: boolean;
  isEmailRequired?: boolean;
  isEmailConfirmationRequiredForLogin?: boolean;
  useCaptchaOnRegistration?: boolean;
  smsVerificationEnabled?: boolean;
}
