/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationDefectDefectManagementDtoInspectionWorkDetailOutputDto {
  id?: number;
  /** @nullable */
  task?: string | null;
  implementDate?: string;
  completePercent?: number;
}
