/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryReservationUnitInputDto } from './sDJCRMApplicationInquiriesDtoInquiryReservationUnitInputDto';

export interface SDJCRMApplicationInquiriesDtoInquiryReservationInputDto {
  id?: number;
  inquiryId?: number;
  /** @nullable */
  reservationTime?: string | null;
  /** @nullable */
  fromDate?: string | null;
  /** @nullable */
  toDate?: string | null;
  /** @nullable */
  expiryDate?: string | null;
  /** @nullable */
  description?: string | null;
  projectId?: number;
  /** @nullable */
  reservationUnit?: SDJCRMApplicationInquiriesDtoInquiryReservationUnitInputDto[] | null;
}
