/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoSimpleInquiryReservationOutputDto } from './sDJCRMApplicationInquiriesDtoSimpleInquiryReservationOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto';
import type { SDJCRMApplicationUnitDtoUnitFacilityMapOutputDto } from './sDJCRMApplicationUnitDtoUnitFacilityMapOutputDto';
import type { SDJCRMApplicationUnitDtoUnitViewMapOutputDto } from './sDJCRMApplicationUnitDtoUnitViewMapOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationUnitDtoUnitResOutputDto {
  id?: number;
  uniqueId?: string;
  /** @nullable */
  projectId?: number | null;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  projectCode?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  floorId?: number | null;
  /** @nullable */
  floorName?: string | null;
  /** @nullable */
  unitName?: string | null;
  /** @nullable */
  actualSize?: number | null;
  statusId?: number;
  status?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  /** @nullable */
  description?: string | null;
  unitTypeId?: number;
  unitType?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  order?: number;
  isActive?: boolean;
  /** @nullable */
  askingRent?: number | null;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  balcony?: number | null;
  /** @nullable */
  helperRoom?: number | null;
  bedRoom?: number;
  bathRoom?: number;
  /** @nullable */
  livingRoom?: number | null;
  productTypeId?: number;
  productType?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  facingId?: number;
  facing?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  /** @nullable */
  saleAble?: number | null;
  /** @nullable */
  gross?: number | null;
  /** @nullable */
  motobikePark?: number | null;
  /** @nullable */
  isPet?: boolean | null;
  /** @nullable */
  carPark?: number | null;
  creatorUserId?: number;
  creationTime?: string;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  /** @nullable */
  unitFacilityMap?: SDJCRMApplicationUnitDtoUnitFacilityMapOutputDto[] | null;
  /** @nullable */
  unitViewMap?: SDJCRMApplicationUnitDtoUnitViewMapOutputDto[] | null;
  /** @nullable */
  leaseAgreement?: SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto[] | null;
  inquiryReservation?: SDJCRMApplicationInquiriesDtoSimpleInquiryReservationOutputDto;
  /** @nullable */
  linkPicture?: string | null;
  isReservation?: boolean;
  /** @nullable */
  totalAssets?: number | null;
  /** @nullable */
  totalAssetsDoNotUse?: number | null;
}
