/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCategoryLevelOutputDto } from './sDJCRMApplicationCategoryLevelOutputDto';
import type { SDJCRMApplicationCompanyCompanyContactCompanyContactOutputDto } from './sDJCRMApplicationCompanyCompanyContactCompanyContactOutputDto';
import type { SDJCRMApplicationCompanyDtoCompanySimpleOutputDto } from './sDJCRMApplicationCompanyDtoCompanySimpleOutputDto';
import type { SDJCRMApplicationContactContactAddressContactAddressOutputDto } from './sDJCRMApplicationContactContactAddressContactAddressOutputDto';
import type { SDJCRMApplicationContactContactEmailContactEmailOutputDto } from './sDJCRMApplicationContactContactEmailContactEmailOutputDto';
import type { SDJCRMApplicationContactContactOrganizationUnitContactOrganizationUnitOutputDto } from './sDJCRMApplicationContactContactOrganizationUnitContactOrganizationUnitOutputDto';
import type { SDJCRMApplicationContactContactPhoneContactPhoneOutputDto } from './sDJCRMApplicationContactContactPhoneContactPhoneOutputDto';
import type { SDJCRMApplicationContactContactTypeMapContactTypeMapOutputDto } from './sDJCRMApplicationContactContactTypeMapContactTypeMapOutputDto';
import type { SDJCRMApplicationContactContactUserContactUserOutputDto } from './sDJCRMApplicationContactContactUserContactUserOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationContactDtoContactOutputDto {
  /** @nullable */
  companyId?: number | null;
  company?: SDJCRMApplicationCompanyDtoCompanySimpleOutputDto;
  /** @nullable */
  typeId?: number | null;
  /** @nullable */
  leadSourceId?: number | null;
  leadSource?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  id?: number;
  uniqueId?: string;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  contactName?: string | null;
  /** @nullable */
  contactNameVi?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  titleVi?: string | null;
  isOwner?: boolean;
  /** @nullable */
  levelId?: number | null;
  level?: SDJCRMApplicationCategoryLevelOutputDto;
  isActive?: boolean;
  creationTime?: string;
  creatorUserId?: number;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  /** @nullable */
  nationalityId?: number | null;
  /** @nullable */
  nationalityName?: string | null;
  /** @nullable */
  numOfInquiry?: number | null;
  /** @nullable */
  numOfLA?: number | null;
  /** @nullable */
  contactAddress?: SDJCRMApplicationContactContactAddressContactAddressOutputDto[] | null;
  /** @nullable */
  contactUser?: SDJCRMApplicationContactContactUserContactUserOutputDto[] | null;
  /** @nullable */
  contactEmail?: SDJCRMApplicationContactContactEmailContactEmailOutputDto[] | null;
  /** @nullable */
  contactPhone?: SDJCRMApplicationContactContactPhoneContactPhoneOutputDto[] | null;
  /** @nullable */
  contactTypeMap?: SDJCRMApplicationContactContactTypeMapContactTypeMapOutputDto[] | null;
  /** @nullable */
  contactOrganizationUnit?: SDJCRMApplicationContactContactOrganizationUnitContactOrganizationUnitOutputDto[] | null;
  /** @nullable */
  companyContact?: SDJCRMApplicationCompanyCompanyContactCompanyContactOutputDto[] | null;
}
