/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuditLogDtoAuditLogItemOutput } from './sDJCRMCoreAuditLogDtoAuditLogItemOutput';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMCoreAuditLogDtoAuditLogOutput {
  id?: number;
  changeTime?: string;
  user?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  /** @nullable */
  items?: SDJCRMCoreAuditLogDtoAuditLogItemOutput[] | null;
}
