/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContractContractDtoContractCategoryOutputDto } from './sDJCRMApplicationContractContractDtoContractCategoryOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  parentId?: number | null;
  parent?: SDJCRMApplicationContractContractDtoContractCategoryOutputDto;
  /** @nullable */
  childs?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto[] | null;
  isActive?: boolean;
  level?: number;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
}
