/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreContactsEntitiesContact } from './sDJCRMCoreContactsEntitiesContact';

export interface SDJCRMCoreContactsEntitiesContactEmail {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  contactId?: number;
  contact?: SDJCRMCoreContactsEntitiesContact;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  isPrimary?: boolean | null;
  /** @nullable */
  isOptedOut?: boolean | null;
  /** @nullable */
  isCheckEmail?: boolean | null;
  /** @nullable */
  isInvalid?: boolean | null;
  isActive?: boolean;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  reason?: string | null;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  feeEmail?: string | null;
  /** @nullable */
  sendTransactional?: string | null;
}
