/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAuthorizationAccountsDtoResetPasswordOutput {
  canLogin?: boolean;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  emailAddress?: string | null;
}
