/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryReservationUnitStatusOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryReservationUnitStatusOutputDto';
import type { SDJCRMApplicationUnitDtoSimpleUnitOutputDto } from './sDJCRMApplicationUnitDtoSimpleUnitOutputDto';

export interface SDJCRMApplicationInquiriesDtoInquiryReservationUnitOutputDto {
  id?: number;
  reservationId?: number;
  unitStatusId?: number;
  unitId?: number;
  number?: number;
  creationTime?: string;
  unit?: SDJCRMApplicationUnitDtoSimpleUnitOutputDto;
  unitStatus?: SDJCRMApplicationInquiriesDtoInquiryReservationUnitStatusOutputDto;
}
