/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLADtoLeaseAgreementUnitInputDto {
  id?: number;
  leaseAgreementId?: number;
  projectId?: number;
  unitId?: number;
}
