/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMApplicationProjectProjectConstantProjectUserRole = typeof SDJCRMApplicationProjectProjectConstantProjectUserRole[keyof typeof SDJCRMApplicationProjectProjectConstantProjectUserRole];


export const SDJCRMApplicationProjectProjectConstantProjectUserRole = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
