/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLADtoLeaseAgreementStatusSettingOutputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  sortOrder?: number;
  /** @nullable */
  numDay?: number | null;
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  icon?: string | null;
  isActive?: boolean;
}
