/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCategoryCountryOutputDto } from './sDJCRMApplicationCategoryCountryOutputDto';
import type { SDJCRMApplicationLocationsDtoDistrictOutputDto } from './sDJCRMApplicationLocationsDtoDistrictOutputDto';
import type { SDJCRMApplicationLocationsDtoProvinceOutputDto } from './sDJCRMApplicationLocationsDtoProvinceOutputDto';

export interface SDJCRMApplicationContactContactAddressContactAddressOutputDto {
  id?: number;
  contactId?: number;
  countryId?: number;
  country?: SDJCRMApplicationCategoryCountryOutputDto;
  /** @nullable */
  provinceId?: number | null;
  province?: SDJCRMApplicationLocationsDtoProvinceOutputDto;
  /** @nullable */
  districtId?: number | null;
  district?: SDJCRMApplicationLocationsDtoDistrictOutputDto;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  addressVi?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  isActive?: boolean;
  isPrimary?: boolean;
}
