/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAuthorizationProfileDtoCurrentUserProfileEditDto {
  /**
     * @minLength 0
     * @maxLength 200
     * @nullable
     */
  displayName?: string | null;
  /**
     * @minLength 0
     * @maxLength 256
     */
  emailAddress: string;
  /**
     * @minLength 0
     * @maxLength 32
     * @nullable
     */
  phoneNumber?: string | null;
}
