/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpAuthorizationUsersUserClaim } from './abpAuthorizationUsersUserClaim';
import type { AbpAuthorizationUsersUserLogin } from './abpAuthorizationUsersUserLogin';
import type { AbpAuthorizationUsersUserPermissionSetting } from './abpAuthorizationUsersUserPermissionSetting';
import type { AbpAuthorizationUsersUserRole } from './abpAuthorizationUsersUserRole';
import type { AbpAuthorizationUsersUserToken } from './abpAuthorizationUsersUserToken';
import type { AbpConfigurationSetting } from './abpConfigurationSetting';
import type { SDJCRMCoreAuthorizationUsersUser as __SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';

export interface SDJCRMCoreAuthorizationUsersUser {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  /**
     * @minLength 0
     * @maxLength 64
     * @nullable
     */
  authenticationSource?: string | null;
  /**
     * @minLength 0
     * @maxLength 256
     */
  userName: string;
  /** @nullable */
  tenantId?: number | null;
  /**
     * @minLength 0
     * @maxLength 256
     */
  emailAddress: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  surname: string;
  /** @nullable */
  readonly fullName?: string | null;
  /**
     * @minLength 0
     * @maxLength 128
     */
  password: string;
  /**
     * @minLength 0
     * @maxLength 328
     * @nullable
     */
  emailConfirmationCode?: string | null;
  /**
     * @minLength 0
     * @maxLength 328
     * @nullable
     */
  passwordResetCode?: string | null;
  /** @nullable */
  lockoutEndDateUtc?: string | null;
  accessFailedCount?: number;
  isLockoutEnabled?: boolean;
  /**
     * @minLength 0
     * @maxLength 32
     * @nullable
     */
  phoneNumber?: string | null;
  isPhoneNumberConfirmed?: boolean;
  /**
     * @minLength 0
     * @maxLength 128
     * @nullable
     */
  securityStamp?: string | null;
  isTwoFactorEnabled?: boolean;
  /** @nullable */
  logins?: AbpAuthorizationUsersUserLogin[] | null;
  /** @nullable */
  roles?: AbpAuthorizationUsersUserRole[] | null;
  /** @nullable */
  claims?: AbpAuthorizationUsersUserClaim[] | null;
  /** @nullable */
  permissions?: AbpAuthorizationUsersUserPermissionSetting[] | null;
  /** @nullable */
  settings?: AbpConfigurationSetting[] | null;
  isEmailConfirmed?: boolean;
  isActive?: boolean;
  /**
     * @minLength 0
     * @maxLength 256
     */
  normalizedUserName: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  normalizedEmailAddress: string;
  /**
     * @minLength 0
     * @maxLength 128
     * @nullable
     */
  concurrencyStamp?: string | null;
  /** @nullable */
  tokens?: AbpAuthorizationUsersUserToken[] | null;
  deleterUser?: __SDJCRMCoreAuthorizationUsersUser;
  creatorUser?: __SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: __SDJCRMCoreAuthorizationUsersUser;
  /** @nullable */
  profilePictureId?: string | null;
  /** @nullable */
  signInToken?: string | null;
  /** @nullable */
  signInTokenExpireTimeUtc?: string | null;
  /** @nullable */
  birthDate?: string | null;
  /**
     * @minLength 0
     * @maxLength 256
     * @nullable
     */
  titleName?: string | null;
  /** @nullable */
  gender?: boolean | null;
  /**
     * @minLength 0
     * @maxLength 256
     */
  displayName: string;
  /**
     * @minLength 0
     * @maxLength 64
     * @nullable
     */
  passport?: string | null;
  /**
     * @minLength 0
     * @maxLength 64
     * @nullable
     */
  identityNumber?: string | null;
  /** @nullable */
  groupId?: number | null;
  status?: number;
  shouldChangePasswordOnNextLogin?: boolean;
}
