/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectManagementDtoInspectionWorkDetailOutputDto } from './sDJCRMApplicationDefectDefectManagementDtoInspectionWorkDetailOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';
import type { SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum } from './sDJCRMCoreSharedEnumsDefectConfigurationTypeEnum';

export interface SDJCRMApplicationDefectDefectManagementDtoInspectionOutputDto {
  id?: number;
  defectId?: number;
  isCompleted?: boolean;
  defectConfigurationType?: SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum;
  /** @nullable */
  standardizedEndDate?: string | null;
  /** @nullable */
  actualStartDate?: string | null;
  /** @nullable */
  estimateEndDate?: string | null;
  /** @nullable */
  description?: string | null;
  uniqueId?: string;
  isDelay?: boolean;
  /** @nullable */
  delayDays?: number | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  /** @nullable */
  inspectionWorkDetails?: SDJCRMApplicationDefectDefectManagementDtoInspectionWorkDetailOutputDto[] | null;
}
