/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLocalizationDtoClientLanguageTextListDtoData } from './sDJCRMApplicationLocalizationDtoClientLanguageTextListDtoData';

export interface SDJCRMApplicationLocalizationDtoClientLanguageTextListDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  visibleIcon?: string | null;
  /** @nullable */
  name?: string | null;
  isDefault?: boolean;
  /** @nullable */
  data?: SDJCRMApplicationLocalizationDtoClientLanguageTextListDtoData;
}
