/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationContractProviderContractProviderContractPaidOutputDto {
  id?: number;
  providerContractId?: number;
  order?: number;
  /** @nullable */
  description?: string | null;
  amount?: number;
  paymentDate?: string;
}
