/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLADtoLeaseAgreementBlockInputDto {
  id?: number;
  /** @nullable */
  statusId?: number | null;
  isBlock?: boolean;
}
