/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLocationsDtoDistrictOutputDto } from './sDJCRMApplicationLocationsDtoDistrictOutputDto';

export interface SDJCRMApplicationLocationsDtoProvinceOutputDto {
  id?: number;
  /** @nullable */
  provinceCode?: string | null;
  /** @nullable */
  provinceName?: string | null;
  /** @nullable */
  districts?: SDJCRMApplicationLocationsDtoDistrictOutputDto[] | null;
}
