/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLocationsDtoProvinceOutputDto } from './sDJCRMApplicationLocationsDtoProvinceOutputDto';

export interface SDJCRMApplicationCategoryCountryOutputDto {
  id?: number;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  phoneCode?: string | null;
  /** @nullable */
  countryName?: string | null;
  /** @nullable */
  nationalityName?: string | null;
  /** @nullable */
  continent?: string | null;
  /** @nullable */
  provinces?: SDJCRMApplicationLocationsDtoProvinceOutputDto[] | null;
}
