/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationConfigurationDtoGeneralSettingsEditDto {
  startDayOfWeek?: number;
  allowSendEmail?: boolean;
  allowSendSms?: boolean;
  zaloPayEnable?: boolean;
  vnPayEnable?: boolean;
  momoEnable?: boolean;
  /** @nullable */
  defaultCountry?: string | null;
}
