/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreContactsEntitiesLevel {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  levelName?: string | null;
  /** @nullable */
  levelDescription?: string | null;
  isActive?: boolean;
}
