/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAuthorizationAccountsDtoIsEmailAddressAvailableInput {
  /**
     * @minLength 0
     * @maxLength 256
     */
  emailAddress: string;
}
