/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLocalizationDtoLanguageTextListDto {
  /** @nullable */
  key?: string | null;
  /** @nullable */
  baseValue?: string | null;
  /** @nullable */
  targetValue?: string | null;
}
