/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationProviderDtoSimpleProviderOutputDto {
  id?: number;
  /** @nullable */
  taxCode?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  legalName?: string | null;
}
