/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationProviderDtoProviderCreateDto {
  /** @nullable */
  typeId?: number | null;
  /** @minLength 1 */
  taxCode: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  primaryPhone: string;
  /** @minLength 1 */
  primaryEmail: string;
  /** @nullable */
  primaryAddress?: string | null;
  /** @nullable */
  secondaryPhone?: string | null;
  /** @nullable */
  secondaryEmail?: string | null;
  /** @nullable */
  secondaryAddress?: string | null;
  /** @nullable */
  description?: string | null;
}
