/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUnitHandoverDtoAssetCreateOrUpdateInputDto } from './sDJCRMApplicationUnitHandoverDtoAssetCreateOrUpdateInputDto';

export interface SDJCRMApplicationUnitHandoverDtoUnitHandoverUpdateInputDto {
  id?: number;
  /** @nullable */
  handoverName?: string | null;
  unitId?: number;
  leaseAgreementId?: number;
  /** @nullable */
  userTenantId?: number | null;
  /** @nullable */
  ciDate?: string | null;
  /** @nullable */
  coDate?: string | null;
  statusId?: number;
  /** @nullable */
  handoverDate?: string | null;
  /** @nullable */
  storageFee?: number | null;
  /** @nullable */
  asset?: SDJCRMApplicationUnitHandoverDtoAssetCreateOrUpdateInputDto[] | null;
}
