/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreProjectsProject } from './sDJCRMCoreProjectsProject';

export interface SDJCRMCoreProjectsFloor {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  projectId?: number;
  project?: SDJCRMCoreProjectsProject;
  /** @nullable */
  floorName?: string | null;
  /** @nullable */
  size?: number | null;
  /** @nullable */
  order?: number | null;
  isActive?: boolean;
  tenantId?: number;
}
