/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationWorkOrderWorkOrderDtoPageFilterWorkOrderExportDto {
  /** @nullable */
  keyword?: string | null;
  /** @nullable */
  projectIds?: number[] | null;
  /** @nullable */
  unitIds?: number[] | null;
  /** @nullable */
  categoryIds?: number[] | null;
  /** @nullable */
  statusIds?: number[] | null;
  /** @nullable */
  zoneIds?: number[] | null;
  /** @nullable */
  assetTypeLv1Ids?: number[] | null;
  /** @nullable */
  assetTypeLv2Ids?: number[] | null;
  /** @nullable */
  fromDate?: string | null;
  /** @nullable */
  toDate?: string | null;
  /** @nullable */
  warrantyDate?: string | null;
  /** @nullable */
  assetId?: number | null;
  /** @nullable */
  providerId?: number | null;
}
