/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositRefundTypeMap } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositRefundTypeMap';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositRefund {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement;
  /** @nullable */
  voucherNo?: string | null;
  /** @nullable */
  remark?: string | null;
  refundAmount?: number;
  /** @nullable */
  voucherDate?: string | null;
  isActive?: boolean;
  /** @nullable */
  leaseAgreementDepositRefundTypeMap?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositRefundTypeMap[] | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
