/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositCollect {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement;
  leaseAgreementDepositId?: number;
  /** @nullable */
  receiptNo?: string | null;
  /** @nullable */
  receiptDate?: string | null;
  /** @nullable */
  paymentDate?: string | null;
  /** @nullable */
  remark?: string | null;
  receiptAmount?: number;
  isActive?: boolean;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
