/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationLADtoDepositLeaseAgreementDepositOutputDto {
  id?: number;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto;
  /** @nullable */
  description?: string | null;
  vatPercent?: number;
  vatAmount?: number;
  depositAmount?: number;
  depositDate?: string;
  collectAmount?: number;
  isActive?: boolean;
  creatorUserId?: number;
  creationTime?: string;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
}
