/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLADtoLeaseAgreementPaymentScheduleDetailsInputDto {
  id?: number;
  leaseAgreementPaymentScheduleId?: number;
  amountIncludeVAT?: number;
  vatAmount?: number;
  feeTypeId?: number;
  amount?: number;
}
