/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoAssetDetailOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetDetailOutputDto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';
import type { SDJCRMApplicationProviderDtoSimpleProviderOutputDto } from './sDJCRMApplicationProviderDtoSimpleProviderOutputDto';
import type { SDJCRMApplicationUnitDtoSimpleUnitOutputDto } from './sDJCRMApplicationUnitDtoSimpleUnitOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';
import type { SDJCRMApplicationWorkOrderWOCategoryDtoWOOutputDto } from './sDJCRMApplicationWorkOrderWOCategoryDtoWOOutputDto';
import type { SDJCRMApplicationZoneDtoZoneOutputDto } from './sDJCRMApplicationZoneDtoZoneOutputDto';
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationWorkOrderWorkOrderDtoWorkOrderOutputDto {
  id?: number;
  woCategory?: SDJCRMApplicationWorkOrderWOCategoryDtoWOOutputDto;
  uniqueId?: string;
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  unit?: SDJCRMApplicationUnitDtoSimpleUnitOutputDto;
  zone?: SDJCRMApplicationZoneDtoZoneOutputDto;
  asset?: SDJCRMApplicationAssetManagementDtoAssetDetailOutputDto;
  /** @nullable */
  description?: string | null;
  status?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  endDate?: string;
  pic?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  /** @nullable */
  repairingCost?: number | null;
  provider?: SDJCRMApplicationProviderDtoSimpleProviderOutputDto;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
}
