/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationInquiriesDtoInquiryReservationUnitStatusOutputDto {
  /** @nullable */
  statusCode?: string | null;
  /** @nullable */
  statusName?: string | null;
  /** @nullable */
  description?: string | null;
}
