/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAuthorizationAccountsDtoResetPasswordInput {
  /**
     * @minLength 1
     * @maxLength 256
     */
  emailAddress: string;
  /** @minLength 1 */
  resetCode: string;
  /** @minLength 1 */
  password: string;
  /** @nullable */
  returnUrl?: string | null;
  /** @nullable */
  singleSignIn?: string | null;
}
