/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreProjectsProject } from './sDJCRMCoreProjectsProject';
import type { SDJCRMCoreProjectsPropertyType } from './sDJCRMCoreProjectsPropertyType';
import type { SDJCRMCoreProjectsUnitType } from './sDJCRMCoreProjectsUnitType';

export interface SDJCRMCoreProjectsProjectTypeMap {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  projectId?: number;
  propertyTypeId?: number;
  unitTypeId?: number;
  unitType?: SDJCRMCoreProjectsUnitType;
  propertyType?: SDJCRMCoreProjectsPropertyType;
  project?: SDJCRMCoreProjectsProject;
}
