/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationConversationsDtoConversationOutputDto } from './sDJCRMApplicationConversationsDtoConversationOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';
import type { SDJCRMCoreSharedDocumentsDtoDocumentOutput } from './sDJCRMCoreSharedDocumentsDtoDocumentOutput';

export interface SDJCRMApplicationConversationsDtoChatMessageOutputDto {
  id?: number;
  uniqueId?: string;
  /** @nullable */
  content?: string | null;
  isActive?: boolean;
  isPrivate?: boolean;
  creationTime?: string;
  user?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  conversation?: SDJCRMApplicationConversationsDtoConversationOutputDto;
  /** @nullable */
  files?: SDJCRMCoreSharedDocumentsDtoDocumentOutput[] | null;
}
