/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUnitDtoUnitAddressInputDto } from './sDJCRMApplicationUnitDtoUnitAddressInputDto';

export interface SDJCRMApplicationUnitDtoUnitResInputDto {
  id?: number;
  /** @nullable */
  projectId?: number | null;
  /** @nullable */
  floorId?: number | null;
  /** @nullable */
  unitName?: string | null;
  /** @nullable */
  actualSize?: number | null;
  statusId?: number;
  /** @nullable */
  description?: string | null;
  unitTypeId?: number;
  order?: number;
  /** @nullable */
  askingRent?: number | null;
  productTypeId?: number;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  motobikePark?: number | null;
  /** @nullable */
  carPark?: number | null;
  /** @nullable */
  balcony?: number | null;
  /** @nullable */
  helperRoom?: number | null;
  bedRoom?: number;
  bathRoom?: number;
  /** @nullable */
  livingRoom?: number | null;
  /** @nullable */
  facingId?: number | null;
  /** @nullable */
  saleAble?: number | null;
  /** @nullable */
  gross?: number | null;
  /** @nullable */
  isPet?: boolean | null;
  /** @nullable */
  unitFacilityIds?: number[] | null;
  /** @nullable */
  viewIds?: number[] | null;
  /** @nullable */
  unitAddress?: SDJCRMApplicationUnitDtoUnitAddressInputDto[] | null;
}
