/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto';
import type { SDJCRMApplicationPlanMaintenanceDtoData } from './sDJCRMApplicationPlanMaintenanceDtoData';

export interface SDJCRMApplicationPlanMaintenanceDtoAssetMonthOutputV2Dto {
  assetTypeLv1?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto;
  /** @nullable */
  data?: SDJCRMApplicationPlanMaintenanceDtoData[] | null;
}
