/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';
import type { SDJCRMApplicationUnitDtoSimpleUnitOutputDto } from './sDJCRMApplicationUnitDtoSimpleUnitOutputDto';
import type { SDJCRMApplicationUnitHandoverDtoAssetUnitHandoverOutputDto } from './sDJCRMApplicationUnitHandoverDtoAssetUnitHandoverOutputDto';
import type { SDJCRMApplicationUnitHandoverDtoHandoverStatusOutputDto } from './sDJCRMApplicationUnitHandoverDtoHandoverStatusOutputDto';
import type { SDJCRMApplicationUserTenantDtoSimpleUserTenantOutputDto } from './sDJCRMApplicationUserTenantDtoSimpleUserTenantOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationUnitHandoverDtoUnitHandoverDetailOutputDto {
  id?: number;
  uniqueId?: string;
  /** @nullable */
  projectCode?: string | null;
  /** @nullable */
  unitName?: string | null;
  /** @nullable */
  handoverName?: string | null;
  /** @nullable */
  handoverDate?: string | null;
  /** @nullable */
  ciDate?: string | null;
  /** @nullable */
  coDate?: string | null;
  leaseAgreementId?: number;
  /** @nullable */
  storageFee?: number | null;
  status?: SDJCRMApplicationUnitHandoverDtoHandoverStatusOutputDto;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  userTenant?: SDJCRMApplicationUserTenantDtoSimpleUserTenantOutputDto;
  unit?: SDJCRMApplicationUnitDtoSimpleUnitOutputDto;
  leaseAgreement?: SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto;
  /** @nullable */
  statusId?: number | null;
  /** @nullable */
  assets?: SDJCRMApplicationUnitHandoverDtoAssetUnitHandoverOutputDto[] | null;
}
