/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailOutputDto } from './sDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';
import type { SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum } from './sDJCRMCoreSharedEnumsDefectConfigurationTypeEnum';

export interface SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationOutputDto {
  id?: number;
  defectId?: number;
  isCompleted?: boolean;
  defectConfigurationType?: SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum;
  /** @nullable */
  standardizedEndDate?: string | null;
  /** @nullable */
  actualStartDate?: string | null;
  /** @nullable */
  estimateEndDate?: string | null;
  /** @nullable */
  receivedDate?: string | null;
  /** @nullable */
  approvalDate?: string | null;
  /** @nullable */
  description?: string | null;
  uniqueId?: string;
  isReturned?: boolean;
  isDelay?: boolean;
  /** @nullable */
  delayDays?: number | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  /** @nullable */
  methodAndQuotationWorkDetails?: SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailOutputDto[] | null;
}
