/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationDefectDefectManagementDtoDefectStatusOutputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  backgroundColor?: string | null;
  /** @nullable */
  order?: number | null;
  isNew?: boolean;
  isRepeated?: boolean;
  /** @nullable */
  parentIds?: number[] | null;
}
