/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoSimpleAssetOutputDto } from './sDJCRMApplicationAssetManagementDtoSimpleAssetOutputDto';
import type { SDJCRMApplicationPlanMaintenanceDtoData } from './sDJCRMApplicationPlanMaintenanceDtoData';

export interface SDJCRMApplicationPlanMaintenanceDtoAssetMonthOutputDto {
  asset?: SDJCRMApplicationAssetManagementDtoSimpleAssetOutputDto;
  /** @nullable */
  data?: SDJCRMApplicationPlanMaintenanceDtoData[] | null;
}
