/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStartEndDateDto {
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  /**
     * @minLength 0
     * @maxLength 512
     * @nullable
     */
  description?: string | null;
}
