/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationPlanMaintenanceDtoPlanTaskStatusOutputDto } from './sDJCRMApplicationPlanMaintenanceDtoPlanTaskStatusOutputDto';

export interface SDJCRMApplicationPlanMaintenanceDtoPlanTaskOutputDto {
  id?: number;
  planMaintenanceId?: number;
  /** @nullable */
  task?: string | null;
  percentageCompletion?: number;
  status?: SDJCRMApplicationPlanMaintenanceDtoPlanTaskStatusOutputDto;
  statusId?: number;
}
