/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreLeaseAgreementsEntitiesAmendmentType } from './sDJCRMCoreLeaseAgreementsEntitiesAmendmentType';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementAmendmentTypeMap {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementId?: number;
  amendmentTypeId?: number;
  amendmentType?: SDJCRMCoreLeaseAgreementsEntitiesAmendmentType;
}
