/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreSharedEnumsModule = typeof SDJCRMCoreSharedEnumsModule[keyof typeof SDJCRMCoreSharedEnumsModule];


export const SDJCRMCoreSharedEnumsModule = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_7: 7,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_17: 17,
  NUMBER_18: 18,
  NUMBER_19: 19,
  NUMBER_20: 20,
  NUMBER_38: 38,
  NUMBER_43: 43,
  NUMBER_44: 44,
  NUMBER_100: 100,
  NUMBER_101: 101,
  NUMBER_102: 102,
  NUMBER_103: 103,
  NUMBER_104: 104,
  NUMBER_105: 105,
  NUMBER_106: 106,
  NUMBER_107: 107,
  NUMBER_109: 109,
  NUMBER_110: 110,
  NUMBER_111: 111,
  NUMBER_112: 112,
  NUMBER_113: 113,
  NUMBER_114: 114,
} as const;
