/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationCommmentCommentSendEmailOutputDto {
  id?: number;
  commentId?: number;
  userId?: number;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  emailAddress?: string | null;
}
