/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreSharedEnumsSendEmailConfigurationModuleEnum = typeof SDJCRMCoreSharedEnumsSendEmailConfigurationModuleEnum[keyof typeof SDJCRMCoreSharedEnumsSendEmailConfigurationModuleEnum];


export const SDJCRMCoreSharedEnumsSendEmailConfigurationModuleEnum = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
