/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationContactContactTypeMapContactTypeMapOutputDto {
  id?: number;
  /** @nullable */
  contactId?: number | null;
  /** @nullable */
  contactName?: string | null;
  contactTypeId?: number;
  /** @nullable */
  contactTypeName?: string | null;
  /** @nullable */
  isActive?: boolean | null;
}
