/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAuthorizationAccountsDtoMobileResetPasswordInput {
  /** @nullable */
  idToken?: string | null;
  /**
     * @minLength 0
     * @maxLength 256
     */
  userNameOrEmailAddress: string;
  /** @minLength 1 */
  password: string;
}
