/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUsersCustomersDtoCustomerDepositInputDto {
  id?: number;
  cashChanelId?: number;
  cashReceiptDate?: string;
  totalAmount?: number;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
}
