/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUserTenantDtoUserTenantInputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  passport?: string | null;
  /** @nullable */
  emailAddress?: string | null;
  /** @nullable */
  nationalityId?: number | null;
  /** @nullable */
  leaseAgreementId?: number | null;
}
