/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto {
  id?: number;
  /** @nullable */
  surName?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  emailAddress?: string | null;
  /** @nullable */
  displayName?: string | null;
}
