/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUsersUserBaseDtoUserDto {
  id?: number;
  /**
     * @minLength 0
     * @maxLength 256
     */
  userName: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  surname: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  displayName: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  emailAddress: string;
  isActive?: boolean;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  lastLoginTime?: string | null;
  creationTime?: string;
  /** @nullable */
  roleNames?: string[] | null;
}
