/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationProjectProjectTransportationMapsProjectTransportationMapOutputDto {
  id?: number;
  transportationId?: number;
  projectId?: number;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
}
