/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionDetailsInputDto {
  id?: number;
  leaseAgreementCommissionPhaseId?: number;
  userId?: number;
  commissionAmount?: number;
  percent?: number;
}
