/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationDefectReportingsDtoDefectReportByStatusDto {
  totalCompleted?: number;
  totalInProgress?: number;
  totalObserving?: number;
  totalOutstanding?: number;
  totalClosedNotNeedToRepair?: number;
  totalPending?: number;
  totalDefects?: number;
}
