/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCommmentCommentSendEmailOutputDto } from './sDJCRMApplicationCommmentCommentSendEmailOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';

export interface SDJCRMApplicationCommmentCommentOutputDto {
  id?: number;
  moduleId?: number;
  referenceId?: number;
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  parentBusinessName?: string | null;
  /** @nullable */
  parentLegalName?: string | null;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
  creatorUserId?: number;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  childCount?: number;
  /** @nullable */
  lastModifierUserId?: number | null;
  /** @nullable */
  isSend?: boolean | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  commentSendEmail?: SDJCRMApplicationCommmentCommentSendEmailOutputDto[] | null;
}
