/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum = typeof SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum[keyof typeof SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum];


export const SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
