/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContactDtoContactInputDto } from './sDJCRMApplicationContactDtoContactInputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryAddressInputDto } from './sDJCRMApplicationInquiriesDtoInquiryAddressInputDto';

export interface SDJCRMApplicationInquiriesDtoInquiryInputDto {
  id?: number;
  /** @nullable */
  clientId?: number | null;
  contactId?: number;
  contact?: SDJCRMApplicationContactDtoContactInputDto;
  /** @nullable */
  companyId?: number | null;
  /** @minLength 1 */
  inquiryName: string;
  sourceId?: number;
  statusId?: number;
  statusDetailId?: number;
  /** @nullable */
  occupierName?: string | null;
  /** @nullable */
  occupierId?: number | null;
  /** @nullable */
  moveInDate?: string | null;
  leaseTerm?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  fromSize?: number | null;
  /** @nullable */
  toSize?: number | null;
  /** @nullable */
  fromPrice?: number | null;
  /** @nullable */
  toPrice?: number | null;
  /** @nullable */
  livingRoom?: number | null;
  /** @nullable */
  bedRoom?: number | null;
  /** @nullable */
  helperRoom?: number | null;
  /** @nullable */
  bathRoom?: number | null;
  /** @nullable */
  balcony?: number | null;
  /** @nullable */
  motobikePark?: number | null;
  /** @nullable */
  carPark?: number | null;
  /** @nullable */
  inquiryAddress?: SDJCRMApplicationInquiriesDtoInquiryAddressInputDto[] | null;
  /** @nullable */
  viewIds?: number[] | null;
  /** @nullable */
  unitFacilityIds?: number[] | null;
  /** @nullable */
  unitTypeIds?: number[] | null;
  /** @nullable */
  serviceTypeIds?: number[] | null;
  /** @nullable */
  inquirySourceIds?: number[] | null;
  /** @nullable */
  unitIds?: number[] | null;
  /** @nullable */
  facingIds?: number[] | null;
  /** @nullable */
  projectIds?: number[] | null;
  /** @nullable */
  userIds?: number[] | null;
  /** @nullable */
  propertyTypeIds?: number[] | null;
  /** @nullable */
  organizationUnitIds?: number[] | null;
}
