/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAreaCountry } from './sDJCRMCoreAreaCountry';
import type { SDJCRMCoreCompanyEntitiesOtherCategory } from './sDJCRMCoreCompanyEntitiesOtherCategory';

export interface SDJCRMCoreCompanyEntitiesCompanyPhone {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  companyId?: number;
  /** @nullable */
  phoneTypeId?: number | null;
  phoneType?: SDJCRMCoreCompanyEntitiesOtherCategory;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  isPrimary?: boolean | null;
  /** @nullable */
  countryId?: number | null;
  country?: SDJCRMCoreAreaCountry;
  isActive?: boolean;
}
