/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum = typeof SDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum[keyof typeof SDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum];


export const SDJCRMCoreSharedNotificationsNotificationConstantsNotificationTypeEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
