/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUnitDtoUnitAddressInputDto {
  id?: number;
  unitId?: number;
  countryId?: number;
  /** @nullable */
  provinceId?: number | null;
  /** @nullable */
  districtId?: number | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  isActive?: boolean;
}
