/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAuthorizationAccountsDtoTenantAvailabilityState } from './sDJCRMApplicationAuthorizationAccountsDtoTenantAvailabilityState';

export interface SDJCRMApplicationAuthorizationAccountsDtoIsTenantAvailableOutput {
  state?: SDJCRMApplicationAuthorizationAccountsDtoTenantAvailabilityState;
  /** @nullable */
  tenantId?: number | null;
}
