/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationProjectProjectConstantProjectUserRole } from './sDJCRMApplicationProjectProjectConstantProjectUserRole';

export interface SDJCRMApplicationInquiriesDtoProjectUserInputDto {
  id?: number;
  projectId?: number;
  userId?: number;
  typeId?: SDJCRMApplicationProjectProjectConstantProjectUserRole;
  isActive?: boolean;
}
