/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreSharedOrganizationUnitDtoFindOrganizationUnitUsersInput {
  /**
     * @minimum 1
     * @maximum 1000
     */
  maxResultCount?: number;
  /**
     * @minimum 0
     * @maximum 2147483647
     */
  skipCount?: number;
  /** @nullable */
  filter?: string | null;
  organizationUnitId?: number;
}
