/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationConfigurationDtoTwoFactorLoginSettingsEditDto } from './sDJCRMApplicationConfigurationDtoTwoFactorLoginSettingsEditDto';
import type { SDJCRMApplicationConfigurationDtoUserLockOutSettingsEditDto } from './sDJCRMApplicationConfigurationDtoUserLockOutSettingsEditDto';
import type { SDJCRMCoreSharedSecurityPasswordComplexitySetting } from './sDJCRMCoreSharedSecurityPasswordComplexitySetting';

export interface SDJCRMApplicationConfigurationDtoSecuritySettingsEditDto {
  allowOneConcurrentLoginPerUser?: boolean;
  useDefaultPasswordComplexitySettings?: boolean;
  passwordComplexity?: SDJCRMCoreSharedSecurityPasswordComplexitySetting;
  defaultPasswordComplexity?: SDJCRMCoreSharedSecurityPasswordComplexitySetting;
  userLockOut?: SDJCRMApplicationConfigurationDtoUserLockOutSettingsEditDto;
  twoFactorLogin?: SDJCRMApplicationConfigurationDtoTwoFactorLoginSettingsEditDto;
}
