/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCompanyDtoCompanySimpleOutputDto } from './sDJCRMApplicationCompanyDtoCompanySimpleOutputDto';
import type { SDJCRMApplicationContactDtoContactSimpleOutputDto } from './sDJCRMApplicationContactDtoContactSimpleOutputDto';
import type { SDJCRMApplicationProjectProjectAddressProjectAddressOutputDto } from './sDJCRMApplicationProjectProjectAddressProjectAddressOutputDto';
import type { SDJCRMApplicationProjectProjectFacilityMapsProjectFacilityMapOutputDto } from './sDJCRMApplicationProjectProjectFacilityMapsProjectFacilityMapOutputDto';
import type { SDJCRMApplicationProjectProjectGradeMapsProjectGradeMapOutputDto } from './sDJCRMApplicationProjectProjectGradeMapsProjectGradeMapOutputDto';
import type { SDJCRMApplicationProjectProjectTransportationMapsProjectTransportationMapOutputDto } from './sDJCRMApplicationProjectProjectTransportationMapsProjectTransportationMapOutputDto';
import type { SDJCRMApplicationProjectProjectTypeMapsProjectTypeMapOutputDto } from './sDJCRMApplicationProjectProjectTypeMapsProjectTypeMapOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';
import type { SDJCRMCoreSharedDocumentsDtoDocumentOutput } from './sDJCRMCoreSharedDocumentsDtoDocumentOutput';

export interface SDJCRMApplicationProjectDtoProjectOutputDto {
  id?: number;
  sortNumber?: number;
  uniqueId?: string;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  propertyManagementName?: string | null;
  /** @nullable */
  landlordName?: string | null;
  /** @nullable */
  link?: string | null;
  /** @nullable */
  yearRenovated?: string | null;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  projectCode?: string | null;
  /** @nullable */
  budgetCode?: string | null;
  /** @nullable */
  bankInfo?: string | null;
  /** @nullable */
  totalSize?: number | null;
  numberOfFloors?: number;
  numberOfUnits?: number;
  leased?: number;
  /** @nullable */
  occPercent?: number | null;
  /** @nullable */
  outOfMarket?: boolean | null;
  /** @nullable */
  outOfDate?: string | null;
  /** @nullable */
  launchingTime?: string | null;
  /** @nullable */
  builtDate?: string | null;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
  /** @nullable */
  landlordId?: number | null;
  landlord?: SDJCRMApplicationCompanyDtoCompanySimpleOutputDto;
  /** @nullable */
  propertyManagementId?: number | null;
  propertyManagement?: SDJCRMApplicationCompanyDtoCompanySimpleOutputDto;
  /** @nullable */
  projectManagerName?: string | null;
  /** @nullable */
  ceilingHeight?: number | null;
  /** @nullable */
  backupPower?: string | null;
  /** @nullable */
  airConditioning?: string | null;
  /** @nullable */
  electricityCost?: number | null;
  /** @nullable */
  waterCost?: number | null;
  /** @nullable */
  motorbikeCost?: number | null;
  /** @nullable */
  petFees?: number | null;
  /** @nullable */
  dedicatedCarCost?: number | null;
  /** @nullable */
  managementFee?: number | null;
  /** @nullable */
  askingRent?: number | null;
  /** @nullable */
  landArea?: number | null;
  /** @nullable */
  askingPrice?: number | null;
  /** @nullable */
  contactId?: number | null;
  /** @nullable */
  lessorAddress?: string | null;
  /** @nullable */
  lessorAddressVi?: string | null;
  /** @nullable */
  representativeOf?: string | null;
  /** @nullable */
  representativeOfVi?: string | null;
  /** @nullable */
  lessorPosition?: string | null;
  /** @nullable */
  lessorPositionVi?: string | null;
  /** @nullable */
  lessorCertificateName?: string | null;
  /** @nullable */
  lessorCertificateNameVi?: string | null;
  /** @nullable */
  lessorCertificateNumber?: string | null;
  /** @nullable */
  lessorCertificateNumberVi?: string | null;
  /** @nullable */
  lessorCertificateIssuedDate?: string | null;
  /** @nullable */
  lessorCertificateIssuedBy?: string | null;
  /** @nullable */
  lessorCertificateIssuedByVi?: string | null;
  /** @nullable */
  registerAddress?: string | null;
  /** @nullable */
  registerAddressVi?: string | null;
  /** @nullable */
  representativeBy?: string | null;
  /** @nullable */
  representativeByVi?: string | null;
  /** @nullable */
  representativePosition?: string | null;
  /** @nullable */
  representativePositionVi?: string | null;
  /** @nullable */
  representativeCertificateNumber?: string | null;
  /** @nullable */
  representativeCertificateNumberVi?: string | null;
  /** @nullable */
  representativeExecuteBy?: string | null;
  /** @nullable */
  representativeExecuteByVi?: string | null;
  /** @nullable */
  representativeCertificateEffectiveDate?: string | null;
  /** @nullable */
  bankAccount?: string | null;
  /** @nullable */
  bankName?: string | null;
  /** @nullable */
  bankNameVi?: string | null;
  /** @nullable */
  bankAddress?: string | null;
  /** @nullable */
  bankAddressVi?: string | null;
  /** @nullable */
  optionalBankAccount?: string | null;
  /** @nullable */
  optionalBankName?: string | null;
  /** @nullable */
  optionalBankNameVi?: string | null;
  /** @nullable */
  optionalBankAddress?: string | null;
  /** @nullable */
  optionalBankAddressVi?: string | null;
  /** @nullable */
  managingAgentCompany?: string | null;
  /** @nullable */
  managingAgentCompanyVi?: string | null;
  /** @nullable */
  holderOf?: string | null;
  /** @nullable */
  holderOfVi?: string | null;
  /** @nullable */
  managingAgentCertificateNumber?: string | null;
  /** @nullable */
  managingAgentCertificateNumberVi?: string | null;
  /** @nullable */
  managingAgentCertificateIssuedDate?: string | null;
  /** @nullable */
  managingAgentCertificateIssuedBy?: string | null;
  /** @nullable */
  managingAgentCertificateIssuedByVi?: string | null;
  contact?: SDJCRMApplicationContactDtoContactSimpleOutputDto;
  /** @nullable */
  authorizationNumber?: string | null;
  /** @nullable */
  effectiveDate?: string | null;
  /** @nullable */
  persionSignLA?: string | null;
  /** @nullable */
  projectAddress?: SDJCRMApplicationProjectProjectAddressProjectAddressOutputDto[] | null;
  /** @nullable */
  projectFacilityMap?: SDJCRMApplicationProjectProjectFacilityMapsProjectFacilityMapOutputDto[] | null;
  /** @nullable */
  projectTransportationMap?: SDJCRMApplicationProjectProjectTransportationMapsProjectTransportationMapOutputDto[] | null;
  /** @nullable */
  projectTypeMap?: SDJCRMApplicationProjectProjectTypeMapsProjectTypeMapOutputDto[] | null;
  /** @nullable */
  projectGradeMap?: SDJCRMApplicationProjectProjectGradeMapsProjectGradeMapOutputDto[] | null;
  /** @nullable */
  price?: number | null;
  creatorUserId?: number;
  creationTime?: string;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  file?: SDJCRMCoreSharedDocumentsDtoDocumentOutput;
}
