/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositRefundTypeMap } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositRefundTypeMap';

export interface SDJCRMApplicationLADtoDepositLeaseAgreementDepositRefundOutputDto {
  id?: number;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto;
  /** @nullable */
  voucherNo?: string | null;
  /** @nullable */
  remark?: string | null;
  refundAmount?: number;
  /** @nullable */
  voucherDate?: string | null;
  /** @nullable */
  leaseAgreementDepositRefundTypeMap?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDepositRefundTypeMap[] | null;
  creatorUserId?: number;
  creationTime?: string;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  isActive?: boolean;
}
