/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreCompanyEntitiesCompany } from './sDJCRMCoreCompanyEntitiesCompany';
import type { SDJCRMCoreContactsEntitiesContact } from './sDJCRMCoreContactsEntitiesContact';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement as __SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementAmendmentTypeMap } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementAmendmentTypeMap';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDetails } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDetails';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDiscount } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDiscount';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementIncentive } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementIncentive';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentSchedule } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentSchedule';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementStatus } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementStatus';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementUnit } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementUnit';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementUserIncharge } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementUserIncharge';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementUserTenant } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementUserTenant';
import type { SDJCRMCoreSharedEnumsLATypeEnum } from './sDJCRMCoreSharedEnumsLATypeEnum';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  type?: SDJCRMCoreSharedEnumsLATypeEnum;
  /**
     * @minLength 0
     * @maxLength 512
     * @nullable
     */
  bookingDealer?: string | null;
  uniqueId?: string;
  /** @nullable */
  parentId?: number | null;
  parent?: __SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement;
  /** @nullable */
  leaseAgreementAmendmentId?: number | null;
  /** @nullable */
  referenceNumber?: string | null;
  /** @nullable */
  inquiryId?: number | null;
  /** @nullable */
  reservationId?: number | null;
  contactId?: number;
  contact?: SDJCRMCoreContactsEntitiesContact;
  statusId?: number;
  /** @nullable */
  isBlock?: boolean | null;
  status?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementStatus;
  stageId?: number;
  stage?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementStatus;
  /** @nullable */
  companyId?: number | null;
  company?: SDJCRMCoreCompanyEntitiesCompany;
  /** @nullable */
  occupier?: string | null;
  /** @nullable */
  occupierVi?: string | null;
  contractAmount?: number;
  /** @nullable */
  contractAmountIncludeVat?: number | null;
  /** @nullable */
  contractAmountAfterDiscountIncludeVat?: number | null;
  /** @nullable */
  contractAmountAfterDiscountExcludeVat?: number | null;
  /** @nullable */
  discountAmountIncludeVat?: number | null;
  /** @nullable */
  discountAmountExcludeVat?: number | null;
  commencementDate?: string;
  expiryDate?: string;
  /** @nullable */
  extensionDate?: string | null;
  /** @nullable */
  terminationDate?: string | null;
  /** @nullable */
  moveInDate?: string | null;
  /** @nullable */
  moveOutDate?: string | null;
  /** @nullable */
  leaseTerm?: string | null;
  /** @nullable */
  leaseTermDay?: number | null;
  /** @nullable */
  leaseTermMonth?: number | null;
  /** @nullable */
  leaseTermYear?: number | null;
  paymentTerm?: number;
  /** @nullable */
  paymentDate?: string | null;
  /** @nullable */
  incentiveAmount?: number | null;
  /** @nullable */
  commissionAmount?: number | null;
  /** @nullable */
  commissionPercent?: number | null;
  /** @nullable */
  rateUSD?: number | null;
  /** @nullable */
  isKeeptheAnnualRent?: boolean | null;
  expiredDayNotification?: number;
  depositAmount?: number;
  /** @nullable */
  depositStatusId?: number | null;
  /** @nullable */
  depositSendDate?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  amendmentDescription?: string | null;
  /** @nullable */
  reasonDrop?: string | null;
  isRequest?: boolean;
  isActive?: boolean;
  isCurrent?: boolean;
  /** @nullable */
  persons?: number | null;
  /** @nullable */
  amendmentMoveInDate?: string | null;
  /** @nullable */
  leaseAgreementUnit?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementUnit[] | null;
  /** @nullable */
  leaseAgreementDetails?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDetails[] | null;
  /** @nullable */
  leaseAgreementDiscount?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDiscount[] | null;
  /** @nullable */
  leaseAgreementIncentive?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementIncentive[] | null;
  /** @nullable */
  leaseAgreementUserIncharge?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementUserIncharge[] | null;
  /** @nullable */
  leaseAgreementPaymentSchedule?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentSchedule[] | null;
  /** @nullable */
  leaseAgreementUserTenant?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementUserTenant[] | null;
  /** @nullable */
  leaseAgreementAmendmentTypeMap?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementAmendmentTypeMap[] | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
