/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreProjectsProjectGradeMap } from './sDJCRMCoreProjectsProjectGradeMap';

export interface SDJCRMCoreProjectsGrade {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  name?: string | null;
  isActive?: boolean;
  /** @nullable */
  projectGradeMap?: SDJCRMCoreProjectsProjectGradeMap[] | null;
}
