/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUnitDtoPagedExportUnitResultRequestDto {
  /**
     * @minimum 1
     * @maximum 2147483647
     */
  maxResultCount?: number;
  /**
     * @minimum 0
     * @maximum 2147483647
     */
  skipCount?: number;
  /** @nullable */
  inquiryId?: number | null;
  /** @nullable */
  keyword?: string | null;
  /** @nullable */
  projectId?: number | null;
  /** @nullable */
  projectIds?: number[] | null;
  /** @nullable */
  assignProjectIds?: number[] | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  unitStatusId?: number | null;
  /** @nullable */
  unitStatusIds?: number[] | null;
  /** @nullable */
  provinceId?: number | null;
  /** @nullable */
  districtId?: number | null;
  /** @nullable */
  facingId?: number | null;
  /** @nullable */
  unitTypeId?: number | null;
  /** @nullable */
  floorId?: number | null;
  /** @nullable */
  productTypeId?: number | null;
  /** @nullable */
  fromDate?: string | null;
  /** @nullable */
  toDate?: string | null;
  /** @nullable */
  fromPrice?: number | null;
  /** @nullable */
  toPrice?: number | null;
  /** @nullable */
  fromSize?: number | null;
  /** @nullable */
  toSize?: number | null;
  /** @nullable */
  unitTypeIds?: number[] | null;
  /** @nullable */
  ids?: number[] | null;
  /** @nullable */
  facingIds?: number[] | null;
  /** @nullable */
  viewIds?: number[] | null;
  /** @nullable */
  facilityIds?: number[] | null;
  /** @nullable */
  productTypeIds?: number[] | null;
  /** @nullable */
  sorting?: string | null;
}
