/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationConfigurationDtoTwoFactorLoginSettingsEditDto } from './sDJCRMApplicationConfigurationDtoTwoFactorLoginSettingsEditDto';
import type { SDJCRMCoreSharedSecurityPasswordComplexitySetting } from './sDJCRMCoreSharedSecurityPasswordComplexitySetting';

export interface SDJCRMWebCoreControllersAuthenticateProviderDto {
  allowSelfRegistration?: boolean;
  useCaptchaOnRegistration?: boolean;
  passwordComplexity?: SDJCRMCoreSharedSecurityPasswordComplexitySetting;
  defaultPasswordComplexity?: SDJCRMCoreSharedSecurityPasswordComplexitySetting;
  twoFactorLogin?: SDJCRMApplicationConfigurationDtoTwoFactorLoginSettingsEditDto;
}
