/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectManagementDtoWorkScheduleWorkDetailInputDto } from './sDJCRMApplicationDefectDefectManagementDtoWorkScheduleWorkDetailInputDto';

export interface SDJCRMApplicationDefectDefectManagementDtoWorkScheduleInputDto {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  standardizedEndDate?: string | null;
  /** @nullable */
  actualSubmissionDate?: string | null;
  /** @nullable */
  plannedStartDate?: string | null;
  /** @nullable */
  plannedEndDate?: string | null;
  /** @nullable */
  actualStartDate?: string | null;
  /** @nullable */
  actualEndDate?: string | null;
  /**
     * @minLength 0
     * @maxLength 5000
     * @nullable
     */
  description?: string | null;
  /** @nullable */
  workScheduleWorkDetails?: SDJCRMApplicationDefectDefectManagementDtoWorkScheduleWorkDetailInputDto[] | null;
}
