/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreAuthorizationUsersDtoBankAccountSettingEditDto {
  /** @nullable */
  accountNo?: string | null;
  /** @nullable */
  branchName?: string | null;
  /** @nullable */
  beneficiaryName?: string | null;
}
