/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationConfigurationDtoTermAndConditionOutputDto {
  subjectId?: string;
  contentId?: string;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  content?: string | null;
}
