/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition = typeof SDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition[keyof typeof SDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition];


export const SDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
