/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUnitDtoUnitHistoryOutputDto {
  /** @nullable */
  id?: number | null;
  floorId?: number;
  /** @nullable */
  floorName?: string | null;
  /** @nullable */
  projectName?: string | null;
  projectId?: number;
  orgTenantId?: number;
  /** @nullable */
  tenantLegalName?: string | null;
  /** @nullable */
  tenantBusinessName?: string | null;
  unitId?: number;
  /** @nullable */
  unitName?: string | null;
  /** @nullable */
  cars?: number | null;
  /** @nullable */
  motorbikes?: number | null;
  /** @nullable */
  itServices?: string | null;
  /** @nullable */
  backupPower?: string | null;
  /** @nullable */
  space?: number | null;
  /** @nullable */
  headCount?: number | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  expiredDate?: string | null;
  /** @nullable */
  reasonMove?: string | null;
  isActive?: boolean;
  /** @nullable */
  monthly?: number | null;
  /** @nullable */
  per?: number | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  creatorSurname?: string | null;
  /** @nullable */
  creatorUserName?: string | null;
  /** @nullable */
  lastModifierSurname?: string | null;
  /** @nullable */
  lastModifierUserName?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  incentives?: number | null;
  /** @nullable */
  netEffectiveRental?: number | null;
}
