/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailOutputDto } from './sDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationDefectDefectManagementDtoHandoverOutputDto {
  id?: number;
  defectId?: number;
  isCompleted?: boolean;
  /** @nullable */
  handoverDate?: string | null;
  /** @nullable */
  actualDate?: string | null;
  /** @nullable */
  description?: string | null;
  uniqueId?: string;
  isDelay?: boolean;
  /** @nullable */
  delayDays?: number | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  /** @nullable */
  methodAndQuotationWorkDetails?: SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailOutputDto[] | null;
}
