/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCompanyCompanyContactCompanyContactInputDto } from './sDJCRMApplicationCompanyCompanyContactCompanyContactInputDto';
import type { SDJCRMApplicationContactContactAddressContactAddressInputDto } from './sDJCRMApplicationContactContactAddressContactAddressInputDto';
import type { SDJCRMApplicationContactContactEmailContactEmailInputDto } from './sDJCRMApplicationContactContactEmailContactEmailInputDto';
import type { SDJCRMApplicationContactContactPhoneContactPhoneInputDto } from './sDJCRMApplicationContactContactPhoneContactPhoneInputDto';

export interface SDJCRMApplicationContactDtoContactInputDto {
  id?: number;
  /** @nullable */
  companyId?: number | null;
  /** @nullable */
  leaseAgreementId?: number | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  contactName?: string | null;
  /** @nullable */
  contactNameVi?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  titleVi?: string | null;
  /** @nullable */
  leadSourceId?: number | null;
  /** @nullable */
  levelId?: number | null;
  /** @nullable */
  typeId?: number | null;
  /** @nullable */
  nationalityId?: number | null;
  /** @nullable */
  contactAddress?: SDJCRMApplicationContactContactAddressContactAddressInputDto[] | null;
  /** @nullable */
  contactEmail?: SDJCRMApplicationContactContactEmailContactEmailInputDto[] | null;
  /** @nullable */
  contactPhone?: SDJCRMApplicationContactContactPhoneContactPhoneInputDto[] | null;
  /** @nullable */
  contactTypeIds?: number[] | null;
  /** @nullable */
  userIds?: number[] | null;
  /** @nullable */
  organizationUnitIds?: number[] | null;
  /** @nullable */
  companyContact?: SDJCRMApplicationCompanyCompanyContactCompanyContactInputDto[] | null;
}
