/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreLeaseAgreementsDtoLeaseAgreementDetailFeeTyeOutputDto {
  startDate?: string;
  endDate?: string;
  feeTypeId?: number;
  totalAmount?: number;
  totalAmountIncludeVat?: number;
  amount?: number;
  rentExcludeVAT?: number;
  amountIncludeVAT?: number;
  vatAmount?: number;
  /** @nullable */
  rowIndex?: number | null;
}
