/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLocalizationDtoUpdateLanguageTextInput {
  /**
     * @minLength 0
     * @maxLength 128
     */
  languageName: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  sourceName: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  key: string;
  /**
     * @minLength 0
     * @maxLength 67108864
     */
  value: string;
}
