/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectManagementDtoInspectionWorkDetailInputDto } from './sDJCRMApplicationDefectDefectManagementDtoInspectionWorkDetailInputDto';
import type { SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum } from './sDJCRMCoreSharedEnumsDefectConfigurationTypeEnum';

export interface SDJCRMApplicationDefectDefectManagementDtoInspectionInputDto {
  id?: number;
  defectConfigurationType: SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum;
  /** @nullable */
  standardizedEndDate?: string | null;
  /** @nullable */
  actualStartDate?: string | null;
  /**
     * @minLength 0
     * @maxLength 5000
     * @nullable
     */
  description?: string | null;
  /** @nullable */
  inspectionWorkDetails?: SDJCRMApplicationDefectDefectManagementDtoInspectionWorkDetailInputDto[] | null;
}
