/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpNotificationsUserNotification } from './abpNotificationsUserNotification';

export interface SDJCRMApplicationNotificationsDtoGetNotificationsOutput {
  /** @nullable */
  items?: AbpNotificationsUserNotification[] | null;
  totalCount?: number;
  unreadCount?: number;
}
