/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementDetailsInputDto } from './sDJCRMApplicationLADtoLeaseAgreementDetailsInputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementDiscountInputDto } from './sDJCRMApplicationLADtoLeaseAgreementDiscountInputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementIncentiveInputDto } from './sDJCRMApplicationLADtoLeaseAgreementIncentiveInputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUnitInputDto } from './sDJCRMApplicationLADtoLeaseAgreementUnitInputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUserInchargeInputDto } from './sDJCRMApplicationLADtoLeaseAgreementUserInchargeInputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUserTenantInputDto } from './sDJCRMApplicationLADtoLeaseAgreementUserTenantInputDto';

export interface SDJCRMApplicationLADtoAmendmentInputDto {
  id?: number;
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  referenceNumber?: string | null;
  /** @nullable */
  inquiryId?: number | null;
  /** @nullable */
  reservationId?: number | null;
  contactId?: number;
  statusId?: number;
  stageId?: number;
  /** @nullable */
  companyId?: number | null;
  /** @nullable */
  occupier?: string | null;
  commencementDate?: string;
  expiryDate?: string;
  /** @nullable */
  extensionDate?: string | null;
  /** @nullable */
  terminationDate?: string | null;
  /** @nullable */
  moveInDate?: string | null;
  /** @nullable */
  moveOutDate?: string | null;
  depositAmount?: number;
  /** @nullable */
  leaseTerm?: string | null;
  /** @nullable */
  leaseTermDay?: number | null;
  /** @nullable */
  leaseTermMonth?: number | null;
  /** @nullable */
  leaseTermYear?: number | null;
  contractAmount?: number;
  /** @nullable */
  contractAmountIncludeVat?: number | null;
  contractAmountAfterDiscountIncludeVat?: number;
  contractAmountAfterDiscountExcludeVat?: number;
  /** @nullable */
  discountAmountIncludeVat?: number | null;
  /** @nullable */
  discountAmountExcludeVat?: number | null;
  paymentTerm?: number;
  /** @nullable */
  paymentDate?: string | null;
  commissionAmount?: number;
  /** @nullable */
  commissionPercent?: number | null;
  /** @nullable */
  rateUSD?: number | null;
  /** @nullable */
  incentiveAmount?: number | null;
  /** @nullable */
  isKeeptheAnnualRent?: boolean | null;
  expiredDayNotification?: number;
  /** @nullable */
  depositStatusId?: number | null;
  /** @nullable */
  depositSendDate?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  amendmentDescription?: string | null;
  isRequest?: boolean;
  /** @nullable */
  amendmentMoveInDate?: string | null;
  /** @nullable */
  leaseAgreementAmendmentId?: number | null;
  /** @nullable */
  amendmentTypeIds?: number[] | null;
  /** @nullable */
  leaseAgreementDetails?: SDJCRMApplicationLADtoLeaseAgreementDetailsInputDto[] | null;
  /** @nullable */
  leaseAgreementIncentive?: SDJCRMApplicationLADtoLeaseAgreementIncentiveInputDto[] | null;
  /** @nullable */
  leaseAgreementUnit?: SDJCRMApplicationLADtoLeaseAgreementUnitInputDto[] | null;
  /** @nullable */
  leaseAgreementUserIncharge?: SDJCRMApplicationLADtoLeaseAgreementUserInchargeInputDto[] | null;
  /** @nullable */
  leaseAgreementDiscount?: SDJCRMApplicationLADtoLeaseAgreementDiscountInputDto[] | null;
  /** @nullable */
  leaseAgreementUserTenant?: SDJCRMApplicationLADtoLeaseAgreementUserTenantInputDto[] | null;
}
