/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionDetailsInputDto } from './sDJCRMApplicationLADtoCommissionLeaseAgreementCommissionDetailsInputDto';

export interface SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseInputDto {
  id?: number;
  leaseAgreementId?: number;
  numPhase?: number;
  leaseAgreementCommissionMasterId?: number;
  /** @nullable */
  phase?: string | null;
  billingDate?: string;
  actBillingDate?: string;
  statusId?: number;
  departmentCommissionAmountByPhase?: number;
  dealerCommissionAmountByPhase?: number;
  percent?: number;
  /** @nullable */
  leaseAgreementCommissionDetails?: SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionDetailsInputDto[] | null;
}
