/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationInquiriesDtoInquiryTaskUserOutputDto {
  id?: number;
  inquiryTaskId?: number;
  userId?: number;
  user?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
}
