/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreSettingEntitiesFeeType } from './sDJCRMCoreSettingEntitiesFeeType';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDetails {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementId?: number;
  /** @nullable */
  name?: string | null;
  uniqueId?: string;
  /** @nullable */
  parentId?: string | null;
  feeTypeId?: number;
  feeType?: SDJCRMCoreSettingEntitiesFeeType;
  /** @nullable */
  amount?: number | null;
  /** @nullable */
  vatPecent?: number | null;
  /** @nullable */
  vatAmount?: number | null;
  /** @nullable */
  totalAmount?: number | null;
  /** @nullable */
  rentNotVatUsd?: number | null;
  /** @nullable */
  amountIncludeVAT?: number | null;
  /** @nullable */
  totalAmountIncludeVat?: number | null;
  /** @nullable */
  rentOnly?: number | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
