/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationTemplateManagementDtoValueOutput } from './sDJCRMApplicationTemplateManagementDtoValueOutput';

export interface SDJCRMApplicationTemplateManagementDtoNotificationTypeOutput {
  id?: number;
  moduleId?: number;
  /** @nullable */
  notificationName?: string | null;
  /** @nullable */
  notificationCode?: string | null;
  /** @nullable */
  template?: string | null;
  /** @nullable */
  notificationType?: string | null;
  module?: SDJCRMApplicationTemplateManagementDtoValueOutput;
}
