/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCompanyDtoCompanySimpleOutputDto } from './sDJCRMApplicationCompanyDtoCompanySimpleOutputDto';
import type { SDJCRMApplicationContactDtoContactSimpleOutputDto } from './sDJCRMApplicationContactDtoContactSimpleOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementAmendmentTypeMapOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementAmendmentTypeMapOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementDetailsOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementDetailsOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementDiscountOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementDiscountOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementIncentiveOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementIncentiveOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUnitOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementUnitOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUserInchargeOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementUserInchargeOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUserTenantOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementUserTenantOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationLADtoLeaseAgreementOutputDto {
  id?: number;
  /** @nullable */
  parentId?: number | null;
  parent?: SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto;
  uniqueId?: string;
  /** @nullable */
  referenceNumber?: string | null;
  /** @nullable */
  inquiryId?: number | null;
  /** @nullable */
  reservationId?: number | null;
  /** @nullable */
  isBlock?: boolean | null;
  contactId?: number;
  contact?: SDJCRMApplicationContactDtoContactSimpleOutputDto;
  statusId?: number;
  status?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  /** @nullable */
  depositStatusId?: number | null;
  depositStatus?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  /** @nullable */
  depositSendDate?: string | null;
  stageId?: number;
  stage?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  /** @nullable */
  companyId?: number | null;
  company?: SDJCRMApplicationCompanyDtoCompanySimpleOutputDto;
  /** @nullable */
  occupier?: string | null;
  commencementDate?: string;
  expiryDate?: string;
  /** @nullable */
  extensionDate?: string | null;
  /** @nullable */
  terminationDate?: string | null;
  /** @nullable */
  moveInDate?: string | null;
  /** @nullable */
  moveOutDate?: string | null;
  /** @nullable */
  leaseTerm?: string | null;
  /** @nullable */
  leaseTermDay?: number | null;
  /** @nullable */
  leaseTermMonth?: number | null;
  /** @nullable */
  leaseTermYear?: number | null;
  paymentTerm?: number;
  /** @nullable */
  paymentDate?: string | null;
  depositAmount?: number;
  /** @nullable */
  contractAmountIncludeVat?: number | null;
  contractAmount?: number;
  contractAmountAfterDiscountIncludeVat?: number;
  contractAmountAfterDiscountExcludeVat?: number;
  discountAmountIncludeVat?: number;
  discountAmountExcludeVat?: number;
  commissionAmount?: number;
  /** @nullable */
  commissionPercent?: number | null;
  /** @nullable */
  rateUSD?: number | null;
  /** @nullable */
  isKeeptheAnnualRent?: boolean | null;
  isActive?: boolean;
  expiredDayNotification?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  amendmentDescription?: string | null;
  isRequest?: boolean;
  /** @nullable */
  rentCollectedAmount?: number | null;
  /** @nullable */
  sapAllowance?: number | null;
  /** @nullable */
  allowance?: number | null;
  /** @nullable */
  scAmount?: number | null;
  /** @nullable */
  rentOnly?: number | null;
  /** @nullable */
  vatAmount?: number | null;
  /** @nullable */
  rentSCIncVAT?: number | null;
  /** @nullable */
  rentSCExcVal?: number | null;
  /** @nullable */
  reasonDrop?: string | null;
  isShareCommission?: boolean;
  isCurrent?: boolean;
  /** @nullable */
  amendmentMoveInDate?: string | null;
  /** @nullable */
  leaseAgreementAmendmentId?: number | null;
  /** @nullable */
  persons?: number | null;
  isMorePrice?: boolean;
  /** @nullable */
  leaseAgreementDetails?: SDJCRMApplicationLADtoLeaseAgreementDetailsOutputDto[] | null;
  /** @nullable */
  leaseAgreementDiscount?: SDJCRMApplicationLADtoLeaseAgreementDiscountOutputDto[] | null;
  /** @nullable */
  leaseAgreementIncentive?: SDJCRMApplicationLADtoLeaseAgreementIncentiveOutputDto[] | null;
  /** @nullable */
  leaseAgreementUnit?: SDJCRMApplicationLADtoLeaseAgreementUnitOutputDto[] | null;
  /** @nullable */
  leaseAgreementUserIncharge?: SDJCRMApplicationLADtoLeaseAgreementUserInchargeOutputDto[] | null;
  /** @nullable */
  leaseAgreementAmendmentTypeMap?: SDJCRMApplicationLADtoLeaseAgreementAmendmentTypeMapOutputDto[] | null;
  /** @nullable */
  leaseAgreementUserTenant?: SDJCRMApplicationLADtoLeaseAgreementUserTenantOutputDto[] | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
}
