/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAreaCountry } from './sDJCRMCoreAreaCountry';
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreCompanyEntitiesCompany } from './sDJCRMCoreCompanyEntitiesCompany';
import type { SDJCRMCoreCompanyEntitiesCompanyContact } from './sDJCRMCoreCompanyEntitiesCompanyContact';
import type { SDJCRMCoreCompanyEntitiesLeadSource } from './sDJCRMCoreCompanyEntitiesLeadSource';
import type { SDJCRMCoreContactsEntitiesContactAddress } from './sDJCRMCoreContactsEntitiesContactAddress';
import type { SDJCRMCoreContactsEntitiesContactEmail } from './sDJCRMCoreContactsEntitiesContactEmail';
import type { SDJCRMCoreContactsEntitiesContactOrganizationUnit } from './sDJCRMCoreContactsEntitiesContactOrganizationUnit';
import type { SDJCRMCoreContactsEntitiesContactPhone } from './sDJCRMCoreContactsEntitiesContactPhone';
import type { SDJCRMCoreContactsEntitiesContactTypeMap } from './sDJCRMCoreContactsEntitiesContactTypeMap';
import type { SDJCRMCoreContactsEntitiesContactUser } from './sDJCRMCoreContactsEntitiesContactUser';
import type { SDJCRMCoreContactsEntitiesLevel } from './sDJCRMCoreContactsEntitiesLevel';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementContact } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementContact';

export interface SDJCRMCoreContactsEntitiesContact {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  uniqueId?: string;
  /** @nullable */
  companyId?: number | null;
  company?: SDJCRMCoreCompanyEntitiesCompany;
  /** @nullable */
  contactName?: string | null;
  /** @nullable */
  contactNameVi?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  titleVi?: string | null;
  /** @nullable */
  leadSourceId?: number | null;
  leadSource?: SDJCRMCoreCompanyEntitiesLeadSource;
  /** @nullable */
  typeId?: number | null;
  /** @nullable */
  levelId?: number | null;
  level?: SDJCRMCoreContactsEntitiesLevel;
  isActive?: boolean;
  /** @nullable */
  nationalityId?: number | null;
  nationality?: SDJCRMCoreAreaCountry;
  /** @nullable */
  description?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
  /** @nullable */
  contactUser?: SDJCRMCoreContactsEntitiesContactUser[] | null;
  /** @nullable */
  contactOrganizationUnit?: SDJCRMCoreContactsEntitiesContactOrganizationUnit[] | null;
  /** @nullable */
  contactEmail?: SDJCRMCoreContactsEntitiesContactEmail[] | null;
  /** @nullable */
  contactTypeMap?: SDJCRMCoreContactsEntitiesContactTypeMap[] | null;
  /** @nullable */
  contactPhone?: SDJCRMCoreContactsEntitiesContactPhone[] | null;
  /** @nullable */
  contactAddress?: SDJCRMCoreContactsEntitiesContactAddress[] | null;
  /** @nullable */
  companyContact?: SDJCRMCoreCompanyEntitiesCompanyContact[] | null;
  /** @nullable */
  leaseAgreementContact?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementContact[] | null;
}
