/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAuthorizationAccountsDtoIsSocialLoginAvailableInput {
  /**
     * @minLength 0
     * @maxLength 128
     */
  authProvider: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  providerKey: string;
  /** @minLength 1 */
  providerAccessCode: string;
}
