/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { AbpWebModelsValidationErrorInfo } from './abpWebModelsValidationErrorInfo';

export interface SDJCRMApplicationAuthorizationAccountsDtoUploadProfilePictureOutput {
  code?: number;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  details?: string | null;
  /** @nullable */
  validationErrors?: AbpWebModelsValidationErrorInfo[] | null;
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  fileType?: string | null;
  /** @nullable */
  fileToken?: string | null;
  width?: number;
  height?: number;
}
