/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCategoryLevelOutputDto } from './sDJCRMApplicationCategoryLevelOutputDto';
import type { SDJCRMApplicationCompanyDtoCompanySimpleOutputDto } from './sDJCRMApplicationCompanyDtoCompanySimpleOutputDto';
import type { SDJCRMApplicationContactContactEmailContactEmailOutputDto } from './sDJCRMApplicationContactContactEmailContactEmailOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';

export interface SDJCRMApplicationContactDtoContactSimpleOutputDto {
  id?: number;
  /** @nullable */
  companyId?: number | null;
  company?: SDJCRMApplicationCompanyDtoCompanySimpleOutputDto;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  contactName?: string | null;
  /** @nullable */
  typeId?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  levelId?: number | null;
  level?: SDJCRMApplicationCategoryLevelOutputDto;
  isActive?: boolean;
  creationTime?: string;
  creatorUserId?: number;
  /** @nullable */
  contactEmail?: SDJCRMApplicationContactContactEmailContactEmailOutputDto[] | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
}
