/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUserTenantDtoSimpleUserTenantOutputDto } from './sDJCRMApplicationUserTenantDtoSimpleUserTenantOutputDto';

export interface SDJCRMApplicationUnitHandoverDtoUnitHandoverSuggestionLA {
  id?: number;
  /** @nullable */
  referenceNumber?: string | null;
  /** @nullable */
  tenants?: SDJCRMApplicationUserTenantDtoSimpleUserTenantOutputDto[] | null;
  unitId?: number;
  /** @nullable */
  unitName?: string | null;
  ciDate?: string;
  /** @nullable */
  coDate?: string | null;
}
