/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationInquiriesDtoInquiryTaskInputDto {
  id?: number;
  /** @nullable */
  inquiryId?: number | null;
  /** @nullable */
  subject?: string | null;
  inquiryTaskStatusId?: number;
  /** @nullable */
  dueDate?: string | null;
  /** @nullable */
  remindDate?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  userIds?: number[] | null;
}
