/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreCompanyEntitiesCompany } from './sDJCRMCoreCompanyEntitiesCompany';

export interface SDJCRMApplicationCompanyCompanyPhoneCompanyPhoneOutputDto {
  /** @nullable */
  id?: number | null;
  companyId?: number;
  company?: SDJCRMCoreCompanyEntitiesCompany;
  /** @nullable */
  phoneTypeId?: number | null;
  /** @nullable */
  phoneTypeName?: string | null;
  isPrimary?: boolean;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  countryId?: number | null;
  /** @nullable */
  phoneCode?: string | null;
  isActive?: boolean;
}
