/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationWorkOrderWorkOrderDtoWorkOrderUpdateInputDto {
  id?: number;
  /** @nullable */
  woCategoryId?: number | null;
  projectId: number;
  /** @nullable */
  unitId?: number | null;
  /** @nullable */
  zoneId?: number | null;
  assetId: number;
  /**
     * @minLength 0
     * @maxLength 500
     * @nullable
     */
  description?: string | null;
  statusId?: number;
  endDate: string;
  picId?: number;
  repairingCost: number;
  /** @nullable */
  providerId?: number | null;
}
