/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationDefectDefectManagementDtoInspectionWorkDetailInputDto {
  /** @nullable */
  id?: number | null;
  /**
     * @minLength 0
     * @maxLength 5000
     */
  task: string;
  implementDate: string;
  completePercent?: number;
}
