/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationPlanMaintenanceDtoAssetMonthOutputV2Dto } from './sDJCRMApplicationPlanMaintenanceDtoAssetMonthOutputV2Dto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';

export interface SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceMonthV2OutputDto {
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  /** @nullable */
  assetMonth?: SDJCRMApplicationPlanMaintenanceDtoAssetMonthOutputV2Dto[] | null;
}
