/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreSharedEnumsDefectTabsEnum = typeof SDJCRMCoreSharedEnumsDefectTabsEnum[keyof typeof SDJCRMCoreSharedEnumsDefectTabsEnum];


export const SDJCRMCoreSharedEnumsDefectTabsEnum = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
} as const;
