/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto } from './sDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto';

export interface SDJCRMApplicationDefectReportingsDtoDefectReportDayOfSolution {
  defectPriority?: SDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto;
  totalWithin15Days?: number;
  totalWithin15To30Days?: number;
  totalWithin30To45Days?: number;
  totalWithin45To60Days?: number;
  totalWithin60To75Days?: number;
  totalOver70Days?: number;
}
