/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationConfigurationDtoDomainSettingsEditDto } from './sDJCRMApplicationConfigurationDtoDomainSettingsEditDto';
import type { SDJCRMApplicationConfigurationDtoGeneralSettingsEditDto } from './sDJCRMApplicationConfigurationDtoGeneralSettingsEditDto';
import type { SDJCRMApplicationConfigurationDtoSecuritySettingsEditDto } from './sDJCRMApplicationConfigurationDtoSecuritySettingsEditDto';
import type { SDJCRMApplicationConfigurationDtoTenantUserManagementSettingsEditDto } from './sDJCRMApplicationConfigurationDtoTenantUserManagementSettingsEditDto';

export interface SDJCRMApplicationConfigurationDtoTenantSettingsEditDto {
  general?: SDJCRMApplicationConfigurationDtoGeneralSettingsEditDto;
  userManagement: SDJCRMApplicationConfigurationDtoTenantUserManagementSettingsEditDto;
  security: SDJCRMApplicationConfigurationDtoSecuritySettingsEditDto;
  domain?: SDJCRMApplicationConfigurationDtoDomainSettingsEditDto;
}
