/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationNotificationsDtoNotificationSubscriptionDto {
  /**
     * @minLength 1
     * @maxLength 96
     */
  name: string;
  isSubscribed?: boolean;
}
