/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';
import type { SDJCRMCoreSettingDtoFeeTypeOutputDto } from './sDJCRMCoreSettingDtoFeeTypeOutputDto';

export interface SDJCRMApplicationSettingVATDtoSettingVATOutputDto {
  id?: number;
  feeTypeId?: number;
  feeType?: SDJCRMCoreSettingDtoFeeTypeOutputDto;
  vat?: number;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  startYear?: number | null;
  /** @nullable */
  endYear?: number | null;
  /** @nullable */
  startMonth?: number | null;
  /** @nullable */
  endMonth?: number | null;
  creationTime?: string;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
}
