/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersEmployeesDtoEmployeeProjectRoleDto } from './sDJCRMApplicationUsersEmployeesDtoEmployeeProjectRoleDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';
import type { SDJCRMCoreSharedOrganizationUnitDtoUserToOrganizationUnitOutput } from './sDJCRMCoreSharedOrganizationUnitDtoUserToOrganizationUnitOutput';
import type { SDJCRMCoreUsersDtoWarningInformationDto } from './sDJCRMCoreUsersDtoWarningInformationDto';

export interface SDJCRMApplicationUsersEmployeesDtoEmployeeOutputDto {
  id?: number;
  /** @nullable */
  profilePictureId?: string | null;
  /**
     * @minLength 0
     * @maxLength 256
     */
  userName: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  surname: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  emailAddress: string;
  /**
     * @minLength 0
     * @maxLength 32
     * @nullable
     */
  phoneNumber?: string | null;
  isActive?: boolean;
  /** @nullable */
  birthDate?: string | null;
  /** @nullable */
  titleName?: string | null;
  status?: boolean;
  /** @nullable */
  gender?: boolean | null;
  /** @nullable */
  passport?: string | null;
  /** @nullable */
  identityNumber?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  lastLoginTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  /** @nullable */
  lastModifierUserId?: number | null;
  userInfo?: SDJCRMCoreUsersDtoWarningInformationDto;
  rating?: number;
  /** @nullable */
  roleNames?: string[] | null;
  /** @nullable */
  userOrganizationUnit?: SDJCRMCoreSharedOrganizationUnitDtoUserToOrganizationUnitOutput[] | null;
  /** @nullable */
  projectUser?: SDJCRMApplicationUsersEmployeesDtoEmployeeProjectRoleDto[] | null;
}
