/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreLocalizationDtoLocalizationDto {
  /**
     * @minLength 0
     * @maxLength 128
     */
  languageName: string;
  /**
     * @minLength 0
     * @maxLength 67108864
     * @nullable
     */
  value?: string | null;
}
