/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedProjectsUnitsStatusConstants } from './sDJCRMCoreSharedProjectsUnitsStatusConstants';

export interface SDJCRMApplicationLADtoLeaseAgreementStatusInputDto {
  id?: number;
  stageId?: number;
  statusId?: number;
  unitStatusId?: SDJCRMCoreSharedProjectsUnitsStatusConstants;
  /** @nullable */
  terminationDate?: string | null;
  /** @nullable */
  reasonDrop?: string | null;
}
