/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLADtoDepositLeaseAgreementDepositCollectInputDto {
  id?: number;
  leaseAgreementId?: number;
  leaseAgreementDepositId?: number;
  /** @nullable */
  receiptNo?: string | null;
  /** @nullable */
  receiptDate?: string | null;
  /** @nullable */
  paymentDate?: string | null;
  /** @nullable */
  remark?: string | null;
  receiptAmount?: number;
}
