/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUnitDtoUnitHistoryOutputDto } from './sDJCRMApplicationUnitDtoUnitHistoryOutputDto';

export interface SDJCRMApplicationUnitDtoUnitOutputDto {
  id?: number;
  /** @nullable */
  expiredType?: string | null;
  floorId?: number;
  /** @nullable */
  floorName?: string | null;
  /** @nullable */
  unitName?: string | null;
  projectId?: number;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  expiredDate?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  orgTenantId?: number | null;
  /** @nullable */
  orgTenantBusinessName?: string | null;
  /** @nullable */
  orgTenantLegalName?: string | null;
  /** @nullable */
  size?: number | null;
  statusId?: number;
  /** @nullable */
  statusName?: string | null;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  description?: string | null;
  unitTypeId?: number;
  /** @nullable */
  unitTypeName?: string | null;
  /** @nullable */
  monthly?: number | null;
  /** @nullable */
  per?: number | null;
  order?: number;
  isActive?: boolean;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  creatorSurname?: string | null;
  /** @nullable */
  creatorUserName?: string | null;
  /** @nullable */
  lastModifierSurname?: string | null;
  /** @nullable */
  lastModifierUserName?: string | null;
  /** @nullable */
  price?: number | null;
  unitHistory?: SDJCRMApplicationUnitDtoUnitHistoryOutputDto;
}
