/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAreaProvince } from './sDJCRMCoreAreaProvince';

export interface SDJCRMCoreAreaDistrict {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  districtCode?: string | null;
  /** @nullable */
  districtName?: string | null;
  provinceId?: number;
  province?: SDJCRMCoreAreaProvince;
  isActive?: boolean;
}
