/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUnitDtoSimpleUnitOutputDto {
  id?: number;
  uniqueId?: string;
  /** @nullable */
  unitName?: string | null;
  projectId?: number;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  projectCode?: string | null;
}
