/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationInquiriesDtoInquiryMailInputDto {
  id?: number;
  inquiryId?: number;
  uniqueId?: string;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  sendDate?: string | null;
  /** @nullable */
  description?: string | null;
}
