/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition } from './sDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition';

export interface SDJCRMApplicationLADtoLeaseAgreementUserInchargeInputDto {
  id?: number;
  leaseAgreementId?: number;
  userId?: number;
  positionId?: SDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition;
}
