/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';

export interface SDJCRMApplicationCompanyCompanyUserCompanyUserOutputDto {
  id?: number;
  companyId?: number;
  userId?: number;
  user?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  /** @nullable */
  isFollwer?: boolean | null;
  isActive?: boolean;
}
