/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContractProviderContractDtoProviderContractPaidInputDto } from './sDJCRMApplicationContractProviderContractDtoProviderContractPaidInputDto';
import type { SDJCRMApplicationRemindersDtoReminderInputDto } from './sDJCRMApplicationRemindersDtoReminderInputDto';
import type { SDJCRMCoreSharedContractContractConstantsContractType } from './sDJCRMCoreSharedContractContractConstantsContractType';

export interface SDJCRMApplicationContractProviderContractDtoProviderContractUpdateInputDto {
  id?: number;
  projectIds: number[];
  companyId: number;
  /**
     * @minLength 0
     * @maxLength 250
     */
  contractId: string;
  /**
     * @minLength 0
     * @maxLength 250
     */
  contractName: string;
  contractCategoryId: number;
  contractTypeId: SDJCRMCoreSharedContractContractConstantsContractType;
  /** @nullable */
  contractParentId?: number | null;
  /** @nullable */
  signDate?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  expiryDate?: string | null;
  contractPrice: number;
  usage: number;
  tax: number;
  /**
     * @minLength 0
     * @maxLength 250
     * @nullable
     */
  contractPaymentTerm?: string | null;
  /**
     * @minLength 0
     * @maxLength 5000
     * @nullable
     */
  description?: string | null;
  /** @nullable */
  contractValue?: number | null;
  reminder?: SDJCRMApplicationRemindersDtoReminderInputDto;
  /** @nullable */
  providerContractPaids?: SDJCRMApplicationContractProviderContractDtoProviderContractPaidInputDto[] | null;
}
