/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType } from './sDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType';

export interface SDJCRMApplicationAssetManagementDtoAssetMoveAssetMoveCreateDto {
  assetId?: number;
  assetMoveTypeId?: SDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType;
  /** @nullable */
  fromProjectId?: number | null;
  /** @nullable */
  fromUnitId?: number | null;
  /** @nullable */
  fromZoneId?: number | null;
  toProjectId?: number;
  /** @nullable */
  toUnitId?: number | null;
  /** @nullable */
  toZoneId?: number | null;
  /** @nullable */
  dateOfMoving?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  liquidationDate?: string | null;
  /** @nullable */
  isCurrent?: boolean | null;
}
