/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationRemindersDtoReminderInputDto } from './sDJCRMApplicationRemindersDtoReminderInputDto';

export interface SDJCRMApplicationAssetManagementDtoAssetInputDto {
  /** @nullable */
  id?: number | null;
  /**
     * @minLength 0
     * @maxLength 50
     * @nullable
     */
  laReferenceNumber?: string | null;
  /**
     * @minLength 0
     * @maxLength 255
     */
  assetName: string;
  /** @nullable */
  providerId?: number | null;
  assetTypeLv1Id: number;
  /** @nullable */
  assetTypeLv2Id?: number | null;
  /**
     * @minLength 0
     * @maxLength 50
     * @nullable
     */
  assetCode?: string | null;
  purchasedDate?: string;
  value?: number;
  warrantDate?: string;
  /** @nullable */
  model?: string | null;
  /** @nullable */
  description?: string | null;
  projectId?: number;
  /** @nullable */
  unitId?: number | null;
  /** @nullable */
  zoneId?: number | null;
  isOriginalPlace?: boolean;
  /** @nullable */
  liquidationDate?: string | null;
  reminder?: SDJCRMApplicationRemindersDtoReminderInputDto;
  /** @nullable */
  assetTypeAttributeIds?: number[] | null;
}
