/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationProviderDtoProviderOutputDto } from './sDJCRMApplicationProviderDtoProviderOutputDto';

export interface SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailOutputDto {
  id?: number;
  methodAndQuotationId?: number;
  serviceProviderId?: number;
  serviceProvider?: SDJCRMApplicationProviderDtoProviderOutputDto;
  repairingCost?: number;
  warrantyPeriodId?: number;
  isSelected?: boolean;
}
