/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationRolesDtoCreateRoleDto {
  /**
     * @minLength 0
     * @maxLength 32
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 64
     */
  displayName: string;
  /** @nullable */
  normalizedName?: string | null;
  /**
     * @minLength 0
     * @maxLength 5000
     * @nullable
     */
  description?: string | null;
  /** @nullable */
  grantedPermissions?: string[] | null;
}
