/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';
import type { SDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition } from './sDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition';

export interface SDJCRMApplicationLADtoLeaseAgreementUserInchargeOutputDto {
  id?: number;
  leaseAgreementId?: number;
  userId?: number;
  user?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  positionId?: SDJCRMCoreLeaseAgreementsLeaseAgreementConstantPosition;
  isActive?: boolean;
}
