/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreUsersDtoWarningInformationDto } from './sDJCRMCoreUsersDtoWarningInformationDto';

export interface SDJCRMApplicationSessionsDtoUserLoginInfoDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  surname?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  emailAddress?: string | null;
  /**
     * @minLength 0
     * @maxLength 256
     */
  displayName: string;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  gender?: boolean | null;
  /** @nullable */
  birthDate?: string | null;
  /** @nullable */
  passport?: string | null;
  /**
     * @minLength 0
     * @maxLength 64
     * @nullable
     */
  identityNumber?: string | null;
  userInfo?: SDJCRMCoreUsersDtoWarningInformationDto;
}
