/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreLocalizationDtoLocalizationDto } from './sDJCRMCoreLocalizationDtoLocalizationDto';

export interface SDJCRMApplicationConfigurationDtoTermAndConditionEditOutputDto {
  subjectId?: string;
  contentId?: string;
  /** @nullable */
  subject?: SDJCRMCoreLocalizationDtoLocalizationDto[] | null;
  /** @nullable */
  content?: SDJCRMCoreLocalizationDtoLocalizationDto[] | null;
}
