/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationNotificationsDtoNotificationSubscriptionDto } from './sDJCRMApplicationNotificationsDtoNotificationSubscriptionDto';

export interface SDJCRMApplicationNotificationsDtoUpdateNotificationSettingsInput {
  receiveNotifications?: boolean;
  receiveInAppNotifications?: boolean;
  receiveEmailNotifications?: boolean;
  /** @nullable */
  notifications?: SDJCRMApplicationNotificationsDtoNotificationSubscriptionDto[] | null;
}
