/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLADtoLeaseAgreementDetailsInputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  leaseAgreementId?: number;
  uniqueId?: string;
  /** @nullable */
  parentId?: string | null;
  feeTypeId?: number;
  /** @nullable */
  amount?: number | null;
  /** @nullable */
  vatPecent?: number | null;
  /** @nullable */
  vatAmount?: number | null;
  /** @nullable */
  totalAmount?: number | null;
  /** @nullable */
  totalAmountIncludeVat?: number | null;
  /** @nullable */
  rentNotVatUsd?: number | null;
  /** @nullable */
  amountIncludeVAT?: number | null;
  /** @nullable */
  rentOnly?: number | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
}
