/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreProjectsGrade } from './sDJCRMCoreProjectsGrade';
import type { SDJCRMCoreProjectsProject } from './sDJCRMCoreProjectsProject';

export interface SDJCRMCoreProjectsProjectGradeMap {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  projectId?: number;
  gradeId?: number;
  project?: SDJCRMCoreProjectsProject;
  grade?: SDJCRMCoreProjectsGrade;
}
