/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedEnumsModule } from './sDJCRMCoreSharedEnumsModule';

export interface SDJCRMApplicationConversationsDtoChatMessageCreateDto {
  id?: number;
  conversationUniqueId?: string;
  /** @nullable */
  content?: string | null;
  isPrivate?: boolean;
  moduleId?: SDJCRMCoreSharedEnumsModule;
}
