/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCategoryIndustryOutputDto } from './sDJCRMApplicationCategoryIndustryOutputDto';
import type { SDJCRMApplicationCompanyCompanyAddressCompanyAddressOutputDto } from './sDJCRMApplicationCompanyCompanyAddressCompanyAddressOutputDto';
import type { SDJCRMApplicationCompanyCompanyOrganizationUnitCompanyOrganizationUnitOutputDto } from './sDJCRMApplicationCompanyCompanyOrganizationUnitCompanyOrganizationUnitOutputDto';
import type { SDJCRMApplicationCompanyCompanyPhoneCompanyPhoneOutputDto } from './sDJCRMApplicationCompanyCompanyPhoneCompanyPhoneOutputDto';
import type { SDJCRMApplicationCompanyCompanyTypeMapCompanyTypeMapOutputDto } from './sDJCRMApplicationCompanyCompanyTypeMapCompanyTypeMapOutputDto';
import type { SDJCRMApplicationCompanyCompanyUserCompanyUserOutputDto } from './sDJCRMApplicationCompanyCompanyUserCompanyUserOutputDto';
import type { SDJCRMApplicationCompanyDtoCompanySimpleOutputDto } from './sDJCRMApplicationCompanyDtoCompanySimpleOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';

export interface SDJCRMApplicationCompanyDtoCompanyOutputDto {
  id?: number;
  uniqueId?: string;
  /** @nullable */
  parentId?: number | null;
  parent?: SDJCRMApplicationCompanyDtoCompanySimpleOutputDto;
  /** @nullable */
  legalName?: string | null;
  /** @nullable */
  legalNameVi?: string | null;
  /** @nullable */
  businessName?: string | null;
  /** @nullable */
  vatCode?: string | null;
  /** @nullable */
  industryId?: number | null;
  industry?: SDJCRMApplicationCategoryIndustryOutputDto;
  /** @nullable */
  industryLevel2Id?: number | null;
  industryLevel2?: SDJCRMApplicationCategoryIndustryOutputDto;
  /** @nullable */
  nationalityId?: number | null;
  /** @nullable */
  nationalityName?: string | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  bankNumber?: string | null;
  /** @nullable */
  bankAccountName?: string | null;
  /** @nullable */
  bankBranch?: string | null;
  /** @nullable */
  swiftCode?: string | null;
  /** @nullable */
  bankAddress?: string | null;
  isActive?: boolean;
  numOfInquiry?: number;
  numOfLA?: number;
  laValue?: number;
  /** @nullable */
  licenseNumber?: string | null;
  /** @nullable */
  licenseNumberVi?: string | null;
  /** @nullable */
  licenseIssued?: string | null;
  /** @nullable */
  licenseIssuedVi?: string | null;
  /** @nullable */
  licenseIssuedDate?: string | null;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  positionVi?: string | null;
  /** @nullable */
  certificate?: string | null;
  /** @nullable */
  certificateVi?: string | null;
  /** @nullable */
  representative?: string | null;
  /** @nullable */
  representativeVi?: string | null;
  creationTime?: string;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  /** @nullable */
  companyPhone?: SDJCRMApplicationCompanyCompanyPhoneCompanyPhoneOutputDto[] | null;
  /** @nullable */
  companyAddress?: SDJCRMApplicationCompanyCompanyAddressCompanyAddressOutputDto[] | null;
  /** @nullable */
  companyTypeMap?: SDJCRMApplicationCompanyCompanyTypeMapCompanyTypeMapOutputDto[] | null;
  /** @nullable */
  companyUser?: SDJCRMApplicationCompanyCompanyUserCompanyUserOutputDto[] | null;
  /** @nullable */
  companyOrganizationUnit?: SDJCRMApplicationCompanyCompanyOrganizationUnitCompanyOrganizationUnitOutputDto[] | null;
}
