/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationTemplateManagementDtoNotificationTemplateInputDto } from './sDJCRMApplicationTemplateManagementDtoNotificationTemplateInputDto';

export interface SDJCRMApplicationTemplateManagementDtoNotificationTemplateMapInputDto {
  id?: number;
  notificationTypeId?: number;
  notificationMethod?: number;
  /** @nullable */
  projectId?: number | null;
  isActive?: boolean;
  /** @nullable */
  notificationTemplates?: SDJCRMApplicationTemplateManagementDtoNotificationTemplateInputDto[] | null;
}
