/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCompanyDtoCompanySimpleOutputDto } from './sDJCRMApplicationCompanyDtoCompanySimpleOutputDto';
import type { SDJCRMApplicationContactDtoContactSimpleOutputDto } from './sDJCRMApplicationContactDtoContactSimpleOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';

export interface SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto {
  id?: number;
  /** @nullable */
  inquiryName?: string | null;
  /** @nullable */
  companyId?: number | null;
  company?: SDJCRMApplicationCompanyDtoCompanySimpleOutputDto;
  contactId?: number;
  contact?: SDJCRMApplicationContactDtoContactSimpleOutputDto;
  /** @nullable */
  moveInDate?: string | null;
  leaseTerm?: number;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
}
