/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseOutputDto } from './sDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseOutputDto';
import type { SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionUserOutputDto } from './sDJCRMApplicationLADtoCommissionLeaseAgreementCommissionUserOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto';
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';

export interface SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionMasterOutputDto {
  id?: number;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto;
  dealerCommissionAmount?: number;
  dealerPercent?: number;
  departmentCommissionAmount?: number;
  departmentPercent?: number;
  isManual?: boolean;
  /** @nullable */
  leaseAgreementCommissionPhase?: SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseOutputDto[] | null;
  /** @nullable */
  leaseAgreementCommissionUser?: SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionUserOutputDto[] | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
