/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationTemplateManagementDtoNotificationTemplateInputDto {
  /** @nullable */
  languageName?: string | null;
  /** @nullable */
  templateName?: string | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  templateContent?: string | null;
  /** @nullable */
  groupType?: number | null;
}
