/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSettingDtoFeeTypeOutputDto } from './sDJCRMCoreSettingDtoFeeTypeOutputDto';

export interface SDJCRMApplicationLADtoLeaseAgreementDiscountOutputDto {
  id?: number;
  leaseAgreementId?: number;
  /** @nullable */
  name?: string | null;
  feeTypeId?: number;
  feeType?: SDJCRMCoreSettingDtoFeeTypeOutputDto;
  rentIncludeVat?: number;
  rentExcludeVat?: number;
  discountPercent?: number;
  /** @nullable */
  discountIncludeVatPerMonth?: number | null;
  /** @nullable */
  discountExcludeVatPerMonth?: number | null;
  /** @nullable */
  contractRentAfterDiscountIncludeVat?: number | null;
  /** @nullable */
  contractRentAfterDiscountExcludeVat?: number | null;
  /** @nullable */
  discountAmountIncludeVat?: number | null;
  /** @nullable */
  discountAmountExcludeVat?: number | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
}
