/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreInquiriesInquiryConstantsActivityType = typeof SDJCRMCoreInquiriesInquiryConstantsActivityType[keyof typeof SDJCRMCoreInquiriesInquiryConstantsActivityType];


export const SDJCRMCoreInquiriesInquiryConstantsActivityType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
} as const;
