/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreProjectsUnitFacility } from './sDJCRMCoreProjectsUnitFacility';
import type { SDJCRMCoreUnitUnit } from './sDJCRMCoreUnitUnit';

export interface SDJCRMCoreUnitUnitFacilityMap {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  unitId?: number;
  unitFacilityId?: number;
  isActive?: boolean;
  unit?: SDJCRMCoreUnitUnit;
  unitFacility?: SDJCRMCoreProjectsUnitFacility;
}
