/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUsersUserBaseDtoResetPasswordDto {
  /** @minLength 1 */
  adminPassword: string;
  userId: number;
  /** @minLength 1 */
  newPassword: string;
}
