/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationCompanyCompanyTypeMapCompanyTypeMapOutputDto {
  id?: number;
  companyId?: number;
  companyTypeId?: number;
  /** @nullable */
  companyTypeName?: string | null;
  /** @nullable */
  isActive?: boolean | null;
}
