/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationContactDtoPagedExportCompanyResultRequestDto {
  /** @nullable */
  roleId?: number | null;
  /** @nullable */
  keyword?: string | null;
  /** @nullable */
  isActive?: boolean | null;
  /** @nullable */
  organizationUnitId?: number | null;
  /** @nullable */
  userIds?: number[] | null;
  /** @nullable */
  industryId?: number | null;
  /** @nullable */
  countryId?: number | null;
  /** @nullable */
  provinceId?: number | null;
  /** @nullable */
  districtId?: number | null;
  /** @nullable */
  nationalityId?: number | null;
  /** @nullable */
  fromDate?: string | null;
  /** @nullable */
  toDate?: string | null;
}
