/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectConfigurationDtoDefectConfigurationOutputDto } from './sDJCRMApplicationDefectDefectConfigurationDtoDefectConfigurationOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';
import type { SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum } from './sDJCRMCoreSharedEnumsDefectConfigurationTypeEnum';

export interface SDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  color?: string | null;
  /** @nullable */
  backgroundColor?: string | null;
  /** @nullable */
  order?: number | null;
  defectConfigurationType?: SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum;
  /** @nullable */
  defectPriorityConfigurations?: SDJCRMApplicationDefectDefectConfigurationDtoDefectConfigurationOutputDto[] | null;
  count?: number;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
}
