/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreAuditLogDtoAuditLogItemOutput {
  changeTime?: string;
  /** @nullable */
  propertyName?: string | null;
  /** @nullable */
  originalValue?: string | null;
  /** @nullable */
  newValue?: string | null;
  /** @nullable */
  newValueDisplay?: string | null;
  /** @nullable */
  originalValueDisplay?: string | null;
}
