/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationInquiriesDtoInquiryProposalInputDto {
  id?: number;
  inquiryId?: number;
  /** @nullable */
  proposalType?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  proposalDate?: string | null;
  /** @nullable */
  description?: string | null;
  templateId?: number;
  /** @nullable */
  contentBefore?: string | null;
  /** @nullable */
  contentAfter?: string | null;
  linkView?: number;
  /** @nullable */
  unitIds?: number[] | null;
  /** @nullable */
  projectIds?: number[] | null;
}
