/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectConfigurationDtoDefectConfigurationSimpleInputDto } from './sDJCRMApplicationDefectDefectConfigurationDtoDefectConfigurationSimpleInputDto';

export interface SDJCRMApplicationDefectDefectConfigurationDtoDefectConfigurationInputDto {
  defectPriorityId: number;
  /** @nullable */
  items?: SDJCRMApplicationDefectDefectConfigurationDtoDefectConfigurationSimpleInputDto[] | null;
}
