/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto } from './sDJCRMApplicationInquiriesDtoInquirySimpleOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';
import type { SDJCRMCoreSharedDocumentsDtoDocumentOutput } from './sDJCRMCoreSharedDocumentsDtoDocumentOutput';

export interface SDJCRMApplicationInquiriesDtoInquiryMailOutputDto {
  id?: number;
  inquiryId?: number;
  uniqueId?: string;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  sendDate?: string | null;
  /** @nullable */
  description?: string | null;
  file?: SDJCRMCoreSharedDocumentsDtoDocumentOutput;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  inquiry?: SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto;
}
