/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreSharedOrganizationUnitDtoOrganizationUnitDto {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  displayName?: string | null;
  memberCount?: number;
  isHead?: boolean;
}
