/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAreaProvince } from './sDJCRMCoreAreaProvince';

export interface SDJCRMCoreAreaCountry {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  countryName?: string | null;
  /** @nullable */
  phoneCode?: string | null;
  /** @nullable */
  nationalityName?: string | null;
  isActive?: boolean;
  /** @nullable */
  provinces?: SDJCRMCoreAreaProvince[] | null;
}
