/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeAttributeInputDto {
  /** @nullable */
  id?: number | null;
  /**
     * @minLength 0
     * @maxLength 200
     */
  name: string;
  assetTypeLv1Id: number;
  /** @nullable */
  assetTypeLv2Id?: number | null;
}
