/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMApplicationAuthorizationAccountsDtoUserAvailabilityState = typeof SDJCRMApplicationAuthorizationAccountsDtoUserAvailabilityState[keyof typeof SDJCRMApplicationAuthorizationAccountsDtoUserAvailabilityState];


export const SDJCRMApplicationAuthorizationAccountsDtoUserAvailabilityState = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
