/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMWebCoreAuthenticationExternalAuthenticateModel {
  /**
     * @minLength 0
     * @maxLength 256
     */
  userNameOrEmailAddress: string;
  /**
     * @minLength 0
     * @maxLength 32
     */
  password: string;
  rememberClient?: boolean;
  /** @nullable */
  returnUrl?: string | null;
  /** @nullable */
  singleSignIn?: boolean | null;
}
