/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';
import type { SDJCRMApplicationProjectProjectConstantProjectUserRole } from './sDJCRMApplicationProjectProjectConstantProjectUserRole';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationInquiriesDtoProjectUserOutputDto {
  id?: number;
  projectId?: number;
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  userId?: number;
  user?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  typeId?: SDJCRMApplicationProjectProjectConstantProjectUserRole;
  isActive?: boolean;
}
