/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentScheduleDetails } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentScheduleDetails';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentScheduleStatus } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentScheduleStatus';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentSchedule {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement;
  /** @nullable */
  name?: string | null;
  amount?: number;
  startDate?: string;
  endDate?: string;
  dueDate?: string;
  statusId?: number;
  status?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentScheduleStatus;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
  /** @nullable */
  leaseAgreementPaymentScheduleDetails?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentScheduleDetails[] | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
