/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreSettingEntitiesFeeType } from './sDJCRMCoreSettingEntitiesFeeType';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementDiscount {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementId?: number;
  /** @nullable */
  name?: string | null;
  feeTypeId?: number;
  feeType?: SDJCRMCoreSettingEntitiesFeeType;
  /** @nullable */
  rentIncludeVat?: number | null;
  /** @nullable */
  rentExcludeVat?: number | null;
  discountPercent?: number;
  /** @nullable */
  discountIncludeVatPerMonth?: number | null;
  /** @nullable */
  discountExcludeVatPerMonth?: number | null;
  /** @nullable */
  contractRentAfterDiscountIncludeVat?: number | null;
  /** @nullable */
  contractRentAfterDiscountExcludeVat?: number | null;
  /** @nullable */
  discountAmountIncludeVat?: number | null;
  /** @nullable */
  discountAmountExcludeVat?: number | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
