/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedEnumsDefectTabsEnum } from './sDJCRMCoreSharedEnumsDefectTabsEnum';

export interface SDJCRMApplicationDefectDefectManagementDtoCompleteTabInputDto {
  defectId: number;
  tab: SDJCRMCoreSharedEnumsDefectTabsEnum;
}
