/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';

export interface SDJCRMApplicationUsersEmployeesDtoEmployeeProjectRoleDto {
  userId?: number;
  projectId?: number;
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
}
