/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType = typeof SDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType[keyof typeof SDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType];


export const SDJCRMApplicationAssetManagementAssetConstantPageFilterAssetType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
