/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLocalizationDtoApplicationLanguageEditDto {
  /** @nullable */
  id?: number | null;
  /**
     * @minLength 0
     * @maxLength 128
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 128
     * @nullable
     */
  icon?: string | null;
  isEnabled?: boolean;
}
