/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAuthorizationProfileDtoUpdateProfilePictureInput {
  /**
     * @minLength 1
     * @maxLength 400
     */
  fileToken: string;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  userId?: number;
}
