/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedDocumentsDtoDocumentOutput } from './sDJCRMCoreSharedDocumentsDtoDocumentOutput';

export interface SDJCRMApplicationHomeDtoUserSettingOutputDto {
  /** @nullable */
  homeSlides?: SDJCRMCoreSharedDocumentsDtoDocumentOutput[] | null;
}
