/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreSharedContractContractConstantsContractType = typeof SDJCRMCoreSharedContractContractConstantsContractType[keyof typeof SDJCRMCoreSharedContractContractConstantsContractType];


export const SDJCRMCoreSharedContractContractConstantsContractType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
