/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationContractProviderContractDtoProviderContractPaidInputDto {
  /** @nullable */
  order?: number | null;
  /**
     * @minLength 0
     * @maxLength 250
     */
  description: string;
  amount: number;
  paymentDate: string;
}
