/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationTemplateManagementDtoValueOutput } from './sDJCRMApplicationTemplateManagementDtoValueOutput';

export interface SDJCRMApplicationTemplateManagementDtoNotificationTemplateOutput {
  id?: number;
  /** @nullable */
  languageName?: string | null;
  /** @nullable */
  templateName?: string | null;
  /** @nullable */
  moduleId?: number | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  templateContent?: string | null;
  /** @nullable */
  groupType?: number | null;
  isActive?: boolean;
  creationTime?: string;
  module?: SDJCRMApplicationTemplateManagementDtoValueOutput;
}
