/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreSharedOrganizationUnitDtoMoveOrganizationUnitInput {
  /** @minimum 1 */
  id?: number;
  /** @nullable */
  newParentId?: number | null;
}
