/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUnitDtoDashboardUnitType } from './sDJCRMApplicationUnitDtoDashboardUnitType';

export interface SDJCRMApplicationFloorDtoFloorOutputDto {
  id?: number;
  projectId?: number;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  floorName?: string | null;
  numberOfUnits?: number;
  /** @nullable */
  size?: number | null;
  /** @nullable */
  order?: number | null;
  isActive?: boolean;
  /** @nullable */
  countUnitType?: SDJCRMApplicationUnitDtoDashboardUnitType[] | null;
}
