/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAreaCountry } from './sDJCRMCoreAreaCountry';
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreCompanyEntitiesCompany as __SDJCRMCoreCompanyEntitiesCompany } from './sDJCRMCoreCompanyEntitiesCompany';
import type { SDJCRMCoreCompanyEntitiesCompanyAddress } from './sDJCRMCoreCompanyEntitiesCompanyAddress';
import type { SDJCRMCoreCompanyEntitiesCompanyOrganizationUnit } from './sDJCRMCoreCompanyEntitiesCompanyOrganizationUnit';
import type { SDJCRMCoreCompanyEntitiesCompanyPhone } from './sDJCRMCoreCompanyEntitiesCompanyPhone';
import type { SDJCRMCoreCompanyEntitiesCompanyTypeMap } from './sDJCRMCoreCompanyEntitiesCompanyTypeMap';
import type { SDJCRMCoreCompanyEntitiesCompanyUser } from './sDJCRMCoreCompanyEntitiesCompanyUser';
import type { SDJCRMCoreCompanyEntitiesIndustry } from './sDJCRMCoreCompanyEntitiesIndustry';

export interface SDJCRMCoreCompanyEntitiesCompany {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  tenantId?: number;
  /** @nullable */
  parentId?: number | null;
  uniqueId?: string;
  parent?: __SDJCRMCoreCompanyEntitiesCompany;
  /** @nullable */
  legalName?: string | null;
  /** @nullable */
  legalNameVi?: string | null;
  /** @nullable */
  businessName?: string | null;
  /** @nullable */
  vatCode?: string | null;
  /** @nullable */
  industryId?: number | null;
  industry?: SDJCRMCoreCompanyEntitiesIndustry;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  nationalityId?: number | null;
  nationality?: SDJCRMCoreAreaCountry;
  /** @nullable */
  industryLevel2Id?: number | null;
  industryLevel2?: SDJCRMCoreCompanyEntitiesIndustry;
  /** @nullable */
  bankNumber?: string | null;
  /** @nullable */
  bankAccountName?: string | null;
  /** @nullable */
  bankBranch?: string | null;
  /** @nullable */
  swiftCode?: string | null;
  /** @nullable */
  bankAddress?: string | null;
  /** @nullable */
  licenseNumber?: string | null;
  /** @nullable */
  licenseNumberVi?: string | null;
  /** @nullable */
  licenseIssued?: string | null;
  /** @nullable */
  licenseIssuedVi?: string | null;
  /** @nullable */
  licenseIssuedDate?: string | null;
  /** @nullable */
  certificate?: string | null;
  /** @nullable */
  certificateVi?: string | null;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  positionVi?: string | null;
  /** @nullable */
  representative?: string | null;
  /** @nullable */
  representativeVi?: string | null;
  isActive?: boolean;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
  /** @nullable */
  companyUser?: SDJCRMCoreCompanyEntitiesCompanyUser[] | null;
  /** @nullable */
  companyOrganizationUnit?: SDJCRMCoreCompanyEntitiesCompanyOrganizationUnit[] | null;
  /** @nullable */
  companyTypeMap?: SDJCRMCoreCompanyEntitiesCompanyTypeMap[] | null;
  /** @nullable */
  companyPhone?: SDJCRMCoreCompanyEntitiesCompanyPhone[] | null;
  /** @nullable */
  companyAddress?: SDJCRMCoreCompanyEntitiesCompanyAddress[] | null;
}
