/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLocalizationDtoApplicationLanguageListDto } from './sDJCRMApplicationLocalizationDtoApplicationLanguageListDto';

export interface SDJCRMApplicationLocalizationDtoGetLanguagesOutput {
  /** @nullable */
  items?: SDJCRMApplicationLocalizationDtoApplicationLanguageListDto[] | null;
  /** @nullable */
  defaultLanguageName?: string | null;
}
