/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedOrganizationUnitOrganizationUnitOutputDto } from './sDJCRMCoreSharedOrganizationUnitOrganizationUnitOutputDto';

export interface SDJCRMApplicationInquiriesDtoInquiryOrganizationUnitOutputDto {
  id?: number;
  inquiryId?: number;
  organizationUnitId?: number;
  organizationUnit?: SDJCRMCoreSharedOrganizationUnitOrganizationUnitOutputDto;
  isActive?: boolean;
}
