/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUnitHandoverDtoAssetCreateOrUpdateInputDto {
  id?: number;
  assetId?: number;
  isUsed?: boolean;
  value?: number;
}
