/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto } from './sDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto';
import type { SDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto } from './sDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto';
import type { SDJCRMApplicationDefectDefectConfigurationDtoDefectStageOutputDto } from './sDJCRMApplicationDefectDefectConfigurationDtoDefectStageOutputDto';
import type { SDJCRMApplicationDefectDefectManagementDtoDefectStatusOutputDto } from './sDJCRMApplicationDefectDefectManagementDtoDefectStatusOutputDto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';
import type { SDJCRMApplicationProviderDtoProviderOutputDto } from './sDJCRMApplicationProviderDtoProviderOutputDto';
import type { SDJCRMApplicationUnitDtoSimpleUnitOutputDto } from './sDJCRMApplicationUnitDtoSimpleUnitOutputDto';
import type { SDJCRMApplicationZoneDtoZoneOutputDto } from './sDJCRMApplicationZoneDtoZoneOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';
import type { SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum } from './sDJCRMCoreSharedEnumsDefectConfigurationTypeEnum';
import type { SDJCRMCoreSharedEnumsDefectTabsEnum } from './sDJCRMCoreSharedEnumsDefectTabsEnum';

export interface SDJCRMApplicationDefectDefectManagementDtoDefectInfoOutputDto {
  id?: number;
  /** @nullable */
  parentId?: number | null;
  defectCategoryId?: number;
  defectCategory?: SDJCRMApplicationDefectDefectCategoryDtoDefectCategoryOutputDto;
  currentStageId?: number;
  currentStage?: SDJCRMApplicationDefectDefectConfigurationDtoDefectStageOutputDto;
  currentStatusId?: number;
  currentStatus?: SDJCRMApplicationDefectDefectManagementDtoDefectStatusOutputDto;
  currentTab?: SDJCRMCoreSharedEnumsDefectTabsEnum;
  defectConfigurationType?: SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum;
  projectId?: number;
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  /** @nullable */
  zoneId?: number | null;
  zone?: SDJCRMApplicationZoneDtoZoneOutputDto;
  /** @nullable */
  unitId?: number | null;
  unit?: SDJCRMApplicationUnitDtoSimpleUnitOutputDto;
  defectPriorityId?: number;
  defectPriority?: SDJCRMApplicationDefectDefectConfigurationDtoDefectPriorityOutputDto;
  /** @nullable */
  createdDate?: string | null;
  /** @nullable */
  estimateEndDate?: string | null;
  /** @nullable */
  description?: string | null;
  uniqueId?: string;
  /** @nullable */
  serviceProviderId?: number | null;
  serviceProvider?: SDJCRMApplicationProviderDtoProviderOutputDto;
  /** @nullable */
  repairingCost?: number | null;
  /** @nullable */
  warrantyExpDate?: string | null;
  isReturned?: boolean;
  isOverdue?: boolean;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  /** @nullable */
  children?: SDJCRMApplicationDefectDefectManagementDtoDefectInfoOutputDto[] | null;
  /** @nullable */
  isInspectionDelay?: boolean | null;
  /** @nullable */
  isMethodAndQuotationDelay?: boolean | null;
  /** @nullable */
  isWorkScheduleDelay?: boolean | null;
  /** @nullable */
  isHandoverDelay?: boolean | null;
  /** @nullable */
  picIds?: number[] | null;
  /** @nullable */
  pics?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto[] | null;
}
