/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersCustomersDtoCustomerDepositInputDto } from './sDJCRMApplicationUsersCustomersDtoCustomerDepositInputDto';

export interface SDJCRMApplicationUsersCustomersDtoCustomerCreateDto {
  /**
     * @minLength 0
     * @maxLength 256
     */
  emailAddress: string;
  /**
     * @minLength 0
     * @maxLength 32
     * @nullable
     */
  password?: string | null;
  isActive?: boolean;
  phoneNumber: string;
  /** @nullable */
  birthDate?: string | null;
  /** @nullable */
  gender?: boolean | null;
  /**
     * @minLength 0
     * @maxLength 256
     */
  displayName: string;
  /**
     * @minLength 0
     * @maxLength 64
     * @nullable
     */
  passport?: string | null;
  /**
     * @minLength 0
     * @maxLength 64
     * @nullable
     */
  identityNumber?: string | null;
  setRandomPassword?: boolean;
  /** @nullable */
  roleNames?: string[] | null;
  customerDeposit?: SDJCRMApplicationUsersCustomersDtoCustomerDepositInputDto;
}
