/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUnitDtoSimpleUnitOutputDto } from './sDJCRMApplicationUnitDtoSimpleUnitOutputDto';

export interface SDJCRMApplicationInquiriesDtoInquiryProposalUnitOutputDto {
  id?: number;
  proposalId?: number;
  unitId?: number;
  unit?: SDJCRMApplicationUnitDtoSimpleUnitOutputDto;
}
