/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationProviderDtoProviderOutputDto {
  id?: number;
  /** @nullable */
  contractValue?: number | null;
  /** @nullable */
  totalPaid?: number | null;
  totalCurrentContract?: number;
  uniqueId?: string;
  /** @nullable */
  typeId?: number | null;
  /** @nullable */
  typeName?: string | null;
  /** @nullable */
  taxCode?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  legalName?: string | null;
  /** @nullable */
  primaryPhone?: string | null;
  /** @nullable */
  primaryEmail?: string | null;
  /** @nullable */
  primaryAddress?: string | null;
  /** @nullable */
  secondaryPhone?: string | null;
  /** @nullable */
  secondaryEmail?: string | null;
  /** @nullable */
  secondaryAddress?: string | null;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
}
