/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreCompanyEntitiesOtherCategory } from './sDJCRMCoreCompanyEntitiesOtherCategory';

export interface SDJCRMApplicationContactContactPhoneContactPhoneOutputDto {
  /** @nullable */
  id?: number | null;
  contactId?: number;
  /** @nullable */
  phoneCode?: string | null;
  /** @nullable */
  isPrimary?: boolean | null;
  /** @nullable */
  phoneTypeId?: number | null;
  /** @nullable */
  phoneTypeName?: string | null;
  phoneType?: SDJCRMCoreCompanyEntitiesOtherCategory;
  /** @nullable */
  countryId?: number | null;
  /** @nullable */
  phone?: string | null;
  isActive?: boolean;
}
