/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailInputDto } from './sDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailInputDto';

export interface SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationInputDto {
  id?: number;
  /** @nullable */
  standardizedEndDate?: string | null;
  /** @nullable */
  actualStartDate?: string | null;
  /** @nullable */
  receivedDate?: string | null;
  /** @nullable */
  approvalDate?: string | null;
  /**
     * @minLength 0
     * @maxLength 5000
     * @nullable
     */
  description?: string | null;
  /** @nullable */
  willReturn?: boolean | null;
  /** @nullable */
  isSendEmail?: boolean | null;
  /** @nullable */
  isApply?: boolean | null;
  /** @nullable */
  methodAndQuotationWorkDetails?: SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailInputDto[] | null;
}
