/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreContactsEntitiesContact } from './sDJCRMCoreContactsEntitiesContact';

export interface SDJCRMCoreContactsEntitiesContactUser {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  contactId?: number;
  contact?: SDJCRMCoreContactsEntitiesContact;
  isRequest?: boolean;
  userId?: number;
  user?: SDJCRMCoreAuthorizationUsersUser;
  /** @nullable */
  requestNote?: string | null;
  isActive?: boolean;
}
