/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationCompanyCompanyPhoneCompanyPhoneInputDto {
  id?: number;
  companyId?: number;
  /** @nullable */
  phoneTypeId?: number | null;
  /** @nullable */
  phone?: string | null;
  isPrimary?: boolean;
  isActive?: boolean;
  /** @nullable */
  countryId?: number | null;
}
