/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';
import type { SDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType } from './sDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType';

export interface SDJCRMApplicationAssetManagementDtoAssetMoveAssetMoveOutputDto {
  id?: number;
  uniqueId?: string;
  assetId?: number;
  /** @nullable */
  assetName?: string | null;
  /** @nullable */
  assetCode?: string | null;
  assetMoveTypeId?: SDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType;
  dateOfMoving?: string;
  fromProjectId?: number;
  /** @nullable */
  fromProjectName?: string | null;
  /** @nullable */
  fromProjectCode?: string | null;
  /** @nullable */
  fromUnitId?: number | null;
  /** @nullable */
  fromUnitName?: string | null;
  /** @nullable */
  fromZoneId?: number | null;
  /** @nullable */
  fromZoneName?: string | null;
  toProjectId?: number;
  /** @nullable */
  toProjectName?: string | null;
  /** @nullable */
  toProjectCode?: string | null;
  /** @nullable */
  toUnitId?: number | null;
  /** @nullable */
  toUnitName?: string | null;
  /** @nullable */
  toZoneId?: number | null;
  /** @nullable */
  toZoneName?: string | null;
  movedQuantity?: number;
  /** @nullable */
  description?: string | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
}
