/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationAssetManagementDtoSimpleAssetOutputDto {
  id?: number;
  isAllowanced?: boolean;
  /** @nullable */
  laReferenceNumber?: string | null;
  value?: number;
  purchasedDate?: string;
  warrantDate?: string;
  /** @nullable */
  description?: string | null;
  uniqueId?: string;
  documentId?: string;
  /** @nullable */
  assetName?: string | null;
  /** @nullable */
  assetCode?: string | null;
  isActive?: boolean;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
}
