/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedOrganizationUnitDtoUsersHeadInputDto } from './sDJCRMCoreSharedOrganizationUnitDtoUsersHeadInputDto';

export interface SDJCRMCoreSharedOrganizationUnitDtoUsersHeadToOrganizationUnitInput {
  /** @nullable */
  listUsersHead?: SDJCRMCoreSharedOrganizationUnitDtoUsersHeadInputDto[] | null;
  /** @minimum 1 */
  organizationUnitId?: number;
}
