/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationContractContractDtoContractCategoryOutputDto } from './sDJCRMApplicationContractContractDtoContractCategoryOutputDto';
import type { SDJCRMApplicationContractProviderContractDtoProviderContractOutputDto as __SDJCRMApplicationContractProviderContractDtoProviderContractOutputDto } from './sDJCRMApplicationContractProviderContractDtoProviderContractOutputDto';
import type { SDJCRMApplicationContractProviderContractProviderContractPaidOutputDto } from './sDJCRMApplicationContractProviderContractProviderContractPaidOutputDto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';
import type { SDJCRMApplicationProviderDtoSimpleProviderOutputDto } from './sDJCRMApplicationProviderDtoSimpleProviderOutputDto';
import type { SDJCRMApplicationRemindersDtoReminderOutputDto } from './sDJCRMApplicationRemindersDtoReminderOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationContractProviderContractDtoProviderContractOutputDto {
  id?: number;
  /** @nullable */
  currentContractAmount?: number | null;
  uniqueId?: string;
  /** @nullable */
  projects?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto[] | null;
  company?: SDJCRMApplicationProviderDtoSimpleProviderOutputDto;
  /** @nullable */
  contractId?: string | null;
  /** @nullable */
  contractName?: string | null;
  contractCategory?: SDJCRMApplicationContractContractDtoContractCategoryOutputDto;
  contractTypeId?: number;
  contractParent?: __SDJCRMApplicationContractProviderContractDtoProviderContractOutputDto;
  /** @nullable */
  signDate?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  expiryDate?: string | null;
  /** @nullable */
  expireInDays?: number | null;
  contractPrice?: number;
  usage?: number;
  /** @nullable */
  contractValue?: number | null;
  tax?: number;
  /** @nullable */
  contractPaymentTerm?: string | null;
  /** @nullable */
  description?: string | null;
  reminder?: SDJCRMApplicationRemindersDtoReminderOutputDto;
  isActive?: boolean;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  creationTime?: string;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  providerContractPaids?: SDJCRMApplicationContractProviderContractProviderContractPaidOutputDto[] | null;
}
