/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeAttributeOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeAttributeOutputDto';
import type { SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';
import type { SDJCRMApplicationProviderDtoSimpleProviderOutputDto } from './sDJCRMApplicationProviderDtoSimpleProviderOutputDto';
import type { SDJCRMApplicationRemindersDtoReminderOutputDto } from './sDJCRMApplicationRemindersDtoReminderOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationAssetManagementDtoAssetDetailOutputDto {
  id?: number;
  isAllowanced?: boolean;
  /** @nullable */
  laReferenceNumber?: string | null;
  /** @nullable */
  assetName?: string | null;
  /** @nullable */
  assetCode?: string | null;
  purchasedDate?: string;
  value?: number;
  warrantDate?: string;
  /** @nullable */
  model?: string | null;
  /** @nullable */
  description?: string | null;
  uniqueId?: string;
  documentId?: string;
  isEdited?: boolean;
  isMoved?: boolean;
  isOriginalPlace?: boolean;
  assetTypeLv1?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto;
  assetTypeLv2?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto;
  /** @nullable */
  liquidationDate?: string | null;
  /** @nullable */
  isLiquidation?: boolean | null;
  beforeDays?: number;
  /** @nullable */
  existingPeriod?: string | null;
  isActive?: boolean;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  /** @nullable */
  assetAttributes?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeAttributeOutputDto[] | null;
  /** @nullable */
  unitId?: number | null;
  /** @nullable */
  unitName?: string | null;
  /** @nullable */
  zoneId?: number | null;
  /** @nullable */
  zoneName?: string | null;
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  provider?: SDJCRMApplicationProviderDtoSimpleProviderOutputDto;
  reminder?: SDJCRMApplicationRemindersDtoReminderOutputDto;
}
