/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationInquiriesDtoSimpleInquiryReservationOutputDto {
  id?: number;
  inquiryId?: number;
  /** @nullable */
  reservationTime?: string | null;
  /** @nullable */
  expiryDate?: string | null;
  /** @nullable */
  description?: string | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
}
