/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentSchedule } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentSchedule';
import type { SDJCRMCoreSettingEntitiesFeeType } from './sDJCRMCoreSettingEntitiesFeeType';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentScheduleDetails {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementPaymentScheduleId?: number;
  amountIncludeVAT?: number;
  vatAmount?: number;
  feeTypeId?: number;
  feType?: SDJCRMCoreSettingEntitiesFeeType;
  amount?: number;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
  leaseAgreementPaymentSchedule?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementPaymentSchedule;
}
