/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum } from './sDJCRMCoreSharedEnumsDefectConfigurationTypeEnum';

export interface SDJCRMApplicationDefectDefectManagementDtoDefectInfoInputDto {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  parentId?: number | null;
  defectCategoryId: number;
  defectPriorityId: number;
  defectConfigurationType: SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum;
  projectId: number;
  /** @nullable */
  zoneId?: number | null;
  /** @nullable */
  unitId?: number | null;
  priorityId: number;
  /** @nullable */
  createdDate?: string | null;
  /** @nullable */
  estimateEndDate?: string | null;
  /**
     * @minLength 0
     * @maxLength 5000
     * @nullable
     */
  description?: string | null;
  /** @nullable */
  picIds?: number[] | null;
}
