/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreSharedOrganizationUnitDtoCreateUpdateUserToOrganizationUnitInput {
  /** @nullable */
  userId?: number | null;
  isHead?: boolean;
  /** @minimum 1 */
  organizationUnitId?: number;
}
