/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseOutputDto } from './sDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionDetailsOutputDto {
  id?: number;
  leaseAgreementCommissionPhaseId?: number;
  leaseAgreementCommissionPhase?: SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseOutputDto;
  userId?: number;
  user?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  commissionAmount?: number;
  percent?: number;
}
