/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreProjectsFacing } from './sDJCRMCoreProjectsFacing';
import type { SDJCRMCoreProjectsFloor } from './sDJCRMCoreProjectsFloor';
import type { SDJCRMCoreProjectsProject } from './sDJCRMCoreProjectsProject';
import type { SDJCRMCoreProjectsPropertyType } from './sDJCRMCoreProjectsPropertyType';
import type { SDJCRMCoreProjectsUnitStatus } from './sDJCRMCoreProjectsUnitStatus';
import type { SDJCRMCoreProjectsUnitType } from './sDJCRMCoreProjectsUnitType';
import type { SDJCRMCoreUnitUnitAddress } from './sDJCRMCoreUnitUnitAddress';
import type { SDJCRMCoreUnitUnitFacilityMap } from './sDJCRMCoreUnitUnitFacilityMap';
import type { SDJCRMCoreUnitUnitViewMap } from './sDJCRMCoreUnitUnitViewMap';

export interface SDJCRMCoreUnitUnit {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  tenantId?: number;
  uniqueId?: string;
  /** @nullable */
  projectId?: number | null;
  project?: SDJCRMCoreProjectsProject;
  /** @nullable */
  floorId?: number | null;
  floor?: SDJCRMCoreProjectsFloor;
  /** @nullable */
  unitName?: string | null;
  /** @nullable */
  actualSize?: number | null;
  statusId?: number;
  status?: SDJCRMCoreProjectsUnitStatus;
  /** @nullable */
  description?: string | null;
  unitTypeId?: number;
  unitType?: SDJCRMCoreProjectsUnitType;
  productTypeId?: number;
  productType?: SDJCRMCoreProjectsPropertyType;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  monthly?: number | null;
  /** @nullable */
  per?: number | null;
  /** @nullable */
  order?: number | null;
  isActive?: boolean;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
  /** @nullable */
  askingRent?: number | null;
  /** @nullable */
  motobikePark?: number | null;
  /** @nullable */
  carPark?: number | null;
  /** @nullable */
  balcony?: number | null;
  /** @nullable */
  helperRoom?: number | null;
  /** @nullable */
  bedRoom?: number | null;
  /** @nullable */
  bathRoom?: number | null;
  /** @nullable */
  livingRoom?: number | null;
  /** @nullable */
  facingId?: number | null;
  facing?: SDJCRMCoreProjectsFacing;
  /** @nullable */
  saleAble?: number | null;
  /** @nullable */
  gross?: number | null;
  /** @nullable */
  isPet?: boolean | null;
  /** @nullable */
  unitAddress?: SDJCRMCoreUnitUnitAddress[] | null;
  /** @nullable */
  unitFacilityMap?: SDJCRMCoreUnitUnitFacilityMap[] | null;
  /** @nullable */
  unitViewMap?: SDJCRMCoreUnitUnitViewMap[] | null;
}
