/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationUnitDtoUnitStatusManagementUnitStatusManagementInputDto {
  /** @nullable */
  id?: number | null;
  unitId?: number;
  statusId?: number;
  startDate?: string;
  endDate?: string;
}
