/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryCallOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryCallOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryMailOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryMailOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryProposalOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryProposalOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryReservationOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryReservationOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquirySiteVisitOutputDto } from './sDJCRMApplicationInquiriesDtoInquirySiteVisitOutputDto';

export interface SDJCRMApplicationInquiriesDtoInquiryActivityOutputDto {
  inquiryMail?: SDJCRMApplicationInquiriesDtoInquiryMailOutputDto;
  inquiryCall?: SDJCRMApplicationInquiriesDtoInquiryCallOutputDto;
  inquirySiteVisit?: SDJCRMApplicationInquiriesDtoInquirySiteVisitOutputDto;
  inquiryReservation?: SDJCRMApplicationInquiriesDtoInquiryReservationOutputDto;
  inquiryProposal?: SDJCRMApplicationInquiriesDtoInquiryProposalOutputDto;
}
