/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationProjectDtoSimpleProjectOutputDto {
  id?: number;
  uniqueId?: string;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  projectCode?: string | null;
  amount?: number;
}
