/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationSessionsDtoChangeCurrentPhoneNumberDto {
  /** @minLength 1 */
  phoneNumber: string;
  /** @nullable */
  idToken?: string | null;
}
