/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailInputDto } from './sDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailInputDto';

export interface SDJCRMApplicationDefectDefectManagementDtoHandoverInputDto {
  id?: number;
  /** @nullable */
  handoverDate?: string | null;
  /** @nullable */
  actualDate?: string | null;
  /**
     * @minLength 0
     * @maxLength 5000
     * @nullable
     */
  description?: string | null;
  /** @nullable */
  methodAndQuotationWorkDetails?: SDJCRMApplicationDefectDefectManagementDtoMethodAndQuotationWorkDetailInputDto[] | null;
}
