/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationRolesDtoFlatPermissionDto } from './sDJCRMApplicationRolesDtoFlatPermissionDto';
import type { SDJCRMApplicationRolesDtoRoleEditDto } from './sDJCRMApplicationRolesDtoRoleEditDto';

export interface SDJCRMApplicationRolesDtoGetRoleForEditOutput {
  role?: SDJCRMApplicationRolesDtoRoleEditDto;
  /** @nullable */
  permissions?: SDJCRMApplicationRolesDtoFlatPermissionDto[] | null;
  /** @nullable */
  grantedPermissionNames?: string[] | null;
}
