/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMWebCoreAuthenticationExternalExternalLoginProviderInfoModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  clientId?: string | null;
}
