/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationPlanMaintenanceDtoPageFilterPlanMaintenanceExportDto {
  /** @nullable */
  keyword?: string | null;
  /** @nullable */
  projectIds?: number[] | null;
  /** @nullable */
  statusIds?: number[] | null;
  /** @nullable */
  zoneIds?: number[] | null;
  /** @nullable */
  assetIds?: number[] | null;
  /** @nullable */
  providerId?: number | null;
  /** @nullable */
  fromActualStartDate?: string | null;
  toActualStartDate?: string;
  /** @nullable */
  fromCreatedDate?: string | null;
  toCreatedDate?: string;
}
