/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationContactContactUserContactUserOutputDto {
  id?: number;
  contactId?: number;
  userId?: number;
  user?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  /** @nullable */
  requestNote?: string | null;
  /** @nullable */
  isRequest?: boolean | null;
  isActive?: boolean;
  /** @nullable */
  approvedDate?: string | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
}
