/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationConfigurationDtoChangeUiThemeInput {
  /**
     * @minLength 0
     * @maxLength 32
     */
  theme: string;
}
