/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreAuthorizationUsersUser } from './sDJCRMCoreAuthorizationUsersUser';
import type { SDJCRMCoreCompanyEntitiesCompany } from './sDJCRMCoreCompanyEntitiesCompany';
import type { SDJCRMCoreContactsEntitiesContact } from './sDJCRMCoreContactsEntitiesContact';
import type { SDJCRMCoreProjectsProjectAddress } from './sDJCRMCoreProjectsProjectAddress';
import type { SDJCRMCoreProjectsProjectFacilityMap } from './sDJCRMCoreProjectsProjectFacilityMap';
import type { SDJCRMCoreProjectsProjectGradeMap } from './sDJCRMCoreProjectsProjectGradeMap';
import type { SDJCRMCoreProjectsProjectTypeMap } from './sDJCRMCoreProjectsProjectTypeMap';

export interface SDJCRMCoreProjectsProject {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  tenantId?: number;
  uniqueId?: string;
  /** @nullable */
  projectCode?: string | null;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  projectManagerName?: string | null;
  /** @nullable */
  bankInfo?: string | null;
  /** @nullable */
  budgetCode?: string | null;
  /** @nullable */
  lessorAddress?: string | null;
  /** @nullable */
  lessorAddressVi?: string | null;
  /** @nullable */
  representativeOf?: string | null;
  /** @nullable */
  representativeOfVi?: string | null;
  /** @nullable */
  lessorPosition?: string | null;
  /** @nullable */
  lessorPositionVi?: string | null;
  /** @nullable */
  lessorCertificateName?: string | null;
  /** @nullable */
  lessorCertificateNameVi?: string | null;
  /** @nullable */
  lessorCertificateNumber?: string | null;
  /** @nullable */
  lessorCertificateNumberVi?: string | null;
  /** @nullable */
  lessorCertificateIssuedDate?: string | null;
  /** @nullable */
  lessorCertificateIssuedBy?: string | null;
  /** @nullable */
  lessorCertificateIssuedByVi?: string | null;
  /** @nullable */
  registerAddress?: string | null;
  /** @nullable */
  registerAddressVi?: string | null;
  /** @nullable */
  representativeBy?: string | null;
  /** @nullable */
  representativeByVi?: string | null;
  /** @nullable */
  representativePosition?: string | null;
  /** @nullable */
  representativePositionVi?: string | null;
  /** @nullable */
  representativeCertificateNumber?: string | null;
  /** @nullable */
  representativeCertificateNumberVi?: string | null;
  /** @nullable */
  representativeExecuteBy?: string | null;
  /** @nullable */
  representativeExecuteByVi?: string | null;
  /** @nullable */
  representativeCertificateEffectiveDate?: string | null;
  /** @nullable */
  bankAccount?: string | null;
  /** @nullable */
  bankName?: string | null;
  /** @nullable */
  bankNameVi?: string | null;
  /** @nullable */
  bankAddress?: string | null;
  /** @nullable */
  bankAddressVi?: string | null;
  /** @nullable */
  optionalBankAccount?: string | null;
  /** @nullable */
  optionalBankName?: string | null;
  /** @nullable */
  optionalBankNameVi?: string | null;
  /** @nullable */
  optionalBankAddress?: string | null;
  /** @nullable */
  optionalBankAddressVi?: string | null;
  /** @nullable */
  managingAgentCompany?: string | null;
  /** @nullable */
  managingAgentCompanyVi?: string | null;
  /** @nullable */
  holderOf?: string | null;
  /** @nullable */
  holderOfVi?: string | null;
  /** @nullable */
  managingAgentCertificateNumber?: string | null;
  /** @nullable */
  managingAgentCertificateNumberVi?: string | null;
  /** @nullable */
  managingAgentCertificateIssuedDate?: string | null;
  /** @nullable */
  managingAgentCertificateIssuedBy?: string | null;
  /** @nullable */
  managingAgentCertificateIssuedByVi?: string | null;
  /** @nullable */
  numberOfFloors?: number | null;
  /** @nullable */
  numberOfUnits?: number | null;
  /** @nullable */
  launchingTime?: string | null;
  /** @nullable */
  builtDate?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  yearRenovated?: string | null;
  isActive?: boolean;
  /** @nullable */
  outOfMarket?: boolean | null;
  /** @nullable */
  outOfDate?: string | null;
  /** @nullable */
  projectAddress?: SDJCRMCoreProjectsProjectAddress[] | null;
  /** @nullable */
  projectFacilityMap?: SDJCRMCoreProjectsProjectFacilityMap[] | null;
  /** @nullable */
  projectTypeMap?: SDJCRMCoreProjectsProjectTypeMap[] | null;
  /** @nullable */
  projectGradeMap?: SDJCRMCoreProjectsProjectGradeMap[] | null;
  /** @nullable */
  landlordId?: number | null;
  landlord?: SDJCRMCoreCompanyEntitiesCompany;
  /** @nullable */
  landlordName?: string | null;
  /** @nullable */
  propertyManagementId?: number | null;
  propertyManagement?: SDJCRMCoreCompanyEntitiesCompany;
  /** @nullable */
  propertyManagementName?: string | null;
  /** @nullable */
  link?: string | null;
  /** @nullable */
  totalSize?: number | null;
  /** @nullable */
  landArea?: number | null;
  /** @nullable */
  isEnableStackingPlan?: boolean | null;
  /** @nullable */
  ceilingHeight?: number | null;
  /** @nullable */
  backupPower?: string | null;
  /** @nullable */
  airConditioning?: string | null;
  /** @nullable */
  electricityCost?: number | null;
  /** @nullable */
  waterCost?: number | null;
  /** @nullable */
  motorbikeCost?: number | null;
  /** @nullable */
  petFees?: number | null;
  /** @nullable */
  dedicatedCarCost?: number | null;
  /** @nullable */
  managementFee?: number | null;
  /** @nullable */
  askingRent?: number | null;
  /** @nullable */
  askingPrice?: number | null;
  /** @nullable */
  contactId?: number | null;
  contact?: SDJCRMCoreContactsEntitiesContact;
  /** @nullable */
  price?: number | null;
  sortNumber?: number;
  /** @nullable */
  authorizationNumber?: string | null;
  /** @nullable */
  effectiveDate?: string | null;
  /** @nullable */
  persionSignLA?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersUser;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersUser;
}
