/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementDetailsOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementDetailsOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUnitOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementUnitOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUserInchargeOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementUserInchargeOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementStatus } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementStatus';

export interface SDJCRMApplicationLABookingDtoBookingOutputDto {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  stageId?: number;
  stage?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementStatus;
  uniqueId?: string;
  /** @nullable */
  occupier?: string | null;
  /** @nullable */
  referenceNumber?: string | null;
  /** @nullable */
  leaseAgreementUnit?: SDJCRMApplicationLADtoLeaseAgreementUnitOutputDto[] | null;
  commencementDate?: string;
  expiryDate?: string;
  /**
     * @minLength 0
     * @maxLength 512
     * @nullable
     */
  bookingDealer?: string | null;
  statusId: number;
  /** @nullable */
  leaseAgreementUserIncharge?: SDJCRMApplicationLADtoLeaseAgreementUserInchargeOutputDto[] | null;
  /** @nullable */
  leaseAgreementDetails?: SDJCRMApplicationLADtoLeaseAgreementDetailsOutputDto[] | null;
  status?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  isActive?: boolean;
  contractAmount?: number;
  /** @nullable */
  contractAmountIncludeVat?: number | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
}
