/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationInquiriesDtoInquiryReservationUnitOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryReservationUnitOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto } from './sDJCRMApplicationInquiriesDtoInquirySimpleOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';

export interface SDJCRMApplicationInquiriesDtoInquiryReservationOutputDto {
  id?: number;
  inquiryId?: number;
  /** @nullable */
  reservationTime?: string | null;
  /** @nullable */
  fromDate?: string | null;
  /** @nullable */
  toDate?: string | null;
  /** @nullable */
  expiryDate?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  reservationUnit?: SDJCRMApplicationInquiriesDtoInquiryReservationUnitOutputDto[] | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  inquiry?: SDJCRMApplicationInquiriesDtoInquirySimpleOutputDto;
}
