/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAuditLogDtoAuditLogListDto {
  id?: number;
  /** @nullable */
  userId?: number | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  impersonatorTenantId?: number | null;
  /** @nullable */
  impersonatorUserId?: number | null;
  /** @nullable */
  serviceName?: string | null;
  /** @nullable */
  methodName?: string | null;
  /** @nullable */
  parameters?: string | null;
  executionTime?: string;
  executionDuration?: number;
  /** @nullable */
  clientIpAddress?: string | null;
  /** @nullable */
  clientName?: string | null;
  /** @nullable */
  browserInfo?: string | null;
  /** @nullable */
  exception?: string | null;
  /** @nullable */
  customData?: string | null;
}
