/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoSimpleAssetOutputDto } from './sDJCRMApplicationAssetManagementDtoSimpleAssetOutputDto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';
import type { SDJCRMApplicationUnitDtoSimpleUnitOutputDto } from './sDJCRMApplicationUnitDtoSimpleUnitOutputDto';
import type { SDJCRMApplicationZoneDtoZoneOutputDto } from './sDJCRMApplicationZoneDtoZoneOutputDto';

export interface SDJCRMApplicationUnitHandoverDtoAssetUnitHandoverOutputDto {
  id?: number;
  asset?: SDJCRMApplicationAssetManagementDtoSimpleAssetOutputDto;
  isMoved?: boolean;
  /** @nullable */
  value?: number | null;
  /** @nullable */
  quantity?: number | null;
  /** @nullable */
  isUsed?: boolean | null;
  toProject?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  toZone?: SDJCRMApplicationZoneDtoZoneOutputDto;
  toUnit?: SDJCRMApplicationUnitDtoSimpleUnitOutputDto;
}
