/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement';
import type { SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionDetails } from './sDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionDetails';

export interface SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionPhase {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterUserId?: number | null;
  /** @nullable */
  deletionTime?: string | null;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreement;
  leaseAgreementCommissionMasterId?: number;
  /** @nullable */
  phase?: string | null;
  departmentCommissionAmountByPhase?: number;
  dealerCommissionAmountByPhase?: number;
  numPhase?: number;
  billingDate?: string;
  actBillingDate?: string;
  statusId?: number;
  percent?: number;
  /** @nullable */
  leaseAgreementCommissionDetails?: SDJCRMCoreLeaseAgreementsEntitiesLeaseAgreementCommissionDetails[] | null;
}
