/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreCompanyEntitiesIndustry {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  industryName?: string | null;
  /** @nullable */
  industryDescription?: string | null;
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  typeCode?: string | null;
  isActive?: boolean;
}
