/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationCommmentCommentInputDto {
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
  /** @nullable */
  userIds?: number[] | null;
}
