/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAssetManagementDtoAssetDetailOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetDetailOutputDto';
import type { SDJCRMApplicationAssetManagementDtoAssetOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetOutputDto';
import type { SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto } from './sDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto';
import type { SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStartEndDateDto } from './sDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStartEndDateDto';
import type { SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStatusOutputDto } from './sDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStatusOutputDto';
import type { SDJCRMApplicationPlanMaintenanceDtoPlanTaskOutputDto } from './sDJCRMApplicationPlanMaintenanceDtoPlanTaskOutputDto';
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';
import type { SDJCRMApplicationProviderDtoProviderOutputDto } from './sDJCRMApplicationProviderDtoProviderOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto';
import type { SDJCRMApplicationZoneDtoZoneOutputDto } from './sDJCRMApplicationZoneDtoZoneOutputDto';

export interface SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceOutputDto {
  id?: number;
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  zone?: SDJCRMApplicationZoneDtoZoneOutputDto;
  asset?: SDJCRMApplicationAssetManagementDtoAssetDetailOutputDto;
  /** @nullable */
  description?: string | null;
  pic?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  status?: SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStatusOutputDto;
  startDate?: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  actualStartDate?: string | null;
  /** @nullable */
  actualEndDate?: string | null;
  repairingCost?: number;
  /** @nullable */
  serviceProviderId?: number | null;
  serviceProvider?: SDJCRMApplicationProviderDtoProviderOutputDto;
  uniqueId?: string;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoSimpleUserOutputDto;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  totalPercentage?: number;
  /** @nullable */
  planTasks?: SDJCRMApplicationPlanMaintenanceDtoPlanTaskOutputDto[] | null;
  /** @nullable */
  planStartEndDates?: SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStartEndDateDto[] | null;
  assetTypeLv1?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto;
  assetTypeLv2?: SDJCRMApplicationAssetManagementDtoAssetTypeAssetTypeOutputDto;
  /** @nullable */
  assetIds?: number[] | null;
  /** @nullable */
  assets?: SDJCRMApplicationAssetManagementDtoAssetOutputDto[] | null;
}
