/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationProjectProjectAddressProjectAddressOutputDto {
  id?: number;
  projectId?: number;
  countryId?: number;
  /** @nullable */
  countryName?: string | null;
  /** @nullable */
  provinceId?: number | null;
  /** @nullable */
  provinceName?: string | null;
  /** @nullable */
  districtId?: number | null;
  /** @nullable */
  districtName?: string | null;
  /** @nullable */
  wardId?: number | null;
  /** @nullable */
  wardName?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  addressVi?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  regionId?: number | null;
  /** @nullable */
  regionName?: string | null;
}
