/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreLocalizationDtoLocalizationDto } from './sDJCRMCoreLocalizationDtoLocalizationDto';

export interface SDJCRMApplicationNewsNewsCreateDto {
  /** @nullable */
  subjects?: SDJCRMCoreLocalizationDtoLocalizationDto[] | null;
  /** @nullable */
  contents?: SDJCRMCoreLocalizationDtoLocalizationDto[] | null;
  /** @nullable */
  shortDescriptions?: SDJCRMCoreLocalizationDtoLocalizationDto[] | null;
  categoryId?: number;
  sortOrder?: number;
  isActive?: boolean;
  startTime?: string;
  endTime?: string;
  isAllProject?: boolean;
  isPublic?: boolean;
  isHighlight?: boolean;
}
