/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationInquiriesDtoInquiryAddressOutputDto {
  id?: number;
  inquiryId?: number;
  countryId?: number;
  /** @nullable */
  countryName?: string | null;
  /** @nullable */
  provinceId?: number | null;
  /** @nullable */
  provinceName?: string | null;
  /** @nullable */
  districtId?: number | null;
  /** @nullable */
  districtName?: string | null;
  /** @nullable */
  address?: string | null;
}
