/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationRolesDtoFlatPermissionDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  description?: string | null;
}
