/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationTemplateManagementDtoAvailableLanguageOutputDto } from './sDJCRMApplicationTemplateManagementDtoAvailableLanguageOutputDto';
import type { SDJCRMApplicationTemplateManagementDtoNotificationParameterOutputDto } from './sDJCRMApplicationTemplateManagementDtoNotificationParameterOutputDto';
import type { SDJCRMApplicationTemplateManagementDtoNotificationTemplateOutput } from './sDJCRMApplicationTemplateManagementDtoNotificationTemplateOutput';
import type { SDJCRMApplicationTemplateManagementDtoNotificationTypeOutput } from './sDJCRMApplicationTemplateManagementDtoNotificationTypeOutput';

export interface SDJCRMApplicationTemplateManagementDtoNotificationTemplateMapOutput {
  id?: number;
  key?: string;
  notificationTypeId?: number;
  notificationMethod?: number;
  isActive?: boolean;
  notificationType?: SDJCRMApplicationTemplateManagementDtoNotificationTypeOutput;
  /** @nullable */
  availableLanguages?: SDJCRMApplicationTemplateManagementDtoAvailableLanguageOutputDto[] | null;
  notificationTemplate?: SDJCRMApplicationTemplateManagementDtoNotificationTemplateOutput;
  /** @nullable */
  notificationTemplates?: SDJCRMApplicationTemplateManagementDtoNotificationTemplateOutput[] | null;
  /** @nullable */
  parameters?: SDJCRMApplicationTemplateManagementDtoNotificationParameterOutputDto[] | null;
}
