/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationProviderDtoProviderUpdateDto {
  id?: number;
  typeId?: number;
  /** @nullable */
  taxCode?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  primaryPhone?: string | null;
  /** @nullable */
  primaryEmail?: string | null;
  /** @nullable */
  primaryAddress?: string | null;
  /** @nullable */
  secondaryPhone?: string | null;
  /** @nullable */
  secondaryEmail?: string | null;
  /** @nullable */
  secondaryAddress?: string | null;
  /** @nullable */
  description?: string | null;
}
