/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationUnitDtoUnitFacilityMapOutputDto {
  id?: number;
  unitFacilityId?: number;
  unitFacility?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  unitId?: number;
  /** @nullable */
  description?: string | null;
}
