/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationInquiriesDtoInquirySiteVisitInputDto {
  id?: number;
  inquiryId?: number;
  /** @nullable */
  siteVisitTime?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  unitIds?: number[] | null;
}
