/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceOutputDto } from './sDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceOutputDto';

export interface SDJCRMApplicationPlanMaintenanceDtoData {
  month?: number;
  /** @nullable */
  monthName?: string | null;
  /** @nullable */
  planMaintenances?: SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceOutputDto[] | null;
}
