/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType = typeof SDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType[keyof typeof SDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType];


export const SDJCRMCoreSharedPlanMaintenancePlanMaintenanceConstantsAssetMoveType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
