/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationPlanMaintenanceDtoPlanMaintenanceStatusOutputDto {
  id?: number;
  order?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  backgroundColor?: string | null;
  /** @nullable */
  color?: string | null;
  isActive?: boolean;
}
