/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCategoryLevelOutputDto } from './sDJCRMApplicationCategoryLevelOutputDto';
import type { SDJCRMApplicationCompanyDtoCompanySimpleOutputDto } from './sDJCRMApplicationCompanyDtoCompanySimpleOutputDto';

export interface SDJCRMApplicationCompanyCompanyContactCompanyContactOutputDto {
  id?: number;
  contactId?: number;
  /** @nullable */
  contactName?: string | null;
  companyId?: number;
  company?: SDJCRMApplicationCompanyDtoCompanySimpleOutputDto;
  /** @nullable */
  levelId?: number | null;
  level?: SDJCRMApplicationCategoryLevelOutputDto;
  /** @nullable */
  title?: string | null;
  isActive?: boolean;
}
