/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationInquiriesDtoInquiryAddressInputDto {
  id?: number;
  inquiryId?: number;
  /** @nullable */
  countryId?: number | null;
  /** @nullable */
  provinceId?: number | null;
  /** @nullable */
  districtId?: number | null;
  /** @nullable */
  address?: string | null;
  isActive?: boolean;
}
