/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SDJCRMCoreSharedProjectsUnitsStatusConstants = typeof SDJCRMCoreSharedProjectsUnitsStatusConstants[keyof typeof SDJCRMCoreSharedProjectsUnitsStatusConstants];


export const SDJCRMCoreSharedProjectsUnitsStatusConstants = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const;
