/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMCoreSharedDocumentsDtoDocumentTypeOutput } from './sDJCRMCoreSharedDocumentsDtoDocumentTypeOutput';
import type { SDJCRMCoreSharedUserDtoSimpleUserOutputDto } from './sDJCRMCoreSharedUserDtoSimpleUserOutputDto';

export interface SDJCRMCoreSharedDocumentsDtoDocumentOutput {
  id?: number;
  /** @nullable */
  fileUrl?: string | null;
  /** @nullable */
  mimeType?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  originalFileName?: string | null;
  /** @nullable */
  moduleName?: string | null;
  /** @nullable */
  fileName?: string | null;
  guid?: string;
  /** @nullable */
  size?: number | null;
  /** @nullable */
  documentName?: string | null;
  documentTypeId?: number;
  documentType?: SDJCRMCoreSharedDocumentsDtoDocumentTypeOutput;
  uploadDate?: string;
  creatorUser?: SDJCRMCoreSharedUserDtoSimpleUserOutputDto;
  lastModifierUser?: SDJCRMCoreSharedUserDtoSimpleUserOutputDto;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
}
