/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreSharedOrganizationUnitDtoUserToOrganizationUnitOutput {
  /** @minimum 1 */
  organizationUnitId?: number;
  /** @nullable */
  organizationUnitName?: string | null;
  isHead?: boolean;
}
