/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLADtoDepositLeaseAgreementDepositInputDto {
  id?: number;
  leaseAgreementId?: number;
  /** @nullable */
  description?: string | null;
  vatPercent?: number;
  vatAmount?: number;
  depositAmount?: number;
  depositDate?: string;
}
