/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationDefectDefectManagementDtoConstructionIssueInputDto {
  /** @nullable */
  id?: number | null;
  statusId: number;
  defectId: number;
  /**
     * @minLength 0
     * @maxLength 250
     */
  title: string;
  /**
     * @minLength 0
     * @maxLength 5000
     * @nullable
     */
  description?: string | null;
}
