/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLocationsDtoDistrictOutputDto {
  id?: number;
  districtId?: number;
  provinceId?: number;
  /** @nullable */
  districtCode?: string | null;
  /** @nullable */
  districtName?: string | null;
  /** @nullable */
  fullName?: string | null;
}
