/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationLADtoDepositLeaseAgreementDepositRefundInputDto {
  id?: number;
  leaseAgreementId?: number;
  /** @nullable */
  voucherNo?: string | null;
  /** @nullable */
  remark?: string | null;
  refundAmount?: number;
  /** @nullable */
  voucherDate?: string | null;
  /** @nullable */
  refundTypeIds?: number[] | null;
}
