/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationProjectDtoSimpleProjectOutputDto } from './sDJCRMApplicationProjectDtoSimpleProjectOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';

export interface SDJCRMApplicationZoneDtoZoneOutputDto {
  id?: number;
  uniqueId?: string;
  /** @nullable */
  zoneName?: string | null;
  size?: number;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  project?: SDJCRMApplicationProjectDtoSimpleProjectOutputDto;
  /** @nullable */
  totalAssets?: number | null;
}
