/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreLeaseAgreementsDtoLeaseAgreementDetailFeeTypeInputDto {
  amountIncludeVAT?: number;
  rentAmount?: number;
  feeTypeId?: number;
  startDate?: string;
  endDate?: string;
  numMonth?: number;
  numDay?: number;
  /** @nullable */
  rowIndex?: number | null;
}
