/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationCompanyCompanyContactCompanyContactInputDto {
  id?: number;
  contactId?: number;
  companyId?: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  levelId?: number | null;
  isActive?: boolean;
}
