/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationDefectDefectConfigurationDtoDefectStageOutputDto } from './sDJCRMApplicationDefectDefectConfigurationDtoDefectStageOutputDto';
import type { SDJCRMCoreAuthorizationUsersDtoUserSimpleDto } from './sDJCRMCoreAuthorizationUsersDtoUserSimpleDto';
import type { SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum } from './sDJCRMCoreSharedEnumsDefectConfigurationTypeEnum';

export interface SDJCRMApplicationDefectDefectConfigurationDtoDefectConfigurationOutputDto {
  id?: number;
  defectPriorityId?: number;
  defectStageId?: number;
  defectStage?: SDJCRMApplicationDefectDefectConfigurationDtoDefectStageOutputDto;
  days?: number;
  defectConfigurationType?: SDJCRMCoreSharedEnumsDefectConfigurationTypeEnum;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
  lastModifierUser?: SDJCRMCoreAuthorizationUsersDtoUserSimpleDto;
}
