/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreLeaseAgreementsDtoLeaseAgreementDiscountOutputDto {
  laDiscountAmountIncludeVat?: number;
  laDiscountAmountExcludeVat?: number;
  discountAmountIncludeVat?: number;
  discountAmountExcludeVat?: number;
}
