/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationNewsNewsCategoryOutputDto } from './sDJCRMApplicationNewsNewsCategoryOutputDto';
import type { SDJCRMCoreLocalizationDtoLocalizationDto } from './sDJCRMCoreLocalizationDtoLocalizationDto';
import type { SDJCRMCoreSharedDocumentsDtoDocumentOutput } from './sDJCRMCoreSharedDocumentsDtoDocumentOutput';

export interface SDJCRMApplicationNewsNewsEditOutputDto {
  id?: number;
  creationTime?: string;
  /** @nullable */
  creatorUserId?: number | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierUserId?: number | null;
  uniqueId?: string;
  /** @nullable */
  subjects?: SDJCRMCoreLocalizationDtoLocalizationDto[] | null;
  /** @nullable */
  contents?: SDJCRMCoreLocalizationDtoLocalizationDto[] | null;
  /** @nullable */
  shortDescriptions?: SDJCRMCoreLocalizationDtoLocalizationDto[] | null;
  categoryId?: number;
  category?: SDJCRMApplicationNewsNewsCategoryOutputDto;
  sortOrder?: number;
  startTime?: string;
  endTime?: string;
  isPublic?: boolean;
  isHighlight?: boolean;
  isActive?: boolean;
  file?: SDJCRMCoreSharedDocumentsDtoDocumentOutput;
}
