/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionDetailsOutputDto } from './sDJCRMApplicationLADtoCommissionLeaseAgreementCommissionDetailsOutputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto } from './sDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto';

export interface SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionPhaseOutputDto {
  id?: number;
  numPhase?: number;
  /** @nullable */
  phase?: string | null;
  leaseAgreementCommissionMasterId?: number;
  leaseAgreementId?: number;
  leaseAgreement?: SDJCRMApplicationLADtoLeaseAgreementSimpleOutputDto;
  billingDate?: string;
  actBillingDate?: string;
  statusId?: number;
  dealerCommissionAmountByPhase?: number;
  departmentCommissionAmountByPhase?: number;
  percent?: number;
  /** @nullable */
  leaseAgreementCommissionDetails?: SDJCRMApplicationLADtoCommissionLeaseAgreementCommissionDetailsOutputDto[] | null;
}
