/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationAuthorizationAccountsDtoUserAvailabilityState } from './sDJCRMApplicationAuthorizationAccountsDtoUserAvailabilityState';

export interface SDJCRMApplicationAuthorizationAccountsDtoIsUserAvailableOutput {
  state?: SDJCRMApplicationAuthorizationAccountsDtoUserAvailabilityState;
}
