/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMCoreSharedOrganizationUnitOrganizationUnitOutputDto {
  id?: number;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  displayName?: string | null;
}
