/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationAuthorizationAccountsDtoIsTenantAvailableInput {
  /**
     * @minLength 0
     * @maxLength 64
     */
  tenancyName: string;
}
