/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationCompanyDtoCompanySimpleOutputDto } from './sDJCRMApplicationCompanyDtoCompanySimpleOutputDto';
import type { SDJCRMApplicationContactDtoContactOutputDto } from './sDJCRMApplicationContactDtoContactOutputDto';
import type { SDJCRMApplicationContactDtoContactSimpleOutputDto } from './sDJCRMApplicationContactDtoContactSimpleOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryAddressOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryAddressOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryFacilityOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryFacilityOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryFacingOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryFacingOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryOrganizationUnitOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryOrganizationUnitOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryProjectOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryProjectOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryPropertyTypeOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryPropertyTypeOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryServiceTypeOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryServiceTypeOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryUnitOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryUnitOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryUnitTypeOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryUnitTypeOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryUserOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryUserOutputDto';
import type { SDJCRMApplicationInquiriesDtoInquiryViewOutputDto } from './sDJCRMApplicationInquiriesDtoInquiryViewOutputDto';
import type { SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto } from './sDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto';
import type { SDJCRMCoreCategoryDtoCategoryOutputBasic } from './sDJCRMCoreCategoryDtoCategoryOutputBasic';

export interface SDJCRMApplicationInquiriesDtoInquiryOutputDto {
  id?: number;
  uniqueId?: string;
  /** @nullable */
  inquiryName?: string | null;
  /** @nullable */
  companyId?: number | null;
  company?: SDJCRMApplicationCompanyDtoCompanySimpleOutputDto;
  contactId?: number;
  contact?: SDJCRMApplicationContactDtoContactOutputDto;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  fromSize?: number | null;
  /** @nullable */
  toSize?: number | null;
  /** @nullable */
  occupierName?: string | null;
  statusId?: number;
  status?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  statusDetailId?: number;
  statusDetail?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  /** @nullable */
  moveInDate?: string | null;
  leaseTerm?: number;
  /** @nullable */
  occupierId?: number | null;
  occupier?: SDJCRMApplicationContactDtoContactSimpleOutputDto;
  /** @nullable */
  fromPrice?: number | null;
  /** @nullable */
  toPrice?: number | null;
  /** @nullable */
  livingRoom?: number | null;
  /** @nullable */
  bedRoom?: number | null;
  /** @nullable */
  helperRoom?: number | null;
  /** @nullable */
  bathRoom?: number | null;
  /** @nullable */
  balcony?: number | null;
  /** @nullable */
  motobikePark?: number | null;
  /** @nullable */
  carPark?: number | null;
  sourceId?: number;
  /** @nullable */
  numReservation?: number | null;
  source?: SDJCRMCoreCategoryDtoCategoryOutputBasic;
  isActive?: boolean;
  /** @nullable */
  inquiryAddress?: SDJCRMApplicationInquiriesDtoInquiryAddressOutputDto[] | null;
  /** @nullable */
  inquiryViewMap?: SDJCRMApplicationInquiriesDtoInquiryViewOutputDto[] | null;
  /** @nullable */
  inquiryPropertyTypeMap?: SDJCRMApplicationInquiriesDtoInquiryPropertyTypeOutputDto[] | null;
  /** @nullable */
  inquiryFacingMap?: SDJCRMApplicationInquiriesDtoInquiryFacingOutputDto[] | null;
  /** @nullable */
  inquiryServiceTypeMap?: SDJCRMApplicationInquiriesDtoInquiryServiceTypeOutputDto[] | null;
  /** @nullable */
  inquiryUnitTypeMap?: SDJCRMApplicationInquiriesDtoInquiryUnitTypeOutputDto[] | null;
  /** @nullable */
  inquiryProjectMap?: SDJCRMApplicationInquiriesDtoInquiryProjectOutputDto[] | null;
  /** @nullable */
  inquiryUnitMap?: SDJCRMApplicationInquiriesDtoInquiryUnitOutputDto[] | null;
  /** @nullable */
  inquiryFacilityMap?: SDJCRMApplicationInquiriesDtoInquiryFacilityOutputDto[] | null;
  /** @nullable */
  inquiryUser?: SDJCRMApplicationInquiriesDtoInquiryUserOutputDto[] | null;
  /** @nullable */
  inquiryOrganizationUnit?: SDJCRMApplicationInquiriesDtoInquiryOrganizationUnitOutputDto[] | null;
  creationTime?: string;
  /** @nullable */
  lastModificationTime?: string | null;
  creatorUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
  lastModifierUser?: SDJCRMApplicationUsersUserBaseBaseDtoUserOutputDto;
}
