/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SDJCRMApplicationLADtoLeaseAgreementDetailsInputDto } from './sDJCRMApplicationLADtoLeaseAgreementDetailsInputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUnitInputDto } from './sDJCRMApplicationLADtoLeaseAgreementUnitInputDto';
import type { SDJCRMApplicationLADtoLeaseAgreementUserInchargeInputDto } from './sDJCRMApplicationLADtoLeaseAgreementUserInchargeInputDto';

export interface SDJCRMApplicationLABookingDtoBookingCreateDto {
  isRequest?: boolean;
  stageId?: number;
  /** @nullable */
  occupier?: string | null;
  /** @nullable */
  referenceNumber?: string | null;
  /** @nullable */
  leaseAgreementUnit?: SDJCRMApplicationLADtoLeaseAgreementUnitInputDto[] | null;
  commencementDate?: string;
  expiryDate?: string;
  /**
     * @minLength 0
     * @maxLength 512
     * @nullable
     */
  bookingDealer?: string | null;
  statusId: number;
  /** @nullable */
  contractAmountIncludeVat?: number | null;
  /** @nullable */
  leaseAgreementUserIncharge?: SDJCRMApplicationLADtoLeaseAgreementUserInchargeInputDto[] | null;
  /** @nullable */
  leaseAgreementDetails?: SDJCRMApplicationLADtoLeaseAgreementDetailsInputDto[] | null;
  contractAmount?: number;
}
