/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export interface SDJCRMApplicationContactContactPhoneContactPhoneInputDto {
  id?: number;
  contactId?: number;
  /** @nullable */
  phoneTypeId?: number | null;
  /** @nullable */
  countryId?: number | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  isPrimary?: boolean | null;
  isActive?: boolean;
}
