/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionCustomAttributeData } from './systemReflectionCustomAttributeData';
import type { SystemReflectionEventAttributes } from './systemReflectionEventAttributes';
import type { SystemReflectionMemberTypes } from './systemReflectionMemberTypes';
import type { SystemReflectionMethodInfo } from './systemReflectionMethodInfo';
import type { SystemReflectionModule } from './systemReflectionModule';
import type { SystemType } from './systemType';

export interface SystemReflectionEventInfo {
  /** @nullable */
  readonly name?: string | null;
  declaringType?: SystemType;
  reflectedType?: SystemType;
  module?: SystemReflectionModule;
  /** @nullable */
  readonly customAttributes?: readonly SystemReflectionCustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  memberType?: SystemReflectionMemberTypes;
  attributes?: SystemReflectionEventAttributes;
  readonly isSpecialName?: boolean;
  addMethod?: SystemReflectionMethodInfo;
  removeMethod?: SystemReflectionMethodInfo;
  raiseMethod?: SystemReflectionMethodInfo;
  readonly isMulticast?: boolean;
  eventHandlerType?: SystemType;
}
