/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemRuntimeInteropServicesLayoutKind } from './systemRuntimeInteropServicesLayoutKind';

export interface SystemRuntimeInteropServicesStructLayoutAttribute {
  readonly typeId?: unknown | null;
  value?: SystemRuntimeInteropServicesLayoutKind;
}
