/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SystemReflectionPropertyAttributes = typeof SystemReflectionPropertyAttributes[keyof typeof SystemReflectionPropertyAttributes];


export const SystemReflectionPropertyAttributes = {
  NUMBER_0: 0,
  NUMBER_512: 512,
  NUMBER_1024: 1024,
  NUMBER_4096: 4096,
  NUMBER_8192: 8192,
  NUMBER_16384: 16384,
  NUMBER_32768: 32768,
  NUMBER_62464: 62464,
} as const;
