/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionCustomAttributeData } from './systemReflectionCustomAttributeData';
import type { SystemReflectionMemberTypes } from './systemReflectionMemberTypes';
import type { SystemReflectionMethodInfo } from './systemReflectionMethodInfo';
import type { SystemReflectionModule } from './systemReflectionModule';
import type { SystemReflectionPropertyAttributes } from './systemReflectionPropertyAttributes';
import type { SystemType } from './systemType';

export interface SystemReflectionPropertyInfo {
  /** @nullable */
  readonly name?: string | null;
  declaringType?: SystemType;
  reflectedType?: SystemType;
  module?: SystemReflectionModule;
  /** @nullable */
  readonly customAttributes?: readonly SystemReflectionCustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  memberType?: SystemReflectionMemberTypes;
  propertyType?: SystemType;
  attributes?: SystemReflectionPropertyAttributes;
  readonly isSpecialName?: boolean;
  readonly canRead?: boolean;
  readonly canWrite?: boolean;
  getMethod?: SystemReflectionMethodInfo;
  setMethod?: SystemReflectionMethodInfo;
}
