/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionCallingConventions } from './systemReflectionCallingConventions';
import type { SystemReflectionCustomAttributeData } from './systemReflectionCustomAttributeData';
import type { SystemReflectionMemberTypes } from './systemReflectionMemberTypes';
import type { SystemReflectionMethodAttributes } from './systemReflectionMethodAttributes';
import type { SystemReflectionMethodImplAttributes } from './systemReflectionMethodImplAttributes';
import type { SystemReflectionModule } from './systemReflectionModule';
import type { SystemRuntimeMethodHandle } from './systemRuntimeMethodHandle';
import type { SystemType } from './systemType';

export interface SystemReflectionMethodBase {
  memberType?: SystemReflectionMemberTypes;
  /** @nullable */
  readonly name?: string | null;
  declaringType?: SystemType;
  reflectedType?: SystemType;
  module?: SystemReflectionModule;
  /** @nullable */
  readonly customAttributes?: readonly SystemReflectionCustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  attributes?: SystemReflectionMethodAttributes;
  methodImplementationFlags?: SystemReflectionMethodImplAttributes;
  callingConvention?: SystemReflectionCallingConventions;
  readonly isAbstract?: boolean;
  readonly isConstructor?: boolean;
  readonly isFinal?: boolean;
  readonly isHideBySig?: boolean;
  readonly isSpecialName?: boolean;
  readonly isStatic?: boolean;
  readonly isVirtual?: boolean;
  readonly isAssembly?: boolean;
  readonly isFamily?: boolean;
  readonly isFamilyAndAssembly?: boolean;
  readonly isFamilyOrAssembly?: boolean;
  readonly isPrivate?: boolean;
  readonly isPublic?: boolean;
  readonly isConstructedGenericMethod?: boolean;
  readonly isGenericMethod?: boolean;
  readonly isGenericMethodDefinition?: boolean;
  readonly containsGenericParameters?: boolean;
  methodHandle?: SystemRuntimeMethodHandle;
  readonly isSecurityCritical?: boolean;
  readonly isSecuritySafeCritical?: boolean;
  readonly isSecurityTransparent?: boolean;
}
