/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionCustomAttributeData } from './systemReflectionCustomAttributeData';
import type { SystemReflectionFieldAttributes } from './systemReflectionFieldAttributes';
import type { SystemReflectionMemberTypes } from './systemReflectionMemberTypes';
import type { SystemReflectionModule } from './systemReflectionModule';
import type { SystemRuntimeFieldHandle } from './systemRuntimeFieldHandle';
import type { SystemType } from './systemType';

export interface SystemReflectionFieldInfo {
  /** @nullable */
  readonly name?: string | null;
  declaringType?: SystemType;
  reflectedType?: SystemType;
  module?: SystemReflectionModule;
  /** @nullable */
  readonly customAttributes?: readonly SystemReflectionCustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  memberType?: SystemReflectionMemberTypes;
  attributes?: SystemReflectionFieldAttributes;
  fieldType?: SystemType;
  readonly isInitOnly?: boolean;
  readonly isLiteral?: boolean;
  readonly isNotSerialized?: boolean;
  readonly isPinvokeImpl?: boolean;
  readonly isSpecialName?: boolean;
  readonly isStatic?: boolean;
  readonly isAssembly?: boolean;
  readonly isFamily?: boolean;
  readonly isFamilyAndAssembly?: boolean;
  readonly isFamilyOrAssembly?: boolean;
  readonly isPrivate?: boolean;
  readonly isPublic?: boolean;
  readonly isSecurityCritical?: boolean;
  readonly isSecuritySafeCritical?: boolean;
  readonly isSecurityTransparent?: boolean;
  fieldHandle?: SystemRuntimeFieldHandle;
}
