/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SystemReflectionEventAttributes = typeof SystemReflectionEventAttributes[keyof typeof SystemReflectionEventAttributes];


export const SystemReflectionEventAttributes = {
  NUMBER_0: 0,
  NUMBER_512: 512,
  NUMBER_1024: 1024,
} as const;
