/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SystemReflectionMethodImplAttributes = typeof SystemReflectionMethodImplAttributes[keyof typeof SystemReflectionMethodImplAttributes];


export const SystemReflectionMethodImplAttributes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_32: 32,
  NUMBER_64: 64,
  NUMBER_128: 128,
  NUMBER_256: 256,
  NUMBER_512: 512,
  NUMBER_4096: 4096,
  NUMBER_65535: 65535,
} as const;
