/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SystemRuntimeInteropServicesLayoutKind = typeof SystemRuntimeInteropServicesLayoutKind[keyof typeof SystemRuntimeInteropServicesLayoutKind];


export const SystemRuntimeInteropServicesLayoutKind = {
  NUMBER_0: 0,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
