/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SystemReflectionGenericParameterAttributes = typeof SystemReflectionGenericParameterAttributes[keyof typeof SystemReflectionGenericParameterAttributes];


export const SystemReflectionGenericParameterAttributes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_28: 28,
} as const;
