/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SystemReflectionCallingConventions = typeof SystemReflectionCallingConventions[keyof typeof SystemReflectionCallingConventions];


export const SystemReflectionCallingConventions = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_32: 32,
  NUMBER_64: 64,
} as const;
