/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionCustomAttributeData } from './systemReflectionCustomAttributeData';
import type { SystemReflectionMemberTypes } from './systemReflectionMemberTypes';
import type { SystemReflectionModule } from './systemReflectionModule';
import type { SystemType } from './systemType';

export interface SystemReflectionMemberInfo {
  memberType?: SystemReflectionMemberTypes;
  /** @nullable */
  readonly name?: string | null;
  declaringType?: SystemType;
  reflectedType?: SystemType;
  module?: SystemReflectionModule;
  /** @nullable */
  readonly customAttributes?: readonly SystemReflectionCustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
}
