/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemModuleHandle } from './systemModuleHandle';
import type { SystemReflectionAssembly } from './systemReflectionAssembly';
import type { SystemReflectionCustomAttributeData } from './systemReflectionCustomAttributeData';

export interface SystemReflectionModule {
  assembly?: SystemReflectionAssembly;
  /** @nullable */
  readonly fullyQualifiedName?: string | null;
  /** @nullable */
  readonly name?: string | null;
  readonly mdStreamVersion?: number;
  readonly moduleVersionId?: string;
  /** @nullable */
  readonly scopeName?: string | null;
  moduleHandle?: SystemModuleHandle;
  /** @nullable */
  readonly customAttributes?: readonly SystemReflectionCustomAttributeData[] | null;
  readonly metadataToken?: number;
}
