/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionCustomAttributeData } from './systemReflectionCustomAttributeData';
import type { SystemReflectionMethodInfo } from './systemReflectionMethodInfo';
import type { SystemReflectionModule } from './systemReflectionModule';
import type { SystemReflectionTypeInfo } from './systemReflectionTypeInfo';
import type { SystemSecuritySecurityRuleSet } from './systemSecuritySecurityRuleSet';
import type { SystemType } from './systemType';

export interface SystemReflectionAssembly {
  /** @nullable */
  readonly definedTypes?: readonly SystemReflectionTypeInfo[] | null;
  /** @nullable */
  readonly exportedTypes?: readonly SystemType[] | null;
  /**
     * @deprecated
     * @nullable
     */
  readonly codeBase?: string | null;
  entryPoint?: SystemReflectionMethodInfo;
  /** @nullable */
  readonly fullName?: string | null;
  /** @nullable */
  readonly imageRuntimeVersion?: string | null;
  readonly isDynamic?: boolean;
  /** @nullable */
  readonly location?: string | null;
  readonly reflectionOnly?: boolean;
  readonly isCollectible?: boolean;
  readonly isFullyTrusted?: boolean;
  /** @nullable */
  readonly customAttributes?: readonly SystemReflectionCustomAttributeData[] | null;
  /**
     * @deprecated
     * @nullable
     */
  readonly escapedCodeBase?: string | null;
  manifestModule?: SystemReflectionModule;
  /** @nullable */
  readonly modules?: readonly SystemReflectionModule[] | null;
  /** @deprecated */
  readonly globalAssemblyCache?: boolean;
  readonly hostContext?: number;
  securityRuleSet?: SystemSecuritySecurityRuleSet;
}
