/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionCustomAttributeTypedArgument } from './systemReflectionCustomAttributeTypedArgument';
import type { SystemReflectionMemberInfo } from './systemReflectionMemberInfo';

export interface SystemReflectionCustomAttributeNamedArgument {
  memberInfo?: SystemReflectionMemberInfo;
  typedValue?: SystemReflectionCustomAttributeTypedArgument;
  /** @nullable */
  readonly memberName?: string | null;
  readonly isField?: boolean;
}
