/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemType } from './systemType';

export interface SystemReflectionCustomAttributeTypedArgument {
  argumentType?: SystemType;
  value?: unknown | null;
}
