/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SystemSecuritySecurityRuleSet = typeof SystemSecuritySecurityRuleSet[keyof typeof SystemSecuritySecurityRuleSet];


export const SystemSecuritySecurityRuleSet = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
