/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionConstructorInfo } from './systemReflectionConstructorInfo';
import type { SystemReflectionCustomAttributeNamedArgument } from './systemReflectionCustomAttributeNamedArgument';
import type { SystemReflectionCustomAttributeTypedArgument } from './systemReflectionCustomAttributeTypedArgument';
import type { SystemType } from './systemType';

export interface SystemReflectionCustomAttributeData {
  attributeType?: SystemType;
  constructor?: SystemReflectionConstructorInfo;
  /** @nullable */
  readonly constructorArguments?: readonly SystemReflectionCustomAttributeTypedArgument[] | null;
  /** @nullable */
  readonly namedArguments?: readonly SystemReflectionCustomAttributeNamedArgument[] | null;
}
