/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionAssembly } from './systemReflectionAssembly';
import type { SystemReflectionConstructorInfo } from './systemReflectionConstructorInfo';
import type { SystemReflectionCustomAttributeData } from './systemReflectionCustomAttributeData';
import type { SystemReflectionGenericParameterAttributes } from './systemReflectionGenericParameterAttributes';
import type { SystemReflectionMemberTypes } from './systemReflectionMemberTypes';
import type { SystemReflectionMethodBase } from './systemReflectionMethodBase';
import type { SystemReflectionModule } from './systemReflectionModule';
import type { SystemReflectionTypeAttributes } from './systemReflectionTypeAttributes';
import type { SystemRuntimeInteropServicesStructLayoutAttribute } from './systemRuntimeInteropServicesStructLayoutAttribute';
import type { SystemRuntimeTypeHandle } from './systemRuntimeTypeHandle';
import type { SystemType as __SystemType } from './systemType';

export interface SystemType {
  /** @nullable */
  readonly name?: string | null;
  /** @nullable */
  readonly customAttributes?: readonly SystemReflectionCustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  readonly isInterface?: boolean;
  memberType?: SystemReflectionMemberTypes;
  /** @nullable */
  readonly namespace?: string | null;
  /** @nullable */
  readonly assemblyQualifiedName?: string | null;
  /** @nullable */
  readonly fullName?: string | null;
  assembly?: SystemReflectionAssembly;
  module?: SystemReflectionModule;
  readonly isNested?: boolean;
  declaringType?: __SystemType;
  declaringMethod?: SystemReflectionMethodBase;
  reflectedType?: __SystemType;
  underlyingSystemType?: __SystemType;
  readonly isTypeDefinition?: boolean;
  readonly isArray?: boolean;
  readonly isByRef?: boolean;
  readonly isPointer?: boolean;
  readonly isConstructedGenericType?: boolean;
  readonly isGenericParameter?: boolean;
  readonly isGenericTypeParameter?: boolean;
  readonly isGenericMethodParameter?: boolean;
  readonly isGenericType?: boolean;
  readonly isGenericTypeDefinition?: boolean;
  readonly isSZArray?: boolean;
  readonly isVariableBoundArray?: boolean;
  readonly isByRefLike?: boolean;
  readonly hasElementType?: boolean;
  /** @nullable */
  readonly genericTypeArguments?: readonly SystemType[] | null;
  readonly genericParameterPosition?: number;
  genericParameterAttributes?: SystemReflectionGenericParameterAttributes;
  attributes?: SystemReflectionTypeAttributes;
  readonly isAbstract?: boolean;
  readonly isImport?: boolean;
  readonly isSealed?: boolean;
  readonly isSpecialName?: boolean;
  readonly isClass?: boolean;
  readonly isNestedAssembly?: boolean;
  readonly isNestedFamANDAssem?: boolean;
  readonly isNestedFamily?: boolean;
  readonly isNestedFamORAssem?: boolean;
  readonly isNestedPrivate?: boolean;
  readonly isNestedPublic?: boolean;
  readonly isNotPublic?: boolean;
  readonly isPublic?: boolean;
  readonly isAutoLayout?: boolean;
  readonly isExplicitLayout?: boolean;
  readonly isLayoutSequential?: boolean;
  readonly isAnsiClass?: boolean;
  readonly isAutoClass?: boolean;
  readonly isUnicodeClass?: boolean;
  readonly isCOMObject?: boolean;
  readonly isContextful?: boolean;
  readonly isEnum?: boolean;
  readonly isMarshalByRef?: boolean;
  readonly isPrimitive?: boolean;
  readonly isValueType?: boolean;
  readonly isSignatureType?: boolean;
  readonly isSecurityCritical?: boolean;
  readonly isSecuritySafeCritical?: boolean;
  readonly isSecurityTransparent?: boolean;
  structLayoutAttribute?: SystemRuntimeInteropServicesStructLayoutAttribute;
  typeInitializer?: SystemReflectionConstructorInfo;
  typeHandle?: SystemRuntimeTypeHandle;
  readonly guid?: string;
  baseType?: __SystemType;
  readonly isSerializable?: boolean;
  readonly containsGenericParameters?: boolean;
  readonly isVisible?: boolean;
}
