/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */

export type SystemReflectionMethodAttributes = typeof SystemReflectionMethodAttributes[keyof typeof SystemReflectionMethodAttributes];


export const SystemReflectionMethodAttributes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_32: 32,
  NUMBER_64: 64,
  NUMBER_128: 128,
  NUMBER_256: 256,
  NUMBER_512: 512,
  NUMBER_1024: 1024,
  NUMBER_2048: 2048,
  NUMBER_4096: 4096,
  NUMBER_8192: 8192,
  NUMBER_16384: 16384,
  NUMBER_32768: 32768,
  NUMBER_53248: 53248,
} as const;
