/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * CRM Leasing API
 * OpenAPI spec version: v1
 */
import type { SystemReflectionCustomAttributeData } from './systemReflectionCustomAttributeData';
import type { SystemReflectionMemberInfo } from './systemReflectionMemberInfo';
import type { SystemReflectionParameterAttributes } from './systemReflectionParameterAttributes';
import type { SystemType } from './systemType';

export interface SystemReflectionParameterInfo {
  attributes?: SystemReflectionParameterAttributes;
  member?: SystemReflectionMemberInfo;
  /** @nullable */
  readonly name?: string | null;
  parameterType?: SystemType;
  readonly position?: number;
  readonly isIn?: boolean;
  readonly isLcid?: boolean;
  readonly isOptional?: boolean;
  readonly isOut?: boolean;
  readonly isRetval?: boolean;
  readonly defaultValue?: unknown | null;
  readonly rawDefaultValue?: unknown | null;
  readonly hasDefaultValue?: boolean;
  /** @nullable */
  readonly customAttributes?: readonly SystemReflectionCustomAttributeData[] | null;
  readonly metadataToken?: number;
}
